//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Blackjacksp.rc
//
#define IDS_APP_TITLE                   1
#define IDC_BJACK                       2
#define IDS_IMPLICIT_SOFTWARE           3
#define IDB_Blackjack                   4
#define IDS_WEBSITE                     5
#define IDS_BTNS_HIT                    6
#define IDS_STRING7                     7
#define IDS_STRING8                     8
#define IDS_STRING9                     9
#define IDD_DLG_Basic                   9
#define IDS_STRING10                    10
#define IDS_STRING11                    11
#define IDS_RESULT_WIN                  12
#define IDS_RESULT_LOSE                 13
#define IDS_RESULT_BLACKJACK            14
#define IDS_RESULT_DRAW                 15
#define IDS_RESULT_SURRENDER            16
#define IDS_RESULT_NULL                 17
#define IDS_SOFTKEY_TEXT_MENU           18
#define IDS_DEMO_Over                   18
#define IDS_SOFTKEY_TEXT_SAVE           19
#define IDS_Bank                        19
#define IDS_SOFTKEY_TEXT_CANCEL         20
#define IDS_Bet                         20
#define IDS_VERSION                     21
#define IDS_DIFF_EASY                   22
#define IDS_DIFF_NORMAL                 23
#define IDS_DIFF_EXPERT                 24
#define IDS_SOUND_OFF                   25
#define IDS_SOUND_ON                    26
#define IDS_MENU_Resume                 27
#define IDS_MENU_New                    28
#define IDS_MENU_Options                29
#define IDS_MENU_Help                   30
#define IDS_MENU_Quit                   31
#define IDS_BJ_2to1                     32
#define IDS_BJ_3to2                     33
#define IDS_BROKE_CAPTION               34
#define IDS_BROKE_MESSAGE               35
#define IDS_MENU_HiScores               36
#define IDS_MENU_About                  37
#define IDS_MENU_Exit                   38
#define IDS_MENU_NewGame                39
#define IDS_MENU_Yes                    40
#define IDS_MENU_No                     41
#define IDS_MSG_Exit                    42
#define IDS_ABOUT_1                     43
#define IDS_MENU_Back                   44
#define IDS_LBL_Bank                    45
#define IDS_LBL_Date                    46
#define IDS_LBL_PlaySounds              47
#define IDS_LBL_CardCountView           48
#define IDS_LBL_CardCounting            49
#define IDS_LBL_GameDifficulty          50
#define IDS_CMB_CCV_On                  51
#define IDS_CMB_CCV_Semi                52
#define IDS_CMB_CCV_Off                 53
#define IDS_CMB_CC_Wizard               54
#define IDS_CMB_CC_KO                   55
#define IDS_CMB_CC_HiLow                56
#define IDS_CMB_CC_HiOpt1               57
#define IDS_CMB_CC_HiOpt2               58
#define IDS_CMB_CC_Zen                  59
#define IDS_CMB_CC_OmegaII              60
#define IDS_MENU_Ok                     61
#define IDS_MSG_HiEndGame               62
#define IDI_BLACKJACK                   101
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_TOOLS                       104
#define IDS_BGCOLOR_BLUE                105
#define IDS_BGCOLOR_GREEN               106
#define IDS_BGCOLOR_PURPLE              107
#define IDS_BGCOLOR_RED                 108
#define IDC_LST_PLAYSOUNDS              121
#define IDC_LST_DIFFICULTY              122
#define IDC_LST_DIFFICULTY2             123
#define IDC_LST_BACKGROUND              123
#define IDS_BTNS_DEAL                   132
#define IDS_BTNS_RESET                  133
#define IDS_BTNS_5                      134
#define IDS_BTNS_10                     135
#define IDS_BTNS_25                     136
#define IDS_BTNS_100                    137
#define IDD_DLG_Options                 138
#define IDS_WIN                         139
#define IDR_MENU_Options                140
#define IDS_BLACKJACK                   141
#define IDR_MENU_Blackjack              142
#define IDS_DRAW                        143
#define IDS_LOSE                        144
#define IDS_SURRENDER                   145
#define IDS_MENU_Menu                   146
#define IDS_MENU_Save                   147
#define IDS_MENU_Cancel                 148
#define IDR_PNG_MenuBtn                 149
#define IDR_PNG_Title                   150
#define IDR_PNG_TitleVGA                151
#define IDS_CMB_GD_Easy                 154
#define IDS_CMB_GD_Normal               155
#define IDR_PNG_MenuBtnVGA              155
#define IDS_CMB_GD_Difficult            156
#define IDS_CMB_GD_Custom               157
#define IDS_CMB_GD_Learn                158
#define IDR_PNG_DollarVGA               164
#define IDR_PNG_Dollar                  180
#define IDB_PNG_Clubs                   200
#define IDB_PNG_Diamonds                201
#define IDB_PNG_Hearts                  202
#define IDB_PNG_Spades                  203
#define IDB_PNG_CardAlpha               204
#define IDB_PNG_CardBack                205
#define IDB_PNG_Flip                    206
#define IDB_PNG_Chips                   208
#define IDB_PNG_Count                   210
#define IDB_PNG_Felt                    212
#define IDB_PNG_Logo                    215
#define IDB_PNG_Pano                    217
#define IDB_PNG_Table                   219
#define IDB_PNG_TableVGA                220
#define IDB_PNG_Dollar                  221
#define IDC_SPIN1                       305
#define IDC_SPIN2                       306
#define IDC_SPIN3                       307
#define IDC_SPIN4                       308
#define ID_SAVE                         32771
#define ID_CANCEL                       32772
#define ID_MENU                         32773
#define IDMENU_Back                     32774
#define IDMENU_Resume                   32785
#define IDMENU_HiScores                 32786
#define IDMENU_Options                  32787
#define IDMENU_Help                     32788
#define IDMENU_About                    32789
#define IDMENU_Cancel                   32790
#define IDMENU_Save                     32791
#define IDMENU_Menu                     32792
#define IDMENU_Quit                     32795
#define IDMENU_Exit                     32796
#define IDMENU_NewGame                  32797
#define IDM_HELP                        40001
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           300
#endif
#endif
