//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GuitarTunerppc.rc
//
#define IDS_APP_TITLE                   1
#define IDS_IMPLICIT_SOFTWARE           3
#define IDB_guitartuner                 4
#define IDS_WEBSITE                     5
#define IDD_DLG_Basic                   9
#define IDS_SOFTKEY_TEXT_MENU           17
#define IDS_DEMO_Over                   18
#define IDS_SOFTKEY_TEXT_SAVE           19
#define IDS_SOFTKEY_TEXT_CANCEL         20
#define IDS_VERSION                     21
#define IDS_SOUND_OFF                   25
#define IDS_SOUND_ON                    26
#define IDS_MENU_Resume                 27
#define IDS_MENU_New                    28
#define IDS_MENU_Options                29
#define IDS_MENU_Help                   30
#define IDS_MENU_LeftHanded				31
#define IDS_MENU_FretNumbers            32
#define IDS_MENU_HiScores               36
#define IDS_MENU_About                  37
#define IDS_MENU_Exit                   38
#define IDS_MENU_NewGame                39
#define IDS_MENU_Yes                    40
#define IDS_MENU_No                     41
#define IDS_MSG_Exit                    42
#define IDS_MENU_Back                   44
#define IDS_MENU_Ok                     45
#define IDS_ABOUT_1                     46
#define IDB_PNG_Wood                    50
#define IDB_PNG_Btn                     51
#define IDB_PNG_BtnVGA                  52
#define IDB_PNG_BtnGreen                53
#define IDB_PNG_BtnGreenVGA             54
#define IDB_PNG_BtnRed                  55
#define IDB_PNG_BtnRedVGA               56
#define IDB_PNG_Note                    57
#define IDB_PNG_Finger                  58
#define IDI_guitartuner                 101
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_TOOLS                       105
#define IDS_guitartuner                 141
#define IDR_MENU_GuitarTuner            142
#define IDS_MENU_Mode                   144
#define IDS_MENU_Quit                   145
#define IDS_MENU_Menu                   146
#define IDS_MENU_Save                   147
#define IDS_MENU_Cancel                 148
#define IDS_MENU_Guitar                 150
#define IDS_MENU_Banjo                  151
#define IDS_MENU_Chords                 152
#define IDS_MENU_Metronome              153
#define IDR_WAV_CLow					200
#define IDR_WAV_CsLow					201
#define IDR_WAV_DLow					202
#define IDR_WAV_DsLow					203
#define IDR_WAV_ELow					204
#define IDR_WAV_FLow					205
#define IDR_WAV_FsLow					206
#define IDR_WAV_GLow					207
#define IDR_WAV_GsLow					208
#define IDR_WAV_AMid					209
#define IDR_WAV_AsMid					210
#define IDR_WAV_BMid					211
#define IDR_WAV_CMid					212
#define IDR_WAV_CsMid					213
#define IDR_WAV_DMid					214
#define IDR_WAV_DsMid					215
#define IDR_WAV_EMid					216
#define IDR_WAV_FMid					217
#define IDR_WAV_FsMid					218
#define IDR_WAV_GMid					219
#define IDR_WAV_GsMid					220
#define IDR_WAV_AHi						221
#define IDR_WAV_AsHi					222
#define IDR_WAV_BHi						223
#define IDR_WAV_CHi						224
#define IDR_WAV_CsHi					225
#define IDR_WAV_DHi						226
#define IDR_WAV_DsHi					227
#define IDR_WAV_EHi						228
#define IDR_WAV_FHi						229
#define IDR_WAV_FsHi					230
#define IDR_WAV_GHi						231
#define IDR_WAV_GsHi					232
#define IDR_WAV_AVHi					233
#define IDR_WAV_AsVHi					234
#define IDR_WAV_BVHi					235
#define IDR_WAV_CVHi					236
#define IDR_WAV_Win                     250
#define IDC_SPIN1                       305
#define IDC_SPIN2                       306
#define IDC_SPIN3                       307
#define IDC_SPIN4                       308
#define IDMENU_Root                     32500
#define IDMENU_ChordType                32600
#define IDMENU_Tuning                   32700
#define ID_SAVE                         32771
#define ID_CANCEL                       32772
#define ID_MENU                         32773
#define IDMENU_LeftHanded				32777
#define IDMENU_FretNumbers				32778
#define IDMENU_Options                  32779
#define IDMENU_Guitar                   32780
#define IDMENU_Chords                   32781
#define IDMENU_Metronome                32782
#define IDMENU_Banjo                    32783
#define IDMENU_Resume                   32785
#define IDMENU_Help                     32788
#define IDMENU_About                    32789
#define IDMENU_Cancel                   32790
#define IDMENU_Save                     32791
#define IDMENU_Menu                     32792
#define IDMENU_Quit                     32793
#define IDMENU_Mode                     32794
#define IDMENU_Exit                     32796
#define IDM_HELP                        40001
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
