//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcPro.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalcPro.Strings.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc.
        /// </summary>
        public static string IDC_Calc {
            get {
                return ResourceManager.GetString("IDC_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panoramic Calc Pro.
        /// </summary>
        public static string IDS_APP_TITLE {
            get {
                return ResourceManager.GetString("IDS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIN.
        /// </summary>
        public static string IDS_BTN_Binary {
            get {
                return ResourceManager.GetString("IDS_BTN_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc.
        /// </summary>
        public static string IDS_BTN_Calc {
            get {
                return ResourceManager.GetString("IDS_BTN_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        public static string IDS_BTN_Conversion {
            get {
                return ResourceManager.GetString("IDS_BTN_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC.
        /// </summary>
        public static string IDS_BTN_Decimal {
            get {
                return ResourceManager.GetString("IDS_BTN_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEG.
        /// </summary>
        public static string IDS_BTN_Degrees {
            get {
                return ResourceManager.GetString("IDS_BTN_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string IDS_BTN_From {
            get {
                return ResourceManager.GetString("IDS_BTN_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAD.
        /// </summary>
        public static string IDS_BTN_Grad {
            get {
                return ResourceManager.GetString("IDS_BTN_Grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX.
        /// </summary>
        public static string IDS_BTN_Hex {
            get {
                return ResourceManager.GetString("IDS_BTN_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyp.
        /// </summary>
        public static string IDS_BTN_Hyp {
            get {
                return ResourceManager.GetString("IDS_BTN_Hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCT.
        /// </summary>
        public static string IDS_BTN_Octal {
            get {
                return ResourceManager.GetString("IDS_BTN_Octal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAD.
        /// </summary>
        public static string IDS_BTN_Radians {
            get {
                return ResourceManager.GetString("IDS_BTN_Radians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ndF.
        /// </summary>
        public static string IDS_BTN_SecondFunction {
            get {
                return ResourceManager.GetString("IDS_BTN_SecondFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string IDS_BTN_To {
            get {
                return ResourceManager.GetString("IDS_BTN_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Update .
        /// </summary>
        public static string IDS_BTN_Update {
            get {
                return ResourceManager.GetString("IDS_BTN_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determination(r²).
        /// </summary>
        public static string IDS_CALC_Determination {
            get {
                return ResourceManager.GetString("IDS_CALC_Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of X.
        /// </summary>
        public static string IDS_CALC_DevOfX {
            get {
                return ResourceManager.GetString("IDS_CALC_DevOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation of Y.
        /// </summary>
        public static string IDS_CALC_DevOfY {
            get {
                return ResourceManager.GetString("IDS_CALC_DevOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation.
        /// </summary>
        public static string IDS_CALC_Equation {
            get {
                return ResourceManager.GetString("IDS_CALC_Equation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean of X.
        /// </summary>
        public static string IDS_CALC_MeanOfX {
            get {
                return ResourceManager.GetString("IDS_CALC_MeanOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean of Y.
        /// </summary>
        public static string IDS_CALC_MeanOfY {
            get {
                return ResourceManager.GetString("IDS_CALC_MeanOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regression (r).
        /// </summary>
        public static string IDS_CALC_Regression {
            get {
                return ResourceManager.GetString("IDS_CALC_Regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope (b).
        /// </summary>
        public static string IDS_CALC_Slope {
            get {
                return ResourceManager.GetString("IDS_CALC_Slope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Intercept (a).
        /// </summary>
        public static string IDS_CALC_YIntercept {
            get {
                return ResourceManager.GetString("IDS_CALC_YIntercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string IDS_DATE_Days {
            get {
                return ResourceManager.GetString("IDS_DATE_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date/Time.
        /// </summary>
        public static string IDS_DATE_End {
            get {
                return ResourceManager.GetString("IDS_DATE_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string IDS_DATE_Hours {
            get {
                return ResourceManager.GetString("IDS_DATE_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Interval.
        /// </summary>
        public static string IDS_DATE_Interval {
            get {
                return ResourceManager.GetString("IDS_DATE_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string IDS_DATE_Min {
            get {
                return ResourceManager.GetString("IDS_DATE_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        public static string IDS_DATE_Sec {
            get {
                return ResourceManager.GetString("IDS_DATE_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date/Time.
        /// </summary>
        public static string IDS_DATE_Start {
            get {
                return ResourceManager.GetString("IDS_DATE_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc Pro.
        /// </summary>
        public static string IDS_ERROR_CalcPro {
            get {
                return ResourceManager.GetString("IDS_ERROR_CalcPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string IDS_ERROR_Error {
            get {
                return ResourceManager.GetString("IDS_ERROR_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string IDS_ERROR_FileDoesNotExist {
            get {
                return ResourceManager.GetString("IDS_ERROR_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index out of range.
        /// </summary>
        public static string IDS_ERROR_IndexRange {
            get {
                return ResourceManager.GetString("IDS_ERROR_IndexRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Unable to open file..
        /// </summary>
        public static string IDS_ERROR_OpenFile {
            get {
                return ResourceManager.GetString("IDS_ERROR_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Contact Panoramic Software Inc.
        /// </summary>
        public static string IDS_ERROR_PleaseContact {
            get {
                return ResourceManager.GetString("IDS_ERROR_PleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect.
        /// </summary>
        public static string IDS_ERROR_UnableToConnect {
            get {
                return ResourceManager.GetString("IDS_ERROR_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ask:{0:0.##}.
        /// </summary>
        public static string IDS_INFO_Ask {
            get {
                return ResourceManager.GetString("IDS_INFO_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bid:{0:0.##}.
        /// </summary>
        public static string IDS_INFO_Bid {
            get {
                return ResourceManager.GetString("IDS_INFO_Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bid:{0:0.##} \r\nask:{1:0.##}.
        /// </summary>
        public static string IDS_INFO_BidAsk {
            get {
                return ResourceManager.GetString("IDS_INFO_BidAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Amount.
        /// </summary>
        public static string IDS_INFO_BillAmount {
            get {
                return ResourceManager.GetString("IDS_INFO_BillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Total.
        /// </summary>
        public static string IDS_INFO_BillTotal {
            get {
                return ResourceManager.GetString("IDS_INFO_BillTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp./Year.
        /// </summary>
        public static string IDS_INFO_CompYear {
            get {
                return ResourceManager.GetString("IDS_INFO_CompYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string IDS_INFO_Cost {
            get {
                return ResourceManager.GetString("IDS_INFO_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo [%i Day(s)].
        /// </summary>
        public static string IDS_INFO_DemoDays {
            get {
                return ResourceManager.GetString("IDS_INFO_DemoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation.
        /// </summary>
        public static string IDS_INFO_Depreciation {
            get {
                return ResourceManager.GetString("IDS_INFO_Depreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff. 360.
        /// </summary>
        public static string IDS_INFO_Diff360 {
            get {
                return ResourceManager.GetString("IDS_INFO_Diff360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string IDS_INFO_Difference {
            get {
                return ResourceManager.GetString("IDS_INFO_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down payment.
        /// </summary>
        public static string IDS_INFO_DownPayment {
            get {
                return ResourceManager.GetString("IDS_INFO_DownPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Rate.
        /// </summary>
        public static string IDS_INFO_EffectiveRate {
            get {
                return ResourceManager.GetString("IDS_INFO_EffectiveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Day.
        /// </summary>
        public static string IDS_INFO_EndDay {
            get {
                return ResourceManager.GetString("IDS_INFO_EndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Month.
        /// </summary>
        public static string IDS_INFO_EndMonth {
            get {
                return ResourceManager.GetString("IDS_INFO_EndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Year.
        /// </summary>
        public static string IDS_INFO_EndYear {
            get {
                return ResourceManager.GetString("IDS_INFO_EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string IDS_INFO_Expired {
            get {
                return ResourceManager.GetString("IDS_INFO_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp. Regression.
        /// </summary>
        public static string IDS_INFO_ExpRegression {
            get {
                return ResourceManager.GetString("IDS_INFO_ExpRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Value.
        /// </summary>
        public static string IDS_INFO_FinalValue {
            get {
                return ResourceManager.GetString("IDS_INFO_FinalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Cost.
        /// </summary>
        public static string IDS_INFO_FixedCost {
            get {
                return ResourceManager.GetString("IDS_INFO_FixedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Value.
        /// </summary>
        public static string IDS_INFO_FutureValue {
            get {
                return ResourceManager.GetString("IDS_INFO_FutureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate.
        /// </summary>
        public static string IDS_INFO_InterestRate {
            get {
                return ResourceManager.GetString("IDS_INFO_InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest/Year.
        /// </summary>
        public static string IDS_INFO_InterestYear {
            get {
                return ResourceManager.GetString("IDS_INFO_InterestYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life.
        /// </summary>
        public static string IDS_INFO_Life {
            get {
                return ResourceManager.GetString("IDS_INFO_Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Regression.
        /// </summary>
        public static string IDS_INFO_LinearRegression {
            get {
                return ResourceManager.GetString("IDS_INFO_LinearRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Regression.
        /// </summary>
        public static string IDS_INFO_LogRegression {
            get {
                return ResourceManager.GetString("IDS_INFO_LogRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly fees.
        /// </summary>
        public static string IDS_INFO_MonthlyFees {
            get {
                return ResourceManager.GetString("IDS_INFO_MonthlyFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly payment.
        /// </summary>
        public static string IDS_INFO_MonthlyPayment {
            get {
                return ResourceManager.GetString("IDS_INFO_MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Device.
        /// </summary>
        public static string IDS_INFO_MyDevice {
            get {
                return ResourceManager.GetString("IDS_INFO_MyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string IDS_INFO_Name {
            get {
                return ResourceManager.GetString("IDS_INFO_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Rate.
        /// </summary>
        public static string IDS_INFO_NominalRate {
            get {
                return ResourceManager.GetString("IDS_INFO_NominalRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of months.
        /// </summary>
        public static string IDS_INFO_NumberOfMonths {
            get {
                return ResourceManager.GetString("IDS_INFO_NumberOfMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. People.
        /// </summary>
        public static string IDS_INFO_NumPeople {
            get {
                return ResourceManager.GetString("IDS_INFO_NumPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. Terms.
        /// </summary>
        public static string IDS_INFO_NumTerms {
            get {
                return ResourceManager.GetString("IDS_INFO_NumTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Fees.
        /// </summary>
        public static string IDS_INFO_OtherFees {
            get {
                return ResourceManager.GetString("IDS_INFO_OtherFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string IDS_INFO_Payment {
            get {
                return ResourceManager.GetString("IDS_INFO_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments/Year.
        /// </summary>
        public static string IDS_INFO_PaymentsYear {
            get {
                return ResourceManager.GetString("IDS_INFO_PaymentsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Periods.
        /// </summary>
        public static string IDS_INFO_Periods {
            get {
                return ResourceManager.GetString("IDS_INFO_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods / Year.
        /// </summary>
        public static string IDS_INFO_PeriodsYear {
            get {
                return ResourceManager.GetString("IDS_INFO_PeriodsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Regression.
        /// </summary>
        public static string IDS_INFO_PowerRegression {
            get {
                return ResourceManager.GetString("IDS_INFO_PowerRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Value.
        /// </summary>
        public static string IDS_INFO_PresentValue {
            get {
                return ResourceManager.GetString("IDS_INFO_PresentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string IDS_INFO_Price {
            get {
                return ResourceManager.GetString("IDS_INFO_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string IDS_INFO_Principal {
            get {
                return ResourceManager.GetString("IDS_INFO_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string IDS_INFO_Profit {
            get {
                return ResourceManager.GetString("IDS_INFO_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string IDS_INFO_Quantity {
            get {
                return ResourceManager.GetString("IDS_INFO_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaing book value.
        /// </summary>
        public static string IDS_INFO_RBVal {
            get {
                return ResourceManager.GetString("IDS_INFO_RBVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaing depreciable value.
        /// </summary>
        public static string IDS_INFO_RDVal {
            get {
                return ResourceManager.GetString("IDS_INFO_RDVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Version.
        /// </summary>
        public static string IDS_INFO_RetailVersion {
            get {
                return ResourceManager.GetString("IDS_INFO_RetailVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvage Value.
        /// </summary>
        public static string IDS_INFO_Salary {
            get {
                return ResourceManager.GetString("IDS_INFO_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        public static string IDS_INFO_SalesTax {
            get {
                return ResourceManager.GetString("IDS_INFO_SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Day.
        /// </summary>
        public static string IDS_INFO_StartDay {
            get {
                return ResourceManager.GetString("IDS_INFO_StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Month.
        /// </summary>
        public static string IDS_INFO_StartMonth {
            get {
                return ResourceManager.GetString("IDS_INFO_StartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value.
        /// </summary>
        public static string IDS_INFO_StartValue {
            get {
                return ResourceManager.GetString("IDS_INFO_StartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Year.
        /// </summary>
        public static string IDS_INFO_StartYear {
            get {
                return ResourceManager.GetString("IDS_INFO_StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms (years).
        /// </summary>
        public static string IDS_INFO_Terms {
            get {
                return ResourceManager.GetString("IDS_INFO_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Amount.
        /// </summary>
        public static string IDS_INFO_TipAmount {
            get {
                return ResourceManager.GetString("IDS_INFO_TipAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Percent.
        /// </summary>
        public static string IDS_INFO_TipPercent {
            get {
                return ResourceManager.GetString("IDS_INFO_TipPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total interest.
        /// </summary>
        public static string IDS_INFO_TotalInterest {
            get {
                return ResourceManager.GetString("IDS_INFO_TotalInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payments.
        /// </summary>
        public static string IDS_INFO_TotalPayments {
            get {
                return ResourceManager.GetString("IDS_INFO_TotalPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total per Per..
        /// </summary>
        public static string IDS_INFO_TotalPer {
            get {
                return ResourceManager.GetString("IDS_INFO_TotalPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total repaid.
        /// </summary>
        public static string IDS_INFO_TotalRepaid {
            get {
                return ResourceManager.GetString("IDS_INFO_TotalRepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade in.
        /// </summary>
        public static string IDS_INFO_TradeIn {
            get {
                return ResourceManager.GetString("IDS_INFO_TradeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string IDS_INFO_Type {
            get {
                return ResourceManager.GetString("IDS_INFO_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var. Cost.
        /// </summary>
        public static string IDS_INFO_VarCost {
            get {
                return ResourceManager.GetString("IDS_INFO_VarCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string IDS_INFO_Year {
            get {
                return ResourceManager.GetString("IDS_INFO_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string IDS_MENU_About {
            get {
                return ResourceManager.GetString("IDS_MENU_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string IDS_MENU_About2 {
            get {
                return ResourceManager.GetString("IDS_MENU_About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Calc Pro.
        /// </summary>
        public static string IDS_MENU_AboutCalcPro {
            get {
                return ResourceManager.GetString("IDS_MENU_AboutCalcPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string IDS_MENU_Back {
            get {
                return ResourceManager.GetString("IDS_MENU_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Conversions.
        /// </summary>
        public static string IDS_MENU_BaseConv {
            get {
                return ResourceManager.GetString("IDS_MENU_BaseConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Color.
        /// </summary>
        public static string IDS_MENU_ButtonColor {
            get {
                return ResourceManager.GetString("IDS_MENU_ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Style.
        /// </summary>
        public static string IDS_MENU_ButtonStyle {
            get {
                return ResourceManager.GetString("IDS_MENU_ButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc Pro Graph.
        /// </summary>
        public static string IDS_MENU_CalcProGraph {
            get {
                return ResourceManager.GetString("IDS_MENU_CalcProGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc Pro Options.
        /// </summary>
        public static string IDS_MENU_CalcProOptions {
            get {
                return ResourceManager.GetString("IDS_MENU_CalcProOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string IDS_MENU_Calculator {
            get {
                return ResourceManager.GetString("IDS_MENU_Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string IDS_MENU_Cancel {
            get {
                return ResourceManager.GetString("IDS_MENU_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center on Graph.
        /// </summary>
        public static string IDS_MENU_CenterGraph {
            get {
                return ResourceManager.GetString("IDS_MENU_CenterGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Constants.
        /// </summary>
        public static string IDS_MENU_ConstantFavorites {
            get {
                return ResourceManager.GetString("IDS_MENU_ConstantFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string IDS_MENU_Constants {
            get {
                return ResourceManager.GetString("IDS_MENU_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string IDS_MENU_Copy {
            get {
                return ResourceManager.GetString("IDS_MENU_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Currencies.
        /// </summary>
        public static string IDS_MENU_Currency {
            get {
                return ResourceManager.GetString("IDS_MENU_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        public static string IDS_MENU_DateTime {
            get {
                return ResourceManager.GetString("IDS_MENU_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string IDS_MENU_Down {
            get {
                return ResourceManager.GetString("IDS_MENU_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string IDS_MENU_Edit {
            get {
                return ResourceManager.GetString("IDS_MENU_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string IDS_MENU_Exit {
            get {
                return ResourceManager.GetString("IDS_MENU_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string IDS_MENU_File {
            get {
                return ResourceManager.GetString("IDS_MENU_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        public static string IDS_MENU_Financial {
            get {
                return ResourceManager.GetString("IDS_MENU_Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to data.
        /// </summary>
        public static string IDS_MENU_FitToData {
            get {
                return ResourceManager.GetString("IDS_MENU_FitToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full list.
        /// </summary>
        public static string IDS_MENU_FullList {
            get {
                return ResourceManager.GetString("IDS_MENU_FullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string IDS_MENU_General {
            get {
                return ResourceManager.GetString("IDS_MENU_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string IDS_MENU_Graph {
            get {
                return ResourceManager.GetString("IDS_MENU_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphing.
        /// </summary>
        public static string IDS_MENU_Graphing {
            get {
                return ResourceManager.GetString("IDS_MENU_Graphing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group  .
        /// </summary>
        public static string IDS_MENU_Group {
            get {
                return ResourceManager.GetString("IDS_MENU_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string IDS_MENU_Help {
            get {
                return ResourceManager.GetString("IDS_MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string IDS_MENU_Menu {
            get {
                return ResourceManager.GetString("IDS_MENU_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string IDS_MENU_Mode {
            get {
                return ResourceManager.GetString("IDS_MENU_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Apps.
        /// </summary>
        public static string IDS_MENU_MoreApps {
            get {
                return ResourceManager.GetString("IDS_MENU_MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string IDS_MENU_Off {
            get {
                return ResourceManager.GetString("IDS_MENU_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string IDS_MENU_Ok {
            get {
                return ResourceManager.GetString("IDS_MENU_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string IDS_MENU_On {
            get {
                return ResourceManager.GetString("IDS_MENU_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string IDS_MENU_Open {
            get {
                return ResourceManager.GetString("IDS_MENU_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string IDS_MENU_OpenFile {
            get {
                return ResourceManager.GetString("IDS_MENU_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string IDS_MENU_Options {
            get {
                return ResourceManager.GetString("IDS_MENU_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string IDS_MENU_Options2 {
            get {
                return ResourceManager.GetString("IDS_MENU_Options2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string IDS_MENU_Paste {
            get {
                return ResourceManager.GetString("IDS_MENU_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point on Graph.
        /// </summary>
        public static string IDS_MENU_PointOnGraph {
            get {
                return ResourceManager.GetString("IDS_MENU_PointOnGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Calc Pro.
        /// </summary>
        public static string IDS_MENU_Purchase {
            get {
                return ResourceManager.GetString("IDS_MENU_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        public static string IDS_MENU_Quiet {
            get {
                return ResourceManager.GetString("IDS_MENU_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string IDS_MENU_Range {
            get {
                return ResourceManager.GetString("IDS_MENU_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string IDS_MENU_Recent {
            get {
                return ResourceManager.GetString("IDS_MENU_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string IDS_MENU_Reset {
            get {
                return ResourceManager.GetString("IDS_MENU_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPN Stack.
        /// </summary>
        public static string IDS_MENU_RPNStack {
            get {
                return ResourceManager.GetString("IDS_MENU_RPNStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string IDS_MENU_Save {
            get {
                return ResourceManager.GetString("IDS_MENU_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string IDS_MENU_SaveFile {
            get {
                return ResourceManager.GetString("IDS_MENU_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Bitmap.
        /// </summary>
        public static string IDS_MENU_SaveGraph {
            get {
                return ResourceManager.GetString("IDS_MENU_SaveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Graph.
        /// </summary>
        public static string IDS_MENU_SelectGraph {
            get {
                return ResourceManager.GetString("IDS_MENU_SelectGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string IDS_MENU_Standard {
            get {
                return ResourceManager.GetString("IDS_MENU_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string IDS_MENU_Stats {
            get {
                return ResourceManager.GetString("IDS_MENU_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string IDS_MENU_Toggle {
            get {
                return ResourceManager.GetString("IDS_MENU_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Graph.
        /// </summary>
        public static string IDS_MENU_Translate {
            get {
                return ResourceManager.GetString("IDS_MENU_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Converter.
        /// </summary>
        public static string IDS_MENU_Unit {
            get {
                return ResourceManager.GetString("IDS_MENU_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string IDS_MENU_Up {
            get {
                return ResourceManager.GetString("IDS_MENU_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Currencies.
        /// </summary>
        public static string IDS_MENU_UpdateCurrencies {
            get {
                return ResourceManager.GetString("IDS_MENU_UpdateCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string IDS_MENU_View {
            get {
                return ResourceManager.GetString("IDS_MENU_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tape....
        /// </summary>
        public static string IDS_MENU_ViewTape {
            get {
                return ResourceManager.GetString("IDS_MENU_ViewTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and Zoom.
        /// </summary>
        public static string IDS_MENU_Zoom {
            get {
                return ResourceManager.GetString("IDS_MENU_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string IDS_MENU_ZoomIn {
            get {
                return ResourceManager.GetString("IDS_MENU_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Mode.
        /// </summary>
        public static string IDS_MENU_ZoomMode {
            get {
                return ResourceManager.GetString("IDS_MENU_ZoomMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Normal.
        /// </summary>
        public static string IDS_MENU_ZoomNormal {
            get {
                return ResourceManager.GetString("IDS_MENU_ZoomNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string IDS_MENU_ZoomOut {
            get {
                return ResourceManager.GetString("IDS_MENU_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom X.
        /// </summary>
        public static string IDS_MENU_ZoomX {
            get {
                return ResourceManager.GetString("IDS_MENU_ZoomX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Y.
        /// </summary>
        public static string IDS_MENU_ZoomY {
            get {
                return ResourceManager.GetString("IDS_MENU_ZoomY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v3.2.1\r\nCopyright 2007-2011\r\nAll rights reserved.
        /// </summary>
        public static string IDS_MSG_About {
            get {
                return ResourceManager.GetString("IDS_MSG_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc Pro Memory.
        /// </summary>
        public static string IDS_MSG_CalcProMemory {
            get {
                return ResourceManager.GetString("IDS_MSG_CalcProMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting ....
        /// </summary>
        public static string IDS_MSG_Connecting {
            get {
                return ResourceManager.GetString("IDS_MSG_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoyed using Panoramic Calc Pro, your trial has now expired.\r\n\r\nTo purchase: please return to the website that provided the trial software..
        /// </summary>
        public static string IDS_MSG_DemoOver {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoyed using Panoramic Calc Pro, your trial has now expired..
        /// </summary>
        public static string IDS_MSG_DemoOverShort {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOverShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Would you like to overwrite?.
        /// </summary>
        public static string IDS_MSG_FileExists {
            get {
                return ResourceManager.GetString("IDS_MSG_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory%i: %s\r\n.
        /// </summary>
        public static string IDS_MSG_Memory {
            get {
                return ResourceManager.GetString("IDS_MSG_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory: %s.
        /// </summary>
        public static string IDS_MSG_Memory2 {
            get {
                return ResourceManager.GetString("IDS_MSG_Memory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Expired.
        /// </summary>
        public static string IDS_MSG_TrialExpired {
            get {
                return ResourceManager.GetString("IDS_MSG_TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated: {0}.
        /// </summary>
        public static string IDS_MSG_Updated {
            get {
                return ResourceManager.GetString("IDS_MSG_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string IDS_MSG_Warning {
            get {
                return ResourceManager.GetString("IDS_MSG_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of 1 key.
        /// </summary>
        public static string IDS_OPT_1Key {
            get {
                return ResourceManager.GetString("IDS_OPT_1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers start at A.
        /// </summary>
        public static string IDS_OPT_A {
            get {
                return ResourceManager.GetString("IDS_OPT_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced memory.
        /// </summary>
        public static string IDS_OPT_AdvancedMemory {
            get {
                return ResourceManager.GetString("IDS_OPT_AdvancedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algebraic.
        /// </summary>
        public static string IDS_OPT_Algebraic {
            get {
                return ResourceManager.GetString("IDS_OPT_Algebraic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZERTY.
        /// </summary>
        public static string IDS_OPT_AZERTY {
            get {
                return ResourceManager.GetString("IDS_OPT_AZERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Monthly.
        /// </summary>
        public static string IDS_OPT_BiMonthly {
            get {
                return ResourceManager.GetString("IDS_OPT_BiMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Monthly Accel.
        /// </summary>
        public static string IDS_OPT_BiMonthlyAccel {
            get {
                return ResourceManager.GetString("IDS_OPT_BiMonthlyAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Dec.
        /// </summary>
        public static string IDS_OPT_BinaryDec {
            get {
                return ResourceManager.GetString("IDS_OPT_BinaryDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Weekly.
        /// </summary>
        public static string IDS_OPT_BiWeekly {
            get {
                return ResourceManager.GetString("IDS_OPT_BiWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Weekly Accel.
        /// </summary>
        public static string IDS_OPT_BiWeeklyAccel {
            get {
                return ResourceManager.GetString("IDS_OPT_BiWeeklyAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Steel.
        /// </summary>
        public static string IDS_OPT_BlueSteel {
            get {
                return ResourceManager.GetString("IDS_OPT_BlueSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string IDS_OPT_Brown {
            get {
                return ResourceManager.GetString("IDS_OPT_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator mode.
        /// </summary>
        public static string IDS_OPT_CalculatorMode {
            get {
                return ResourceManager.GetString("IDS_OPT_CalculatorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator size.
        /// </summary>
        public static string IDS_OPT_CalculatorSize {
            get {
                return ResourceManager.GetString("IDS_OPT_CalculatorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion buffer.
        /// </summary>
        public static string IDS_OPT_ConversionBuffer {
            get {
                return ResourceManager.GetString("IDS_OPT_ConversionBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Algebraic.
        /// </summary>
        public static string IDS_OPT_DirectAlgebraic {
            get {
                return ResourceManager.GetString("IDS_OPT_DirectAlgebraic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers start at E.
        /// </summary>
        public static string IDS_OPT_E {
            get {
                return ResourceManager.GetString("IDS_OPT_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End period payments (TVM).
        /// </summary>
        public static string IDS_OPT_EndPeriodPayments {
            get {
                return ResourceManager.GetString("IDS_OPT_EndPeriodPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENG.
        /// </summary>
        public static string IDS_OPT_ENG {
            get {
                return ResourceManager.GetString("IDS_OPT_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        public static string IDS_OPT_Engineering {
            get {
                return ResourceManager.GetString("IDS_OPT_Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string IDS_OPT_Expression {
            get {
                return ResourceManager.GetString("IDS_OPT_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast graphing.
        /// </summary>
        public static string IDS_OPT_FastGraphing {
            get {
                return ResourceManager.GetString("IDS_OPT_FastGraphing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string IDS_OPT_Fixed {
            get {
                return ResourceManager.GetString("IDS_OPT_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed digits.
        /// </summary>
        public static string IDS_OPT_FixedDigits {
            get {
                return ResourceManager.GetString("IDS_OPT_FixedDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAC.
        /// </summary>
        public static string IDS_OPT_FRAC {
            get {
                return ResourceManager.GetString("IDS_OPT_FRAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractions.
        /// </summary>
        public static string IDS_OPT_Fractions {
            get {
                return ResourceManager.GetString("IDS_OPT_Fractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use full screen.
        /// </summary>
        public static string IDS_OPT_Fullscreen {
            get {
                return ResourceManager.GetString("IDS_OPT_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glam pink.
        /// </summary>
        public static string IDS_OPT_GlamPink {
            get {
                return ResourceManager.GetString("IDS_OPT_GlamPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show keyboard letters.
        /// </summary>
        public static string IDS_OPT_KeyboardLetters {
            get {
                return ResourceManager.GetString("IDS_OPT_KeyboardLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard type.
        /// </summary>
        public static string IDS_OPT_KeyboardType {
            get {
                return ResourceManager.GetString("IDS_OPT_KeyboardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string IDS_OPT_Large {
            get {
                return ResourceManager.GetString("IDS_OPT_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large (wide).
        /// </summary>
        public static string IDS_OPT_LargeWide {
            get {
                return ResourceManager.GetString("IDS_OPT_LargeWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc Pro layout.
        /// </summary>
        public static string IDS_OPT_Layout {
            get {
                return ResourceManager.GetString("IDS_OPT_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic blue.
        /// </summary>
        public static string IDS_OPT_MetallicBlue {
            get {
                return ResourceManager.GetString("IDS_OPT_MetallicBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight black.
        /// </summary>
        public static string IDS_OPT_MidnightBlack {
            get {
                return ResourceManager.GetString("IDS_OPT_MidnightBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string IDS_OPT_Monthly {
            get {
                return ResourceManager.GetString("IDS_OPT_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Accel.
        /// </summary>
        public static string IDS_OPT_MonthlyAccel {
            get {
                return ResourceManager.GetString("IDS_OPT_MonthlyAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string IDS_OPT_Normal {
            get {
                return ResourceManager.GetString("IDS_OPT_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal (wide).
        /// </summary>
        public static string IDS_OPT_NormalWide {
            get {
                return ResourceManager.GetString("IDS_OPT_NormalWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notation.
        /// </summary>
        public static string IDS_OPT_Notation {
            get {
                return ResourceManager.GetString("IDS_OPT_Notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Sched. (Mort).
        /// </summary>
        public static string IDS_OPT_PaymentSched {
            get {
                return ResourceManager.GetString("IDS_OPT_PaymentSched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sounds.
        /// </summary>
        public static string IDS_OPT_PlaySounds {
            get {
                return ResourceManager.GetString("IDS_OPT_PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers start at Q.
        /// </summary>
        public static string IDS_OPT_Q {
            get {
                return ResourceManager.GetString("IDS_OPT_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWERTY.
        /// </summary>
        public static string IDS_OPT_QWERTY {
            get {
                return ResourceManager.GetString("IDS_OPT_QWERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWERTZ.
        /// </summary>
        public static string IDS_OPT_QWERTZ {
            get {
                return ResourceManager.GetString("IDS_OPT_QWERTZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers start at R.
        /// </summary>
        public static string IDS_OPT_R {
            get {
                return ResourceManager.GetString("IDS_OPT_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record tape.
        /// </summary>
        public static string IDS_OPT_RecordTape {
            get {
                return ResourceManager.GetString("IDS_OPT_RecordTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regional settings.
        /// </summary>
        public static string IDS_OPT_RegionalSettings {
            get {
                return ResourceManager.GetString("IDS_OPT_RegionalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.P.N..
        /// </summary>
        public static string IDS_OPT_RPN {
            get {
                return ResourceManager.GetString("IDS_OPT_RPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPN stack size.
        /// </summary>
        public static string IDS_OPT_RPNStackSize {
            get {
                return ResourceManager.GetString("IDS_OPT_RPNStackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        public static string IDS_OPT_Scientific {
            get {
                return ResourceManager.GetString("IDS_OPT_Scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi Monthly.
        /// </summary>
        public static string IDS_OPT_SemiMonthly {
            get {
                return ResourceManager.GetString("IDS_OPT_SemiMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi Monthly Accel.
        /// </summary>
        public static string IDS_OPT_SemiMonthlyAccel {
            get {
                return ResourceManager.GetString("IDS_OPT_SemiMonthlyAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show points only.
        /// </summary>
        public static string IDS_OPT_ShowPointsOnly {
            get {
                return ResourceManager.GetString("IDS_OPT_ShowPointsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string IDS_OPT_Skin {
            get {
                return ResourceManager.GetString("IDS_OPT_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string IDS_OPT_Small {
            get {
                return ResourceManager.GetString("IDS_OPT_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small (wide).
        /// </summary>
        public static string IDS_OPT_SmallWide {
            get {
                return ResourceManager.GetString("IDS_OPT_SmallWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers start at T.
        /// </summary>
        public static string IDS_OPT_T {
            get {
                return ResourceManager.GetString("IDS_OPT_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers start at W.
        /// </summary>
        public static string IDS_OPT_W {
            get {
                return ResourceManager.GetString("IDS_OPT_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string IDS_OPT_Weekly {
            get {
                return ResourceManager.GetString("IDS_OPT_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Accel.
        /// </summary>
        public static string IDS_OPT_WeeklyAccel {
            get {
                return ResourceManager.GetString("IDS_OPT_WeeklyAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless green.
        /// </summary>
        public static string IDS_OPT_WirelessGreen {
            get {
                return ResourceManager.GetString("IDS_OPT_WirelessGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers start at Z.
        /// </summary>
        public static string IDS_OPT_Z {
            get {
                return ResourceManager.GetString("IDS_OPT_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Even Sales.
        /// </summary>
        public static string IDS_TITLE_BreakEvenSales {
            get {
                return ResourceManager.GetString("IDS_TITLE_BreakEvenSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc Pro - .
        /// </summary>
        public static string IDS_TITLE_CalcPro {
            get {
                return ResourceManager.GetString("IDS_TITLE_CalcPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Interest.
        /// </summary>
        public static string IDS_TITLE_CompoundInterest {
            get {
                return ResourceManager.GetString("IDS_TITLE_CompoundInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Calculator.
        /// </summary>
        public static string IDS_TITLE_DateCalculator {
            get {
                return ResourceManager.GetString("IDS_TITLE_DateCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation.
        /// </summary>
        public static string IDS_TITLE_Depreciation {
            get {
                return ResourceManager.GetString("IDS_TITLE_Depreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Calculator.
        /// </summary>
        public static string IDS_TITLE_LoanCalculator {
            get {
                return ResourceManager.GetString("IDS_TITLE_LoanCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage - .
        /// </summary>
        public static string IDS_TITLE_Mortgage {
            get {
                return ResourceManager.GetString("IDS_TITLE_Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Change.
        /// </summary>
        public static string IDS_TITLE_PercentChange {
            get {
                return ResourceManager.GetString("IDS_TITLE_PercentChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin.
        /// </summary>
        public static string IDS_TITLE_ProfitMargin {
            get {
                return ResourceManager.GetString("IDS_TITLE_ProfitMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Calculator.
        /// </summary>
        public static string IDS_TITLE_TipCalculator {
            get {
                return ResourceManager.GetString("IDS_TITLE_TipCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Value Money.
        /// </summary>
        public static string IDS_TITLE_TVM {
            get {
                return ResourceManager.GetString("IDS_TITLE_TVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet.
        /// </summary>
        public static string IDS_TITLE_Worksheet {
            get {
                return ResourceManager.GetString("IDS_TITLE_Worksheet", resourceCulture);
            }
        }
    }
}
