//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoPokerppc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_VideoPoker                  2
#define IDS_MAIN_CLASS                  3
#define IDS_SOFTKEY_TEXT_LEFT           4
#define IDS_SOFTKEY_TEXT_RIGHT          5
#define IDS_BTN_Hold                    6
#define IDS_DEMO_Over                   7
#define IDS_RESULT_Lose                 8
#define IDS_RESULT_JOB                  9
#define IDS_RESULT_2P                   10
#define IDS_RESULT_3OK                  11
#define IDS_RESULT_4OK                  12
#define IDS_RESULT_FH                   13
#define IDS_RESULT_S                    14
#define IDS_RESULT_F                    15
#define IDS_RESULT_SF                   16
#define IDS_RESULT_RF                   17
#define IDS_RESULT_Pair                 18
#define IDS_RESULT_10s                  19
#define IDS_RESULT_Four2s4s             20
#define IDS_RESULT_Four2s4swA		    21
#define IDS_RESULT_Four5sKs             22
#define IDS_RESULT_Four2s10s            23
#define IDS_RESULT_FourJsKs             24
#define IDS_RESULT_FourAs               25
#define IDS_RESULT_FourAsw234		    26
#define IDB_PNG_BgGreen                 27
#define IDB_PNG_BgBlue                  28
#define IDB_PNG_BgRed                   29
#define IDB_PNG_BgPurple                30
#define IDB_PNG_BgOrange                31
#define IDS_GAMETYPE_10s                32
#define IDS_GAMETYPE_Aces               33
#define IDS_GAMETYPE_BonusDeluxe	    34
#define IDS_GAMETYPE_Double             35
#define IDS_GAMETYPE_DoubleDouble	    36
#define IDS_GAMETYPE_Jacks              37
#define IDS_GAMETYPE_Stud               38
#define IDS_OPTS_PS_OFF                 40
#define IDS_OPTS_PS_ON                  41
#define IDB_PNG_Title_HR                42
#define IDB_PNG_Title                   43
#define IDS_NAME_VideoPoker             45
#define IDS_BGCOLOR_BLUE                49
#define IDS_BGCOLOR_GREEN               50
#define IDS_BGCOLOR_PURPLE              51
#define IDS_BGCOLOR_RED                 52
#define IDS_BGCOLOR_ORANGE              53
#define IDB_PNG_Loader                  60
#define IDS_WEBSITE                     61
#define IDB_PNG_Loader_Inside           65
#define IDB_PNG_Grid33                  66
#define IDB_PNG_Grid50                  67
#define IDB_PNG_MenuSlice_HR            68
#define IDB_PNG_MenuSlice               69
#define IDB_PNG_Logo_HR                 70
#define IDB_PNG_Logo                    71
#define IDR_PNG_MenuBtn                 72
#define IDR_PNG_MenuBtnVGA              73
#define IDB_PNG_WinSelector_Sm          77
#define IDB_PNG_Menu			        78
#define IDB_PNG_Menu_HR                 79
#define IDB_PNG_MenuArray		        80
#define IDB_PNG_MenuArray_HR            81
#define IDB_PNG_MenuGlow		        82
#define IDB_PNG_MenuGlow_HR	            83
#define IDB_PNG_MenuSelector            84
#define IDB_PNG_MenuMid		            85
#define IDB_PNG_MenuMid_HR		        86
#define IDB_PNG_Selector                87
#define IDB_PNG_Selector_HR             88
#define IDB_PNG_CardBack_HR             89
#define IDB_PNG_CardBack                90
#define IDB_PNG_DigitalFont             91
#define IDB_PNG_DigitalFont_HR          92
#define IDB_PNG_ScoreBox                93
#define IDB_PNG_ScoreBox_HR             94
#define IDR_PNG_MenuBack                95
#define IDB_PNG_WinSelector_HR          96
#define IDB_PNG_WinSelector             97
#define IDB_PNG_WinGlow_HR              98
#define IDB_PNG_WinGlow                 99
#define IDI_VideoPoker                  100
#define IDS_OK                          101
#define IDS_HELP                        102
#define IDB_PNG_CardBack_Sm             103
#define IDS_TOOLS                       104
#define IDB_PNG_Hold_HR                 105
#define IDB_PNG_Hold                    106
#define IDS_MENU_Back                   110
#define IDS_ABOUT_1                     111
#define IDD_DLG_Basic                   129
#define IDR_MENU_Menu                   129
#define IDD_DLG_Options                 130
#define IDR_MENU_Options                131
#define IDR_MENU_VideoPoker             132
#define IDB_BMP_Clubs                   133
#define IDB_BMP_Clubs_HR                134
#define IDB_BMP_Clubs_Sm                135
#define IDB_BMP_Diamonds                136
#define IDB_BMP_Diamonds_HR             137
#define IDB_BMP_Diamonds_Sm             138
#define IDB_BMP_Hearts                  139
#define IDB_BMP_Hearts_HR               140
#define IDB_BMP_Hearts_Sm               141
#define IDB_BMP_Spades                  142
#define IDB_BMP_Spades_HR               143
#define IDB_BMP_Spades_Sm               144
#define IDC_LST_ND                      146
#define IDC_LST_BACKGROUND              147
#define IDC_LST_PS                      148
#define IDC_LST_GAMETYPE                149
#define IDC_LST_ANI			            150
#define IDS_LOSE                        151
#define IDS_LOSE_IT                     152
#define IDS_SOFTKEY_TEXT_SAVE           159
#define IDS_MENU_Save                   159
#define IDS_SOFTKEY_TEXT_CANCEL         160
#define IDB_PNG_BetX2_HR                168
#define IDB_PNG_BetX2                   169
#define IDB_PNG_BetOne_HR               170
#define IDB_PNG_BetOne                  171
#define IDB_PNG_BetMax_HR               172
#define IDB_PNG_BetMax                  173
#define IDB_PNG_Deal_HR                 174
#define IDB_PNG_Deal                    176
#define IDB_PNG_MenuBtn_HR              177
#define IDB_PNG_MenuBtn                 178
#define IDB_PNG_Game10s_HR              180
#define IDB_PNG_Game10s                 181
#define IDB_PNG_GameJacks_HR            182
#define IDB_PNG_GameJacks               183
#define IDB_PNG_GameAces_HR             184
#define IDB_PNG_GameAces                185
#define IDB_PNG_GameBonus_HR            186
#define IDB_PNG_GameBonus               187
#define IDB_PNG_GameDouble_HR           188
#define IDB_PNG_GameDouble              189
#define IDB_PNG_GameStud_HR             190
#define IDB_PNG_GameStud                191
#define IDB_PNG_MenuSep                 192
#define IDS_MENU_Cancel                 200
#define IDS_MENU_Menu                   201
#define IDS_MENU_Undo                   202
#define IDS_MENU_RestartGame            205
#define IDS_MENU_SelectGame             206
#define IDS_MENU_NewGame                207
#define IDS_MENU_Game                   208
#define IDS_MENU_Resume                 209
#define IDS_MENU_New                    210
#define IDS_MENU_Options                211
#define IDS_MENU_Help                   212
#define IDS_MENU_Quit                   213
#define IDS_MENU_Yes                    214
#define IDS_MENU_No                     215
#define IDS_MENU_Ok                     216
#define IDS_MENU_About                  217
#define IDS_MENU_Exit                   218
#define IDS_MSG_Exit                    219
#define IDS_MENU_Stats                  220
#define IDC_SPIN1                       305
#define IDC_SPIN2                       306
#define IDC_SPIN3                       307
#define IDC_SPIN4                       308
#define IDMENU_GameSelect               32762
#define IDMENU_About                    32763
#define IDMENU_Help                     32764
#define IDMENU_Exit                     32765
#define IDMENU_Resume                   32766
#define IDMENU_AutoPlay					32767
#define IDMENU_Game                     32768
#define IDMENU_NewGame                  32769
#define IDMENU_SelectGame               32770
#define IDMENU_RestartGame              32771
#define IDMENU_Stats                    32772 
#define IDMENU_Options                  32774
#define IDMENU_Undo                     32775
#define IDMENU_Cancel                   32790
#define IDMENU_Save                     32791
#define IDMENU_Menu                     32792
#define IDMENU_Quit                     32795
#define IDM_HELP                        40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
