//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CalcProsp.rc
//
#define IDS_APP_TITLE                   1
#define IDS_MAIN_CLASS                  2
#define IDS_DEMO_Over                   2
#define IDC_Calc                        3
#define IDS_MENU_Open                   105
#define IDR_MENU_SaveMenu               106
#define IDR_MENU_OpenMenu               107
#define IDS_MENU_Load                   108
#define IDS_MENU_ViewTape               109
#define IDS_NAME_Calc                   110
#define IDS_MENU_File                   111
#define IDS_MENU_Exit                   112
#define IDS_MENU_About                  113
#define IDS_MENU_Help                   114
#define IDS_MENU_Edit                   115
#define IDS_MENU_Copy                   116
#define IDS_MENU_Paste                  117
#define IDS_MENU_View                   118
#define IDS_MENU_Standard               119
#define IDS_MENU_Scientific             120
#define IDS_MENU_BaseConv               121
#define IDS_MENU_Financial              122
#define IDS_MENU_Menu                   123
#define IDS_MENU_Regional               124
#define IDR_MENU_Calculator             125
#define IDR_MENU_Options                126
#define IDS_MENU_Save                   127
#define IDS_MENU_Cancel                 128
#define IDS_MENU_Graph                  129
#define IDS_MENU_Unit                   130
#define IDS_MENU_Currency               131
#define IDS_MENU_DateTime               132
#define IDS_MENU_Translate              133
#define IDS_MENU_ZoomOut                134
#define IDS_MENU_ZoomIn                 135
#define IDS_MENU_Reset                  136
#define IDS_MENU_Mode                   137
#define IDS_MENU_PointOnGraph           138
#define IDS_MENU_CenterGraph            139
#define IDS_MENU_Zoom                   140
#define IDS_MENU_Constants              141
#define IDS_MENU_Back                   142
#define IDS_MENU_Stats                  143
#define IDI_CALCPRO                     144
#define IDR_MENU_WSheet                 145
#define IDR_MENU_Graph                  146
#define IDS_Button_SecondFunction       148
#define IDD_DLG_Child                   149
#define IDS_Button_Hyp                  150
#define IDR_GIF1                        151
#define IDS_Button_Binary               152
#define IDS_Button_Octal                153
#define IDR_WAVE1                       154
#define IDR_WAVE2                       154
#define IDS_Button_Hex                  156
#define IDS_Button_Decimal              157
#define IDS_Button_Degrees              158
#define IDS_Button_Radians              159
#define IDS_Button_Grad                 160
#define IDS_About_Long                  200
#define IDS_About_Short                 201
#define IDD_DLG_BASIC                   300
#define IDS_UNIT_Distance               400
#define IDS_UNIT_Temperature            401
#define IDS_UNIT_Speed                  402
#define IDS_UNIT_Volume                 403
#define IDS_UNIT_Mass                   404
#define IDS_UNIT_Cooking                405
#define IDS_UNIT_Computers              406
#define IDS_UNIT_Area                   407
#define IDS_UNIT_Energy                 408
#define IDS_UNIT_Power                  409
#define IDS_UNIT_Force                  410
#define IDS_UNIT_Pressure               411
#define IDS_UNIT_FuelEcon               412
#define IDS_UNIT_Time                   413
#define IDS_UNIT_Angles                 414
#define IDS_UNIT_Torque                 415
#define IDS_UNIT_Density                416
#define IDR_PNG_MenuBack                500
#define IDR_PNG_MenuSelect              501
#define IDR_PNG_MenuArray               502
#define IDR_PNG_About                   503
#define IDR_PNG_MenuBar                 504
#define IDR_PNG_Menu                    505
#define IDR_PNG_MenuBarBlue             506
#define IDR_PNG_MenuBarPink             507
#define IDR_PNG_MenuIcons               508
#define IDR_PNG_MenuIconsVGA            509
#define IDS_UL_miles                    1001
#define IDS_UL_mi                       1002
#define IDS_UL_yards                    1003
#define IDS_UL_yd                       1004
#define IDS_UL_feet                     1005
#define IDS_UL_ft                       1006
#define IDS_UL_inches                   1007
#define IDS_UL_in                       1008
#define IDS_UL_nautical_miles           1009
#define IDS_UL_nm                       1010
#define IDS_UL_kilometers               1011
#define IDS_UL_km                       1012
#define IDS_UL_meters                   1013
#define IDS_UL_m                        1014
#define IDS_UL_centimeters              1015
#define IDS_UL_cm                       1016
#define IDS_UL_millimeters              1017
#define IDS_UL_mm                       1018
#define IDS_UL_decimeters               1019
#define IDS_UL_dm                       1020
#define IDS_UL_nanometers               1021
#define IDS_UL_nanm                     1022
#define IDS_UL_leagues                  1023
#define IDS_UL_leg                      1024
#define IDS_UT_Rankine                  1038
#define IDS_UT_R                        1039
#define IDS_UT_Celcius                  1040
#define IDS_UT_C                        1041
#define IDS_UT_Fahrenheit               1042
#define IDS_UT_F                        1043
#define IDS_UT_Kelvin                   1044
#define IDS_UT_K                        1045
#define IDS_US_Miles_per_Hour           1046
#define IDS_US_mph                      1047
#define IDS_US_Kilometers_per_Hour      1048
#define IDS_US_km_h                     1049
#define IDS_US_Knots                    1050
#define IDS_US_nmph                     1051
#define IDS_US_Feet_per_Second          1052
#define IDS_US_f_s                      1053
#define IDS_US_Meters_per_Second        1054
#define IDS_US_m_s                      1055
#define IDS_US_Speed_of_Light           1056
#define IDS_US_c                        1057
#define IDS_US_Speed_of_Sound           1058
#define IDS_US_Mach                     1059
#define IDS_US_Feet_per_Minute          1060
#define IDS_US_ft_min                   1061
#define IDS_US_Meters_per_Minute        1062
#define IDS_US_m_min                    1063
#define IDS_US_Inch_per_Second          1064
#define IDS_US_in_s                     1065
#define IDS_US_Kilometes_per_Second     1066
#define IDS_US_km_s                     1067
#define IDS_UV_Gallons_liquid_US        1070
#define IDS_UV_gal_US                   1071
#define IDS_UV_Gallons_dry_US           1072
#define IDS_UV_gal_US_dry               1073
#define IDS_UV_Gallons_UK               1074
#define IDS_UV_gal_UK                   1075
#define IDS_UV_Quarts_liquid_US         1076
#define IDS_UV_qt_US                    1077
#define IDS_UV_Quarts_dry_US            1078
#define IDS_UV_qt_US_dry                1079
#define IDS_UV_Quarts_UK                1080
#define IDS_UV_qt_UK                    1081
#define IDS_UV_Pints_liquid_US          1082
#define IDS_UV_pt_US                    1083
#define IDS_UV_Pints_dry_US             1084
#define IDS_UV_pt_US_dry                1085
#define IDS_UV_Pints_UK                 1086
#define IDS_UV_pt_UK                    1087
#define IDS_UV_Cups_US                  1088
#define IDS_UV_c_US                     1089
#define IDS_UV_Cups_metric              1090
#define IDS_UV_c                        1091
#define IDS_UV_Gill_US                  1092
#define IDS_UV_gi_US                    1093
#define IDS_UV_Gill_UK                  1094
#define IDS_UV_gi_UK                    1095
#define IDS_UV_Fluid_Ounces_US          1096
#define IDS_UV_fl_oz_US                 1097
#define IDS_UV_Fluid_Ounces_UK          1098
#define IDS_UV_fl_oz_UK                 1099
#define IDS_UV_Cubic_feet               1100
#define IDS_UV_ft                       1101
#define IDS_UV_Cubic_Inches             1102
#define IDS_UV_in                       1103
#define IDS_UV_Liters                   1104
#define IDS_UV_l                        1105
#define IDS_UV_Centiliters              1106
#define IDS_UV_cl                       1107
#define IDS_UV_milliliters              1108
#define IDS_UV_ml                       1109
#define IDS_UV_Cubic_meters             1110
#define IDS_UV_m                        1111
#define IDS_UV_Cubic_centimeters        1112
#define IDS_UV_cm                       1113
#define IDS_UV_Cubic_millimeters        1114
#define IDS_UV_mm                       1115
#define IDS_UC_Pints_US                 1116
#define IDS_UC_pints_US                 1117
#define IDS_UC_Pints_UK                 1118
#define IDS_UC_pints_UK                 1119
#define IDS_UC_Gallons_liquid_US        1120
#define IDS_UC_gal_US                   1121
#define IDS_UC_Gallons_UK               1122
#define IDS_UC_gal_UK                   1123
#define IDS_UC_Quarts_liquid_US         1124
#define IDS_UC_qt_US                    1125
#define IDS_UC_Quarts_UK                1126
#define IDS_UC_qt_UK                    1127
#define IDS_UC_Cups_US                  1128
#define IDS_UC_c_US                     1129
#define IDS_UC_Cups_metric              1130
#define IDS_UC_c                        1131
#define IDS_UC_milliliters              1132
#define IDS_UC_ml                       1133
#define IDS_UC_Fluid_Ounces_US          1134
#define IDS_UC_fl_oz_US                 1135
#define IDS_UC_Fluid_Ounces_UK          1136
#define IDS_UC_fl_oz_UK                 1137
#define IDS_UC_Tablespoon               1138
#define IDS_UC_tbsp                     1139
#define IDS_UC_Teaspoon                 1140
#define IDS_UC_tsp                      1141
#define IDS_UC_Liters                   1142
#define IDS_UC_l                        1143
#define IDS_UC_bit                      1144
#define IDS_UC_byte                     1145
#define IDS_UC_kilobyte                 1146
#define IDS_UC_Kb                       1147
#define IDS_UC_megabyte                 1148
#define IDS_UC_MB                       1149
#define IDS_UC_gigabyte                 1150
#define IDS_UC_GB                       1151
#define IDS_UC_terabyte                 1152
#define IDS_UC_TB                       1153
#define IDS_UC_petabyte                 1154
#define IDS_UC_PB                       1155
#define IDS_UC_exabyte                  1156
#define IDS_UC_EB                       1157
#define IDS_UC_Word                     1158
#define IDS_UC_word                     1159
#define IDS_UC_DWord                    1160
#define IDS_UC_QWord                    1162
#define IDS_UC_disc                     1164
#define IDS_UC_35Floppy                 1165
#define IDS_UC_CD74                     1166
#define IDS_UC_CD80                     1167
#define IDS_UC_DVD                      1168
#define IDS_UA_Acres                    1170
#define IDS_UA_A                        1171
#define IDS_UA_Square_Miles             1172
#define IDS_UA_mi                       1173
#define IDS_UA_Square_Yards             1174
#define IDS_UA_yd                       1175
#define IDS_UA_Square_Feet              1176
#define IDS_UA_ft                       1177
#define IDS_UA_Square_Inches            1178
#define IDS_UA_in                       1179
#define IDS_UA_Hectares                 1180
#define IDS_UA_ha                       1181
#define IDS_UA_Square_Kilometers        1182
#define IDS_UA_km                       1183
#define IDS_UA_Square_Meters            1184
#define IDS_UA_m                        1185
#define IDS_UA_Square_Centimeters       1186
#define IDS_UA_cm                       1187
#define IDS_UA_Square_Millimeters       1188
#define IDS_UA_mm                       1189
#define IDS_UE_Joules                   1200
#define IDS_UE_J                        1201
#define IDS_UE_Calories                 1202
#define IDS_UE_cal                      1203
#define IDS_UE_Kilocalories             1204
#define IDS_UE_kcal                     1205
#define IDS_UE_Kilowatt_hours           1206
#define IDS_UE_kW_h                     1207
#define IDS_UE_Watt_hours               1208
#define IDS_UE_W_h                      1209
#define IDS_UE_Watt_seconds             1210
#define IDS_UE_W_s                      1211
#define IDS_UE_British_thermal_units    1212
#define IDS_UE_Btu                      1213
#define IDS_UE_Therms                   1214
#define IDS_UE_thm                      1215
#define IDS_UE_Foot_Pounds              1216
#define IDS_UE_Ft_lbf                   1217
#define IDS_UE_HorsePower_per_Hour      1218
#define IDS_UE_Hp_hr                    1219
#define IDS_UE_Kilogram_Meters          1220
#define IDS_UE_Kg_m                     1221
#define IDS_UE_KJoules                  1222
#define IDS_UE_kJ                       1223
#define IDS_UP_Watts                    1230
#define IDS_UP_W                        1231
#define IDS_UP_Kilowatts                1232
#define IDS_UP_kW                       1233
#define IDS_UP_MegaWatts                1234
#define IDS_UP_MW                       1235
#define IDS_UP_Gigawatts                1236
#define IDS_UP_GW                       1237
#define IDS_UP_Calories_per_hour        1238
#define IDS_UP_cal_h                    1239
#define IDS_UP_Calories_per_min         1240
#define IDS_UP_cal_min                  1241
#define IDS_UP_Calories_per_second      1242
#define IDS_UP_cal_s                    1243
#define IDS_UP_Btu_per_hour             1244
#define IDS_UP_Btu_h                    1245
#define IDS_UP_Btu_per_minute           1246
#define IDS_UP_Btu_min                  1247
#define IDS_UP_Btu_per_second           1248
#define IDS_UP_Btu_s                    1249
#define IDS_UP_Horse_Power_IT           1250
#define IDS_UP_hp_IT                    1251
#define IDS_UP_Horse_Power_metric       1252
#define IDS_UP_hp_metric                1253
#define IDS_UP_Foot_Pounds_per_sec      1254
#define IDS_UP_ft_lb_s                  1255
#define IDS_UP_Inches_Merc              1256
#define IDS_UP_Hg                       1257
#define IDS_UP_Foot_Pounds_per_min      1258
#define IDS_UP_ft_lb_min                1259
#define IDS_UM_PoundsTroy               1266
#define IDS_UM_lbTroy                   1267
#define IDS_UM_OuncesTroy               1268
#define IDS_UM_ozTroy                   1269
#define IDS_UM_Grams                    1270
#define IDS_UM_g                        1271
#define IDS_UM_Kilograms                1272
#define IDS_UM_kg                       1273
#define IDS_UM_Ounces                   1274
#define IDS_UM_oz                       1275
#define IDS_UM_Pounds                   1276
#define IDS_UM_lb                       1277
#define IDS_UM_Tonnes_metric            1278
#define IDS_UM_t                        1279
#define IDS_UM_Tons_US_short            1280
#define IDS_UM_tn                       1281
#define IDS_UM_Tons_UK_long             1282
#define IDS_UM_T                        1283
#define IDS_UM_Stones                   1284
#define IDS_UM_st                       1285
#define IDS_UM_Hunweights_US_short      1286
#define IDS_UM_Cwt_US                   1287
#define IDS_UM_Hunweights_UK_long       1288
#define IDS_UM_Cwt_UK                   1289
#define IDS_UF_gram_Force               1296
#define IDS_UF_gf                       1297
#define IDS_UF_Ounce_Force              1298
#define IDS_UF_of                       1299
#define IDS_UF_Newtons                  1300
#define IDS_UF_N                        1301
#define IDS_UF_KiloNewtons              1302
#define IDS_UF_kN                       1303
#define IDS_UF_MegaNewtons              1304
#define IDS_UF_MN                       1305
#define IDS_UF_Pound_force              1306
#define IDS_UF_lbf                      1307
#define IDS_UF_Tonnes_force_metric      1308
#define IDS_UF_tnf_metric               1309
#define IDS_UF_Tons_force_US            1310
#define IDS_UF_tnf_US                   1311
#define IDS_UF_Tons_force_UK            1312
#define IDS_UF_tnf_UK                   1313
#define IDS_UF_Kilgram_Force            1314
#define IDS_UF_kgf                      1315
#define IDS_UF_Dynes                    1316
#define IDS_UF_dynes                    1317
#define IDS_UP_Kilogram_force_per_meter 1320
#define IDS_UP_kg_m                     1321
#define IDS_UP_Kilogram_force_per_cm    1322
#define IDS_UP_kg_cm                    1323
#define IDS_UP_Kilogram_force_per_mm    1324
#define IDS_UP_kg_mm                    1325
#define IDS_UP_Tons_US_per_foot         1326
#define IDS_UP_tn_ft                    1327
#define IDS_UP_Tons_US_per_inch         1328
#define IDS_UP_tn_in                    1329
#define IDS_UP_Tons_UK_per_foot         1330
#define IDS_UP_T_ft                     1331
#define IDS_UP_Tons_UK_per_inch         1332
#define IDS_UP_T_in                     1333
#define IDS_UP_Tonnes_per_meter         1334
#define IDS_UP_t_m                      1335
#define IDS_UP_Tonnes_per_cm            1336
#define IDS_UP_t_cm                     1337
#define IDS_UP_Newtons_per_meter        1338
#define IDS_UP_N_m                      1339
#define IDS_UP_Newtons_per_cm           1340
#define IDS_UP_N_cm                     1341
#define IDS_UP_Newtons_per_mm           1342
#define IDS_UP_N_mm                     1343
#define IDS_UP_Bars                     1344
#define IDS_UP_b                        1345
#define IDS_UP_Millibars                1346
#define IDS_UP_mb                       1347
#define IDS_UP_Pascals                  1348
#define IDS_UP_Pa                       1349
#define IDS_UP_Atmospheres              1350
#define IDS_UP_atm                      1351
#define IDS_UP_Torrs                    1352
#define IDS_UP_mm_Hg_0                  1353
#define IDS_UP_Pounds_force_per_foot    1354
#define IDS_UP_lb_ft                    1355
#define IDS_UP_Pounds_force_per_inch    1356
#define IDS_UP_PSI                      1357
#define IDS_UP_Hectopascals             1358
#define IDS_UP_hPa                      1359
#define IDS_UF_Liters100km              1370
#define IDS_UF_l100km                   1371
#define IDS_UF_Miles_Gallon             1372
#define IDS_UF_milesg                   1373
#define IDS_UF_Kilmeters_Gallon         1374
#define IDS_UF_kmg                      1375
#define IDS_UF_Miles_Gallon_UK          1376
#define IDS_UF_milesg_UK                1377
#define IDS_UF_Kilimeters_Gallon_UK     1378
#define IDS_UF_kmg_UK                   1379
#define IDS_UF_Miles_Liter              1380
#define IDS_UF_milesl                   1381
#define IDS_UF_Kilmeters_Liter          1382
#define IDS_UF_kml                      1383
#define IDS_UF_Gallons_100miles         1384
#define IDS_UF_g100miles                1385
#define IDS_UF_Gallons_100km            1386
#define IDS_UF_g100km                   1387
#define IDS_UF_Gallons_100miles_UK      1388
#define IDS_UF_g100miles_UK             1389
#define IDS_UF_Gallons_100kilmeters_UK  1390
#define IDS_UF_g100km_UK                1391
#define IDS_UF_l100miles                1392
#define IDS_UF_Liters_100miles          1393
#define IDS_UT_WorkWeeks                1398
#define IDS_UT_workweeks                1399
#define IDS_UT_NanoSec                  1400
#define IDS_UT_ns                       1401
#define IDS_UT_MilliSec                 1404
#define IDS_UT_ms                       1405
#define IDS_UT_Sec                      1406
#define IDS_UT_s                        1407
#define IDS_UT_Minute                   1408
#define IDS_UT_min                      1409
#define IDS_UT_Hour                     1410
#define IDS_UT_h                        1411
#define IDS_UT_Days                     1412
#define IDS_UT_days                     1413
#define IDS_UT_Weeks                    1414
#define IDS_UT_weeks                    1415
#define IDS_UT_Months                   1416
#define IDS_UT_months                   1417
#define DS_UT_Years                     1418
#define IDS_UT_years                    1419
#define IDS_UT_Decades                  1420
#define IDS_UT_decades                  1421
#define IDS_UT_Centuries                1422
#define IDS_UT_centuries                1423
#define IDS_UT_Milleniums               1424
#define IDS_UT_milleniums               1425
#define IDS_UAN_Radians                 1450
#define IDS_UAN_rad                     1451
#define IDS_UAN_Gradians                1452
#define IDS_UAN_grad                    1453
#define IDS_UAN_Degrees                 1454
#define IDS_UAN_deg                     1455
#define IDS_UAN_Circle                  1456
#define IDS_UAN_cir                     1457
#define IDS_UAN_Point                   1458
#define IDS_UAN_pt                      1459
#define IDS_UAN_Quadrants               1460
#define IDS_UAN_quad                    1461
#define IDS_UAN_Mil                     1462
#define IDS_UAN_mill                    1463
#define IDS_UC_centiliters              1600
#define IDS_UC_cl                       1601
#define IDMENU_Back                     20185
#define IDMENU_Stats                    20186
#define IDMENU_Financial                20187
#define IDMENU_SelGraph1                20188
#define IDMENU_SelGraph2                20189
#define IDMENU_SelGraph3                20190
#define IDMENU_SelGraph4                20191
#define IDMENU_SelGraph5                20192
#define IDMENU_SelGraph6                20193
#define IDMENU_SelGraph7                20194
#define IDMENU_SelGraph8                20195
#define IDMENU_Constants                20196
#define IDMENU_DateTime                 20197
#define IDMENU_Currency                 20198
#define IDMENU_Unit                     20199
#define IDMENU_Graph                    20200
#define IDMENU_File                     20201
#define IDMENU_Menu                     20202
#define IDMENU_View                     20203
#define IDMENU_Translate                20204
#define IDMENU_ZoomOut                  20205
#define IDMENU_ZoomIn                   20206
#define IDMENU_Reset                    20207
#define IDMENU_Mode                     20208
#define IDMENU_PointOnGraph             20209
#define IDMENU_CenterGraph              20210
#define IDMENU_Exit                     20211
#define IDMENU_Zoom                     20212
#define IDMENU_ZoomNormal               20213
#define IDMENU_ZoomX                    20214
#define IDMENU_ZoomY                    20215
#define IDMENU_FitToData                20216
#define IDMENU_Open                     32762
#define IDMENU_About                    32763
#define IDMENU_Help                     32764
#define IDMENU_Edit                     32765
#define IDMENU_Copy                     32766
#define IDMENU_Paste                    32767
#define IDMENU_ViewTape                 32768
#define IDMENU_Standard                 32769
#define IDMENU_Scientific               32770
#define IDMENU_BaseConv                 32771
#define IDMENU_Regional                 32772
#define IDMENU_Options                  32773
#define IDMENU_Cancel                   32774
#define IDMENU_Save                     32775
#define ID_GRAPH_RESET                  32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
