//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Launcherppc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_Contacts                    2
#define IDS_About_Launchpad             3
#define IDS_Close                       4
#define IDS_VERSION_Launchpad           5
#define IDS_NO_Programs                 6
#define IDS_SELECT_Program              7
#define IDS_SELECT_Setting              8
#define IDS_OPEN_File                   9
#define IDS_SAVE_File                   10
#define IDS_FILE_ExistOverwrite         11
#define IDS_Name                        12
#define IDS_Type                        13
#define IDS_Warning                     14
#define IDS_MY_Device                   15
#define IDS_TRIAL_Over                  16
#define IDS_Yes                         17
#define IDS_No                          18
#define IDS_On                          19
#define IDS_Off                         20
#define IDS_Large                       21
#define IDS_Small                       22
#define IDS_Normal                      23
#define IDS_Windows                     24
#define IDS_Rocket                      25
#define IDS_Default                     26
#define IDS_COLOR_Blue                  27
#define IDS_COLOR_Green                 28
#define IDS_COLOR_Pink                  29
#define IDS_COLOR_Purple                30
#define IDS_COLOR_Orange                31
#define IDS_COLOR_Red                   32
#define IDS_SLIDER_Apps                 33
#define IDS_SLIDER_Settings             34
#define IDS_SLIDER_Utilities            35
#define IDS_SLIDER_Music                36
#define IDS_SLIDER_Folders              37
#define IDS_SLIDER_Files                38
#define IDS_SLIDER_Pictures             39
#define IDS_SLIDER_Favorites            40
#define IDS_SLIDER_Videos               41
#define IDS_CAT_General                 42
#define IDS_SoftReset                   43
#define IDS_OPTION_ShowName             44
#define IDS_OPTION_HideOnAppLaunch      45
#define IDS_OPTION_SetTodayMenu         46
#define IDS_OPTION_SetStartMenu         47
#define IDR_PNG_FolderArrowFlip         48
#define IDS_OPTION_ColorScheme          48
#define IDR_PNG_FolderArrowFlipVGA      49
#define IDS_OPTION_IconSize             49
#define IDR_PNG_FolderArrow             50
#define IDS_OPTION_LeftSliderTitle      50
#define IDR_PNG_FolderArrowVGA          51
#define IDS_OPTION_RightSliderTitle     51
#define IDR_PNG_DropBack                52
#define IDS_OPTION_StartMenu            52
#define IDR_PNG_DropBackVGA             53
#define IDS_OPTION_SeparateBySection    53
#define IDR_PNG_Shine                   54
#define IDS_MENU_AddFileFolder          54
#define IDR_PNG_ShineVGA                55
#define IDS_MENU_AddFavorite            55
#define IDR_PNG_ProgBorder              56
#define IDS_Back                        56
#define IDR_PNG_ProgBorderVGA           57
#define IDS_Connections                 57
#define IDR_PNG_DropBack128             58
#define IDS_Today                       58
#define IDR_PNG_Shine128                59
#define IDS_MENU_AddProgram             90
#define IDS_MENU_AddSetting             91
#define IDS_MENU_Quit                   100
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_MENU_Unlock                 105
#define IDS_MENU_Ok                     106
#define IDS_MENU_Cancel                 107
#define IDS_MENU_RemoveItem             109
#define IDS_MENU_DeleteContact          112
#define IDS_MENU_SmartArrange           113
#define IDS_MENU_LockItems              114
#define IDS_TOOLBAR_FAV                 115
#define IDS_TOOLBAR_CONTACTS            116
#define IDS_TOOLBAR_HISTORY             117
#define IDS_TOOLBAR_EXIT                118
#define IDS_SLIDER_Personal             119
#define IDS_SLIDER_Business             120
#define IDR_PNG_StartVGA                120
#define IDS_TOOLBAR_PROGRAMS            121
#define IDR_PNG_Start35                 121
#define IDS_TOOLBAR_SETTINGS            122
#define IDR_PNG_Start                   122
#define IDS_SLIDER_Programs             123
#define IDR_PNG_StartVGA2               123
#define IDS_SLIDER_Games                124
#define IDR_PNG_Start352                124
#define IDS_MENU_Open                   125
#define IDR_PNG_Start2                  125
#define IDS_MENU_Save                   126
#define IDR_PNG_ToolbarSelector_p       130
#define IDR_PNG_ToolbarSelector_l       131
#define IDR_PNG_ToolbarSelectorVGA_p    132
#define IDR_PNG_ToolbarSelectorVGA_l    133
#define IDR_PNG_ToolbarIconArray        134
#define IDR_PNG_ToolbarIconArrayVGA     135
#define IDR_PNG_Glow                    136
#define IDR_PNG_GlowVGA                 137
#define IDR_PNG_FavoritesArrowArray     138
#define IDR_PNG_FavoritesArrowArrayVGA  139
#define IDR_PNG_FavoritesAdd            141
#define IDR_PNG_FavoritesImgAlpha       142
#define IDR_PNG_FavoritesImgBorder      143
#define IDR_PNG_FavoritesImgBorderVGA   144
#define IDR_PNG_FavoritesImgDefault     145
#define IDR_PNG_FavoritesImgSelect      146
#define IDR_PNG_FavoritesImgShadow      147
#define IDR_PNG_FavoritesNameBbl        148
#define IDR_PNG_FavoritesGrid           149
#define IDR_PNG_FavoritesSlider         150
#define IDR_PNG_FavoritesSliderLan      151
#define IDR_PNG_DetailsBackGreenVGA     152
#define IDR_PNG_FavoritesSliderBg       153
#define IDR_PNG_FavoritesSliderBgLan    154
#define IDR_PNG_DetailsBackGreen        155
#define IDR_PNG_DetailsBtnGreen         156
#define IDR_PNG_DetailsBtn              157
#define IDR_PNG_DetailsDefault          158
#define IDR_PNG_DetailsDefaultVGA       159
#define IDR_PNG_ContactsBorder          160
#define IDR_PNG_ContactsBorderVGA       161
#define IDR_PNG_ContactsSelector        162
#define IDR_PNG_ContactsLetterBubble    170
#define IDR_PNG_Font                    173
#define IDR_PNG_FontVGA                 174
#define IDR_PNG_Group                   175
#define IDR_PNG_MenuArray               176
#define IDR_PNG_MenuArrayVGA            177
#define IDR_PNG_Selector                178
#define IDR_MENU_Unlock                 179
#define IDR_MENU_OkCancel               180
#define IDR_PNG_B_Arrow_LanVGA          180
#define IDD_DLG_Basic                   183
#define IDD_DLG_Add                     184
#define IDS_MENU_Options                191
#define IDR_PNG_B_MenuArray             192
#define IDS_MENU_Help                   193
#define IDR_PNG_B_MenuArrayVGA          193
#define IDS_MENU_About                  194
#define IDR_PNG_O_MenuArray             194
#define IDR_PNG_O_MenuArrayVGA          195
#define IDR_PNG_PI_MenuArray            196
#define IDR_PNG_PI_MenuArrayVGA         197
#define IDR_PNG_P_MenuArray             198
#define IDR_PNG_P_MenuArrayVGA          199
#define IDR_PNG_R_MenuArray             200
#define IDR_PNG_R_MenuArrayVGA          201
#define IDR_PNG_B_Selector              202
#define IDR_PNG_O_Selector              203
#define IDR_PNG_PI_Selector             204
#define IDR_PNG_P_Selector              205
#define IDR_PNG_R_Selector              206
#define IDR_PNG_B_DetailsBtnGreenVGA    207
#define IDR_PNG_B_DetailsBackGreen      208
#define IDR_PNG_B_DetailsBackGreenVGA   209
#define IDR_PNG_B_DetailsBtnGreen       210
#define IDR_PNG_O_DetailsBtnGreenVGA    211
#define IDR_PNG_O_DetailsBtnGreen       212
#define IDR_PNG_O_DetailsBackGreen      213
#define IDR_PNG_O_DetailsBackGreenVGA   214
#define IDR_PNG_PI_DetailsBackGreen     215
#define IDR_PNG_PI_DetailsBackGreenVGA  216
#define IDR_PNG_PI_DetailsBtnGreen      217
#define IDR_PNG_PI_DetailsBtnGreenVGA   218
#define IDR_PNG_P_DetailsBackGreen      219
#define IDR_PNG_P_DetailsBackGreenVGA   220
#define IDR_PNG_P_DetailsBtnGreen       221
#define IDR_PNG_P_DetailsBtnGreenVGA    222
#define IDR_PNG_R_DetailsBtnGreenVGA    223
#define IDR_PNG_R_DetailsBackGreenVGA   224
#define IDR_PNG_R_DetailsBackGreen      225
#define IDR_PNG_R_DetailsBtnGreen       226
#define IDR_PNG_DetailsBtnGreenVGA      227
#define IDR_PNG_B_FavSelectVGA          228
#define IDR_PNG_B_Glow                  229
#define IDR_PNG_B_GlowVGA               230
#define IDR_PNG_B_FavSelect             231
#define IDR_PNG_O_Glow                  232
#define IDR_PNG_O_GlowVGA               233
#define IDR_PNG_O_FavSelect             234
#define IDR_PNG_O_FavSelectVGA          235
#define IDR_PNG_PI_Glow                 238
#define IDR_PNG_PI_GlowVGA              239
#define IDR_PNG_PI_FavSelect            240
#define IDR_PNG_PI_FavSelectVGA         241
#define IDR_PNG_P_Glow                  242
#define IDR_PNG_P_GlowVGA               243
#define IDR_PNG_P_FavSelect             244
#define IDR_PNG_P_FavSelectVGA          245
#define IDR_PNG_R_Glow                  246
#define IDR_PNG_R_GlowVGA               247
#define IDR_PNG_R_FavSelect             248
#define IDR_PNG_R_FavSelectVGA          249
#define IDR_PNG_B_Arrow                 250
#define IDR_PNG_B_Arrow_Lan             251
#define IDR_PNG_B_ArrowVGA              252
#define IDR_PNG_Arrow_LanVGA            254
#define IDR_PNG_Arrow                   255
#define IDR_PNG_Arrow_Lan               256
#define IDR_PNG_ArrowVGA                257
#define IDR_PNG_O_Arrow_LanVGA          258
#define IDR_PNG_O_Arrow                 259
#define IDR_PNG_O_Arrow_Lan             260
#define IDR_PNG_O_ArrowVGA              261
#define IDR_PNG_PI_ArrowVGA             262
#define IDR_PNG_PI_Arrow_LanVGA         263
#define IDR_PNG_PI_Arrow                264
#define IDR_PNG_PI_Arrow_Lan            265
#define IDR_PNG_P_Arrow_LanVGA          266
#define IDR_PNG_P_Arrow                 267
#define IDR_PNG_P_Arrow_Lan             268
#define IDR_PNG_P_ArrowVGA              269
#define IDR_PNG_R_ArrowVGA              270
#define IDR_PNG_R_Arrow_LanVGA          271
#define IDR_PNG_R_Arrow                 272
#define IDR_PNG_R_Arrow_Lan             273
#define IDR_PNG_DetailsBtnVGA           274
#define IDR_PNG_CallBg                  275
#define IDR_PNG_CallBgVGA               276
#define IDI_Launcher                    277
#define IDR_MENU_OpenMenu               278
#define IDR_MENU_SaveMenu               279
#define IDR_PNG_Today                   280
#define IDR_PNG_TodayVGA                281
#define IDD_DIALOG1                     282
#define IDD_DLG_Blank                   282
#define IDR_PNG_FavoritesGridVGA        300
#define IDR_PNG_FavoritesSliderVGA      301
#define IDR_PNG_FavoritesSliderLanVGA   302
#define IDR_PNG_FavoritesSliderBgVGA    303
#define IDR_PNG_FavoritesSliderBgLanVGA 304
#define IDR_PNG_FavoritesNameBblVGA     305
#define IDR_PNG_FavoritesImgSelectVGA   306
#define IDR_PNG_FavoritesAddVGA         307
#define IDR_PNG_FavoritesImgAlphaVGA    308
#define IDR_PNG_FavoritesImgDefaultVGA  309
#define IDR_PNG_FavoritesImgShadowVGA   310
#define IDR_PNG_HistoryArray            311
#define IDR_PNG_HistoryArrayVGA         312
#define IDS_About_Launchpad_DE          7003
#define IDS_Close_DE                    7004
#define IDS_VERSION_Launchpad_DE        7005
#define IDS_NO_Programs_DE              7006
#define IDS_SELECT_Program_DE           7007
#define IDS_SELECT_Setting_DE           7008
#define IDS_OPEN_File_DE                7009
#define IDS_SAVE_File_DE                7010
#define IDS_FILE_ExistOverwrite_DE      7011
#define IDS_Name_DE                     7012
#define IDS_Type_DE                     7013
#define IDS_Warning_DE                  7014
#define IDS_MY_Device_DE                7015
#define IDS_TRIAL_Over_DE               7016
#define IDS_Yes_DE                      7017
#define IDS_No_DE                       7018
#define IDS_On_DE                       7019
#define IDS_Off_DE                      7020
#define IDS_Large_DE                    7021
#define IDS_Small_DE                    7022
#define IDS_Normal_DE                   7023
#define IDS_Windows_DE                  7024
#define IDS_Rocket_DE                   7025
#define IDS_Default_DE                  7026
#define IDS_COLOR_Blue_DE               7027
#define IDS_COLOR_Green_DE              7028
#define IDS_COLOR_Pink_DE               7029
#define IDS_COLOR_Purple_DE             7030
#define IDS_COLOR_Orange_DE             7031
#define IDS_COLOR_Red_DE                7032
#define IDS_SLIDER_Apps_DE              7033
#define IDS_SLIDER_Settings_DE          7034
#define IDS_SLIDER_Utilities_DE         7035
#define IDS_SLIDER_Music_DE             7036
#define IDS_SLIDER_Folders_DE           7037
#define IDS_SLIDER_Files_DE             7038
#define IDS_SLIDER_Pictures_DE          7039
#define IDS_SLIDER_Favorites_DE         7040
#define IDS_SLIDER_Videos_DE            7041
#define IDS_CAT_General_DE              7042
#define IDS_SoftReset_DE                7043
#define IDS_OPTION_ShowName_DE          7044
#define IDS_OPTION_HideOnAppLaunch_DE   7045
#define IDS_OPTION_SetTodayMenu_DE      7046
#define IDS_OPTION_SetStartMenu_DE      7047
#define IDS_OPTION_ColorScheme_DE       7048
#define IDS_OPTION_IconSize_DE          7049
#define IDS_OPTION_LeftSliderTitle_DE   7050
#define IDS_OPTION_RightSliderTitle_DE  7051
#define IDS_OPTION_StartMenu_DE         7052
#define IDS_OPTION_SeparateBySection_DE 7053
#define IDS_MENU_AddFileFolder_DE       7054
#define IDS_MENU_AddFavorite_DE         7055
#define IDS_Back_DE                     7056
#define IDS_Connections_DE              7057
#define IDS_Today_DE                    7058
#define IDS_MENU_AddProgram_DE          7090
#define IDS_MENU_AddSetting_DE          7091
#define IDS_MENU_Quit_DE                7100
#define IDS_OK_DE                       7103
#define IDS_HELP_DE                     7104
#define IDS_MENU_Unlock_DE              7105
#define IDS_MENU_Ok_DE                  7106
#define IDS_MENU_Cancel_DE              7107
#define IDS_MENU_RemoveItem_DE          7109
#define IDS_MENU_DeleteContact_DE       7112
#define IDS_MENU_SmartArrange_DE        7113
#define IDS_MENU_LockItems_DE           7114
#define IDS_TOOLBAR_FAV_DE              7115
#define IDS_TOOLBAR_CONTACTS_DE         7116
#define IDS_TOOLBAR_HISTORY_DE          7117
#define IDS_TOOLBAR_EXIT_DE             7118
#define IDS_SLIDER_Personal_DE          7119
#define IDS_SLIDER_Business_DE          7120
#define IDS_TOOLBAR_PROGRAMS_DE         7121
#define IDS_TOOLBAR_SETTINGS_DE         7122
#define IDS_SLIDER_Programs_DE          7123
#define IDS_SLIDER_Games_DE             7124
#define IDS_MENU_Open_DE                7125
#define IDS_MENU_Save_DE                7126
#define IDS_MENU_Options_DE             7191
#define IDS_MENU_Help_DE                7193
#define IDS_MENU_About_DE               7194
#define IDS_About_Launchpad_ES          10003
#define IDS_Close_ES                    10004
#define IDS_VERSION_Launchpad_ES        10005
#define IDS_NO_Programs_ES              10006
#define IDS_SELECT_Program_ES           10007
#define IDS_SELECT_Setting_ES           10008
#define IDS_OPEN_File_ES                10009
#define IDS_SAVE_File_ES                10010
#define IDS_FILE_ExistOverwrite_ES      10011
#define IDS_Name_ES                     10012
#define IDS_Type_ES                     10013
#define IDS_Warning_ES                  10014
#define IDS_MY_Device_ES                10015
#define IDS_TRIAL_Over_ES               10016
#define IDS_Yes_ES                      10017
#define IDS_No_ES                       10018
#define IDS_On_ES                       10019
#define IDS_Off_ES                      10020
#define IDS_Large_ES                    10021
#define IDS_Small_ES                    10022
#define IDS_Normal_ES                   10023
#define IDS_Windows_ES                  10024
#define IDS_Rocket_ES                   10025
#define IDS_Default_ES                  10026
#define IDS_COLOR_Blue_ES               10027
#define IDS_COLOR_Green_ES              10028
#define IDS_COLOR_Pink_ES               10029
#define IDS_COLOR_Purple_ES             10030
#define IDS_COLOR_Orange_ES             10031
#define IDS_COLOR_Red_ES                10032
#define IDS_SLIDER_Apps_ES              10033
#define IDS_SLIDER_Settings_ES          10034
#define IDS_SLIDER_Utilities_ES         10035
#define IDS_SLIDER_Music_ES             10036
#define IDS_SLIDER_Folders_ES           10037
#define IDS_SLIDER_Files_ES             10038
#define IDS_SLIDER_Pictures_ES          10039
#define IDS_SLIDER_Favorites_ES         10040
#define IDS_SLIDER_Videos_ES            10041
#define IDS_CAT_General_ES              10042
#define IDS_SoftReset_ES                10043
#define IDS_OPTION_ShowName_ES          10044
#define IDS_OPTION_HideOnAppLaunch_ES   10045
#define IDS_OPTION_SetTodayMenu_ES      10046
#define IDS_OPTION_SetStartMenu_ES      10047
#define IDS_OPTION_ColorScheme_ES       10048
#define IDS_OPTION_IconSize_ES          10049
#define IDS_OPTION_LeftSliderTitle_ES   10050
#define IDS_OPTION_RightSliderTitle_ES  10051
#define IDS_OPTION_StartMenu_ES         10052
#define IDS_OPTION_SeparateBySection_ES 10053
#define IDS_MENU_AddFileFolder_ES       10054
#define IDS_MENU_AddFavorite_ES         10055
#define IDS_Back_ES                     10056
#define IDS_Connections_ES              10057
#define IDS_Today_ES                    10058
#define IDS_MENU_AddProgram_ES          10090
#define IDS_MENU_AddSetting_ES          10091
#define IDS_MENU_Quit_ES                10100
#define IDS_OK_ES                       10103
#define IDS_HELP_ES                     10104
#define IDS_MENU_Unlock_ES              10105
#define IDS_MENU_Ok_ES                  10106
#define IDS_MENU_Cancel_ES              10107
#define IDS_MENU_RemoveItem_ES          10109
#define IDS_MENU_DeleteContact_ES       10112
#define IDS_MENU_SmartArrange_ES        10113
#define IDS_MENU_LockItems_ES           10114
#define IDS_TOOLBAR_FAV_ES              10115
#define IDS_TOOLBAR_CONTACTS_ES         10116
#define IDS_TOOLBAR_HISTORY_ES          10117
#define IDS_TOOLBAR_EXIT_ES             10118
#define IDS_SLIDER_Personal_ES          10119
#define IDS_SLIDER_Business_ES          10120
#define IDS_TOOLBAR_PROGRAMS_ES         10121
#define IDS_TOOLBAR_SETTINGS_ES         10122
#define IDS_SLIDER_Programs_ES          10123
#define IDS_SLIDER_Games_ES             10124
#define IDS_MENU_Open_ES                10125
#define IDS_MENU_Save_ES                10126
#define IDS_MENU_Options_ES             10191
#define IDS_MENU_Help_ES                10193
#define IDS_MENU_About_ES               10194
#define IDS_About_Launchpad_FR          12003
#define IDS_Close_FR                    12004
#define IDS_VERSION_Launchpad_FR        12005
#define IDS_NO_Programs_FR              12006
#define IDS_SELECT_Program_FR           12007
#define IDS_SELECT_Setting_FR           12008
#define IDS_OPEN_File_FR                12009
#define IDS_SAVE_File_FR                12010
#define IDS_FILE_ExistOverwrite_FR      12011
#define IDS_Name_FR                     12012
#define IDS_Type_FR                     12013
#define IDS_Warning_FR                  12014
#define IDS_MY_Device_FR                12015
#define IDS_TRIAL_Over_FR               12016
#define IDS_Yes_FR                      12017
#define IDS_No_FR                       12018
#define IDS_On_FR                       12019
#define IDS_Off_FR                      12020
#define IDS_Large_FR                    12021
#define IDS_Small_FR                    12022
#define IDS_Normal_FR                   12023
#define IDS_Windows_FR                  12024
#define IDS_Rocket_FR                   12025
#define IDS_Default_FR                  12026
#define IDS_COLOR_Blue_FR               12027
#define IDS_COLOR_Green_FR              12028
#define IDS_COLOR_Pink_FR               12029
#define IDS_COLOR_Purple_FR             12030
#define IDS_COLOR_Orange_FR             12031
#define IDS_COLOR_Red_FR                12032
#define IDS_SLIDER_Apps_FR              12033
#define IDS_SLIDER_Settings_FR          12034
#define IDS_SLIDER_Utilities_FR         12035
#define IDS_SLIDER_Music_FR             12036
#define IDS_SLIDER_Folders_FR           12037
#define IDS_SLIDER_Files_FR             12038
#define IDS_SLIDER_Pictures_FR          12039
#define IDS_SLIDER_Favorites_FR         12040
#define IDS_SLIDER_Videos_FR            12041
#define IDS_CAT_General_FR              12042
#define IDS_SoftReset_FR                12043
#define IDS_OPTION_ShowName_FR          12044
#define IDS_OPTION_HideOnAppLaunch_FR   12045
#define IDS_OPTION_SetTodayMenu_FR      12046
#define IDS_OPTION_SetStartMenu_FR      12047
#define IDS_OPTION_ColorScheme_FR       12048
#define IDS_OPTION_IconSize_FR          12049
#define IDS_OPTION_LeftSliderTitle_FR   12050
#define IDS_OPTION_RightSliderTitle_FR  12051
#define IDS_OPTION_StartMenu_FR         12052
#define IDS_OPTION_SeparateBySection_FR 12053
#define IDS_MENU_AddFileFolder_FR       12054
#define IDS_MENU_AddFavorite_FR         12055
#define IDS_Back_FR                     12056
#define IDS_Connections_FR              12057
#define IDS_Today_FR                    12058
#define IDS_MENU_AddProgram_FR          12090
#define IDS_MENU_AddSetting_FR          12091
#define IDS_MENU_Quit_FR                12100
#define IDS_OK_FR                       12103
#define IDS_HELP_FR                     12104
#define IDS_MENU_Unlock_FR              12105
#define IDS_MENU_Ok_FR                  12106
#define IDS_MENU_Cancel_FR              12107
#define IDS_MENU_RemoveItem_FR          12109
#define IDS_MENU_DeleteContact_FR       12112
#define IDS_MENU_SmartArrange_FR        12113
#define IDS_MENU_LockItems_FR           12114
#define IDS_TOOLBAR_FAV_FR              12115
#define IDS_TOOLBAR_CONTACTS_FR         12116
#define IDS_TOOLBAR_HISTORY_FR          12117
#define IDS_TOOLBAR_EXIT_FR             12118
#define IDS_SLIDER_Personal_FR          12119
#define IDS_SLIDER_Business_FR          12120
#define IDS_TOOLBAR_PROGRAMS_FR         12121
#define IDS_TOOLBAR_SETTINGS_FR         12122
#define IDS_SLIDER_Programs_FR          12123
#define IDS_SLIDER_Games_FR             12124
#define IDS_MENU_Open_FR                12125
#define IDS_MENU_Save_FR                12126
#define IDS_MENU_Options_FR             12191
#define IDS_MENU_Help_FR                12193
#define IDS_MENU_About_FR               12194
#define IDS_About_Launchpad_IT          16003
#define IDS_Close_IT                    16004
#define IDS_VERSION_Launchpad_IT        16005
#define IDS_NO_Programs_IT              16006
#define IDS_SELECT_Program_IT           16007
#define IDS_SELECT_Setting_IT           16008
#define IDS_OPEN_File_IT                16009
#define IDS_SAVE_File_IT                16010
#define IDS_FILE_ExistOverwrite_IT      16011
#define IDS_Name_IT                     16012
#define IDS_Type_IT                     16013
#define IDS_Warning_IT                  16014
#define IDS_MY_Device_IT                16015
#define IDS_TRIAL_Over_IT               16016
#define IDS_Yes_IT                      16017
#define IDS_No_IT                       16018
#define IDS_On_IT                       16019
#define IDS_Off_IT                      16020
#define IDS_Large_IT                    16021
#define IDS_Small_IT                    16022
#define IDS_Normal_IT                   16023
#define IDS_Windows_IT                  16024
#define IDS_Rocket_IT                   16025
#define IDS_Default_IT                  16026
#define IDS_COLOR_Blue_IT               16027
#define IDS_COLOR_Green_IT              16028
#define IDS_COLOR_Pink_IT               16029
#define IDS_COLOR_Purple_IT             16030
#define IDS_COLOR_Orange_IT             16031
#define IDS_COLOR_Red_IT                16032
#define IDS_SLIDER_Apps_IT              16033
#define IDS_SLIDER_Settings_IT          16034
#define IDS_SLIDER_Utilities_IT         16035
#define IDS_SLIDER_Music_IT             16036
#define IDS_SLIDER_Folders_IT           16037
#define IDS_SLIDER_Files_IT             16038
#define IDS_SLIDER_Pictures_IT          16039
#define IDS_SLIDER_Favorites_IT         16040
#define IDS_SLIDER_Videos_IT            16041
#define IDS_CAT_General_IT              16042
#define IDS_SoftReset_IT                16043
#define IDS_OPTION_ShowName_IT          16044
#define IDS_OPTION_HideOnAppLaunch_IT   16045
#define IDS_OPTION_SetTodayMenu_IT      16046
#define IDS_OPTION_SetStartMenu_IT      16047
#define IDS_OPTION_ColorScheme_IT       16048
#define IDS_OPTION_IconSize_IT          16049
#define IDS_OPTION_LeftSliderTitle_IT   16050
#define IDS_OPTION_RightSliderTitle_IT  16051
#define IDS_OPTION_StartMenu_IT         16052
#define IDS_OPTION_SeparateBySection_IT 16053
#define IDS_MENU_AddFileFolder_IT       16054
#define IDS_MENU_AddFavorite_IT         16055
#define IDS_Back_IT                     16056
#define IDS_Connections_IT              16057
#define IDS_Today_IT                    16058
#define IDS_MENU_AddProgram_IT          16090
#define IDS_MENU_AddSetting_IT          16091
#define IDS_MENU_Quit_IT                16100
#define IDS_OK_IT                       16103
#define IDS_HELP_IT                     16104
#define IDS_MENU_Unlock_IT              16105
#define IDS_MENU_Ok_IT                  16106
#define IDS_MENU_Cancel_IT              16107
#define IDS_MENU_RemoveItem_IT          16109
#define IDS_MENU_DeleteContact_IT       16112
#define IDS_MENU_SmartArrange_IT        16113
#define IDS_MENU_LockItems_IT           16114
#define IDS_TOOLBAR_FAV_IT              16115
#define IDS_TOOLBAR_CONTACTS_IT         16116
#define IDS_TOOLBAR_HISTORY_IT          16117
#define IDS_TOOLBAR_EXIT_IT             16118
#define IDS_SLIDER_Personal_IT          16119
#define IDS_SLIDER_Business_IT          16120
#define IDS_TOOLBAR_PROGRAMS_IT         16121
#define IDS_TOOLBAR_SETTINGS_IT         16122
#define IDS_SLIDER_Programs_IT          16123
#define IDS_SLIDER_Games_IT             16124
#define IDS_MENU_Open_IT                16125
#define IDS_MENU_Save_IT                16126
#define IDS_MENU_Options_IT             16191
#define IDS_MENU_Help_IT                16193
#define IDS_MENU_About_IT               16194
#define IDS_About_Launchpad_DU          19003
#define IDS_Close_DU                    19004
#define IDS_VERSION_Launchpad_DU        19005
#define IDS_NO_Programs_DU              19006
#define IDS_SELECT_Program_DU           19007
#define IDS_SELECT_Setting_DU           19008
#define IDS_OPEN_File_DU                19009
#define IDS_SAVE_File_DU                19010
#define IDS_FILE_ExistOverwrite_DU      19011
#define IDS_Name_DU                     19012
#define IDS_Type_DU                     19013
#define IDS_Warning_DU                  19014
#define IDS_MY_Device_DU                19015
#define IDS_TRIAL_Over_DU               19016
#define IDS_Yes_DU                      19017
#define IDS_No_DU                       19018
#define IDS_On_DU                       19019
#define IDS_Off_DU                      19020
#define IDS_Large_DU                    19021
#define IDS_Small_DU                    19022
#define IDS_Normal_DU                   19023
#define IDS_Windows_DU                  19024
#define IDS_Rocket_DU                   19025
#define IDS_Default_DU                  19026
#define IDS_COLOR_Blue_DU               19027
#define IDS_COLOR_Green_DU              19028
#define IDS_COLOR_Pink_DU               19029
#define IDS_COLOR_Purple_DU             19030
#define IDS_COLOR_Orange_DU             19031
#define IDS_COLOR_Red_DU                19032
#define IDS_SLIDER_Apps_DU              19033
#define IDS_SLIDER_Settings_DU          19034
#define IDS_SLIDER_Utilities_DU         19035
#define IDS_SLIDER_Music_DU             19036
#define IDS_SLIDER_Folders_DU           19037
#define IDS_SLIDER_Files_DU             19038
#define IDS_SLIDER_Pictures_DU          19039
#define IDS_SLIDER_Favorites_DU         19040
#define IDS_SLIDER_Videos_DU            19041
#define IDS_CAT_General_DU              19042
#define IDS_SoftReset_DU                19043
#define IDS_OPTION_ShowName_DU          19044
#define IDS_OPTION_HideOnAppLaunch_DU   19045
#define IDS_OPTION_SetTodayMenu_DU      19046
#define IDS_OPTION_SetStartMenu_DU      19047
#define IDS_OPTION_ColorScheme_DU       19048
#define IDS_OPTION_IconSize_DU          19049
#define IDS_OPTION_LeftSliderTitle_DU   19050
#define IDS_OPTION_RightSliderTitle_DU  19051
#define IDS_OPTION_StartMenu_DU         19052
#define IDS_OPTION_SeparateBySection_DU 19053
#define IDS_MENU_AddFileFolder_DU       19054
#define IDS_MENU_AddFavorite_DU         19055
#define IDS_Back_DU                     19056
#define IDS_Connections_DU              19057
#define IDS_Today_DU                    19058
#define IDS_MENU_AddProgram_DU          19090
#define IDS_MENU_AddSetting_DU          19091
#define IDS_MENU_Quit_DU                19100
#define IDS_OK_DU                       19103
#define IDS_HELP_DU                     19104
#define IDS_MENU_Unlock_DU              19105
#define IDS_MENU_Ok_DU                  19106
#define IDS_MENU_Cancel_DU              19107
#define IDS_MENU_RemoveItem_DU          19109
#define IDS_MENU_DeleteContact_DU       19112
#define IDS_MENU_SmartArrange_DU        19113
#define IDS_MENU_LockItems_DU           19114
#define IDS_TOOLBAR_FAV_DU              19115
#define IDS_TOOLBAR_CONTACTS_DU         19116
#define IDS_TOOLBAR_HISTORY_DU          19117
#define IDS_TOOLBAR_EXIT_DU             19118
#define IDS_SLIDER_Personal_DU          19119
#define IDS_SLIDER_Business_DU          19120
#define IDS_TOOLBAR_PROGRAMS_DU         19121
#define IDS_TOOLBAR_SETTINGS_DU         19122
#define IDS_SLIDER_Programs_DU          19123
#define IDS_SLIDER_Games_DU             19124
#define IDS_MENU_Open_DU                19125
#define IDS_MENU_Save_DU                19126
#define IDS_MENU_Options_DU             19191
#define IDS_MENU_Help_DU                19193
#define IDS_MENU_About_DU               19194
#define IDS_About_Launchpad_PT          22003
#define IDS_Close_PT                    22004
#define IDS_VERSION_Launchpad_PT        22005
#define IDS_NO_Programs_PT              22006
#define IDS_SELECT_Program_PT           22007
#define IDS_SELECT_Setting_PT           22008
#define IDS_OPEN_File_PT                22009
#define IDS_SAVE_File_PT                22010
#define IDS_FILE_ExistOverwrite_PT      22011
#define IDS_Name_PT                     22012
#define IDS_Type_PT                     22013
#define IDS_Warning_PT                  22014
#define IDS_MY_Device_PT                22015
#define IDS_TRIAL_Over_PT               22016
#define IDS_Yes_PT                      22017
#define IDS_No_PT                       22018
#define IDS_On_PT                       22019
#define IDS_Off_PT                      22020
#define IDS_Large_PT                    22021
#define IDS_Small_PT                    22022
#define IDS_Normal_PT                   22023
#define IDS_Windows_PT                  22024
#define IDS_Rocket_PT                   22025
#define IDS_Default_PT                  22026
#define IDS_COLOR_Blue_PT               22027
#define IDS_COLOR_Green_PT              22028
#define IDS_COLOR_Pink_PT               22029
#define IDS_COLOR_Purple_PT             22030
#define IDS_COLOR_Orange_PT             22031
#define IDS_COLOR_Red_PT                22032
#define IDS_SLIDER_Apps_PT              22033
#define IDS_SLIDER_Settings_PT          22034
#define IDS_SLIDER_Utilities_PT         22035
#define IDS_SLIDER_Music_PT             22036
#define IDS_SLIDER_Folders_PT           22037
#define IDS_SLIDER_Files_PT             22038
#define IDS_SLIDER_Pictures_PT          22039
#define IDS_SLIDER_Favorites_PT         22040
#define IDS_SLIDER_Videos_PT            22041
#define IDS_CAT_General_PT              22042
#define IDS_SoftReset_PT                22043
#define IDS_OPTION_ShowName_PT          22044
#define IDS_OPTION_HideOnAppLaunch_PT   22045
#define IDS_OPTION_SetTodayMenu_PT      22046
#define IDS_OPTION_SetStartMenu_PT      22047
#define IDS_OPTION_ColorScheme_PT       22048
#define IDS_OPTION_IconSize_PT          22049
#define IDS_OPTION_LeftSliderTitle_PT   22050
#define IDS_OPTION_RightSliderTitle_PT  22051
#define IDS_OPTION_StartMenu_PT         22052
#define IDS_OPTION_SeparateBySection_PT 22053
#define IDS_MENU_AddFileFolder_PT       22054
#define IDS_MENU_AddFavorite_PT         22055
#define IDS_Back_PT                     22056
#define IDS_Connections_PT              22057
#define IDS_Today_PT                    22058
#define IDS_MENU_AddProgram_PT          22090
#define IDS_MENU_AddSetting_PT          22091
#define IDS_MENU_Quit_PT                22100
#define IDS_OK_PT                       22103
#define IDS_HELP_PT                     22104
#define IDS_MENU_Unlock_PT              22105
#define IDS_MENU_Ok_PT                  22106
#define IDS_MENU_Cancel_PT              22107
#define IDS_MENU_RemoveItem_PT          22109
#define IDS_MENU_DeleteContact_PT       22112
#define IDS_MENU_SmartArrange_PT        22113
#define IDS_MENU_LockItems_PT           22114
#define IDS_TOOLBAR_FAV_PT              22115
#define IDS_TOOLBAR_CONTACTS_PT         22116
#define IDS_TOOLBAR_HISTORY_PT          22117
#define IDS_TOOLBAR_EXIT_PT             22118
#define IDS_SLIDER_Personal_PT          22119
#define IDS_SLIDER_Business_PT          22120
#define IDS_TOOLBAR_PROGRAMS_PT         22121
#define IDS_TOOLBAR_SETTINGS_PT         22122
#define IDS_SLIDER_Programs_PT          22123
#define IDS_SLIDER_Games_PT             22124
#define IDS_MENU_Open_PT                22125
#define IDS_MENU_Save_PT                22126
#define IDS_MENU_Options_PT             22191
#define IDS_MENU_Help_PT                22193
#define IDS_MENU_About_PT               22194
#define IDMENU_Quit                     32760
#define IDMENU_AddProgram               32761
#define IDMENU_AddSetting               32762
#define IDMENU_SmartArrange             32763
#define IDMENU_LockItems                32764
#define IDMENU_AddItem                  32765
#define IDMENU_RemoveItem               32766
#define IDMENU_NewContact               32767
#define IDMENU_CallHome                 32768
#define IDMENU_CallMobile               32769
#define IDMENU_CallWork                 32770
#define IDMENU_SetContactPicture        32771
#define IDMENU_Unlock                   32772
#define IDMENU_SetContactCamera         32773
#define IDMENU_Cancel                   32774
#define IDMENU_Ok                       32776
#define IDMENU_Conversation             32777
#define IDMENU_Options                  32778
#define IDMENU_Open                     32778
#define IDMENU_Help                     32779
#define IDMENU_EditContact              32780
#define IDMENU_DeleteContact            32781
#define IDMENU_Save                     32781
#define IDMENU_About                    32782
#define IDMENU_MarkAllAsRead            32783
#define IDMENU_AddFileFolder            32784
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        283
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
