//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TodayRls.rc
//
#define IDS_APP_TITLE                   1
#define IDC_Today                       2
#define IDS_MENU_EditContact            3
#define IDS_MENU_Conversation           4
#define IDS_MENU_Options                5
#define IDS_MENU_Help                   6
#define IDS_MENU_SetContactPicture      7
#define IDS_MENU_SetContactCamera       8
#define IDS_MENU_SetContactRingtone     9
#define IDS_MENU_Okay                   10
#define IDS_Yes                         11
#define IDS_No                          12
#define IDS_Today                       13
#define IDS_NO_Programs                 14
#define IDS_SELECT_Program              15
#define IDS_SELECT_Setting              16
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_MENU_Unlock                 105
#define IDD_DLG_Modal                   105
#define IDS_MENU_Ok                     106
#define IDR_MENU_NewDoneMenu            106
#define IDS_MENU_Cancel                 107
#define IDR_PNG_BT                      107
#define IDS_MENU_Quit                   108
#define IDR_BTVGA                       108
#define IDR_PNG_BTVGA                   108
#define IDR_PNG_Wifi                    109
#define IDS_MENU_Back                   110
#define IDR_PNG_WifiVGA                 110
#define IDS_MENU_Add                    111
#define IDS_MENU_Remove                 112
#define IDS_MENU_Edit                   114
#define IDS_MENU_AddNew                 115
#define IDS_MENU_AddContact             116
#define IDS_MENU_NewDone                117
#define IDS_MENU_NewMenu                118
#define IDR_PNG_Alarm                   120
#define IDR_PNG_AlarmVGA                121
#define IDR_MENU_Unlock                 129
#define IDR_MENU_OkCancel               133
#define IDD_DLG_Basic                   134
#define IDR_MENU_Quit                   135
#define IDR_MENU_MenuBack               136
#define IDR_MENU_EditBack               139
#define IDR_PNG_MenuArray               139
#define IDR_PNG_MenuArrayVGA            140
#define IDR_PNG_Selector                141
#define IDR_PNG_ContactsBorder          142
#define IDR_PNG_ContactsBorderVGA       143
#define IDR_PNG_FavoritesImgAlpha       144
#define IDR_PNG_FavoritesImgAlphaVGA    145
#define IDR_PNG_FavoritesImgBorder      146
#define IDR_PNG_FavoritesImgBorderVGA   147
#define IDR_PNG_FavoritesImgDefault     148
#define IDR_PNG_FavoritesImgDefaultVGA  149
#define IDR_PNG_DetailsBackGreen        150
#define IDR_PNG_DetailsBackGreenVGA     151
#define IDR_PNG_DetailsBtnGreen         152
#define IDR_PNG_DetailsBtnGreenVGA      153
#define IDR_PNG_DetailsBtn              154
#define IDR_PNG_DetailsBtnVGA           155
#define IDR_PNG_DetailsDefault          156
#define IDR_PNG_DetailsDefaultVGA       157
#define IDR_PNG_Group                   158
#define IDR_Profile                     159
#define IDR_ProfileVGA                  160
#define IDR_PNG_Notify                  161
#define IDR_PNG_NotifyVGA               162
#define IDR_PNG_Mail                    163
#define IDR_PNG_MailVGA                 164
#define IDR_PNG_Missed                  165
#define IDR_PNG_MissedVGA               166
#define IDR_PNG_Sms                     167
#define IDR_PNG_SmsVGA                  168
#define IDR_PNG_Time                    169
#define IDR_PNG_TimeVGA                 170
#define IDR_PNG_Voice                   171
#define IDR_PNG_VoiceVGA                172
#define IDR_PNG_TimeFont                173
#define IDR_PNG_TimeFontSmall           174
#define IDR_PNG_TimeFontVGA             175
#define IDR_PNG_TodaySelector           179
#define IDR_PNG_ContactsSelector        185
#define IDR_PNG_CallBg                  186
#define IDR_PNG_CallBgVGA               187
#define IDR_PNG_ShineVGA                188
#define IDR_PNG_DropBg                  189
#define IDR_PNG_DropBgVGA               190
#define IDR_PNG_Shine                   191
#define IDR_MENU_Voicemail              194
#define IDR_PNG_ButtonSelected          195
#define IDR_PNG_ButtonSelectedVGA       196
#define IDR_PNG_Button                  197
#define IDR_PNG_ButtonVGA               198
#define IDR_PNG_NotifyGreenVGA          200
#define IDR_PNG_NotifyGreen             201
#define IDR_PNG_NotifyBlueVGA           202
#define IDR_PNG_NotifyBlue              203
#define IDR_PNG_NotifyRedVGA            204
#define IDR_PNG_NotifyRed               205
#define IDR_PNG_NotifyOrangeVGA         206
#define IDR_PNG_NotifyOrange            207
#define IDR_PNG_NotifyPinkVGA           208
#define IDR_PNG_NotifyPink              209
#define IDR_PNG_NotifyPurpleVGA         210
#define IDR_PNG_NotifyPurple            211
#define IDD_TODAY_CUSTOM                500
#define IDR_MENU_Done                   600
#define IDS_MENU_Done                   601
#define IDS_MENU_Menu                   602
#define IDMENU_Unlock                   32772
#define IDMENU_Cancel                   32774
#define IDMENU_Ok                       32776
#define IDMENU_Quit                     32778
#define IDMENU_Back                     32780
#define IDMENU_Menu                     32782
#define IDMENU_Done                     32785
#define IDMENU_Edit                     32786
#define IDMENU_EditContact              32789
#define IDMENU_Options                  32790
#define IDMENU_Help                     32791
#define IDMENU_Conversation             32792
#define IDMENU_SetContactPicture        32793
#define IDMENU_SetContactCamera         32794
#define ID_CANCEL32794                  32794
#define IDMENU_SetContactRingtone       32795
#define ID_OK32795                      32795
#define ID_MENU                         40001
#define ID_DONE                         40002
#define ID_MENU40003                    40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
