//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuitarSuite.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable_du {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable_du() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuitarSuite.Strings.StringTable.du", typeof(StringTable_du).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar Suite.
        /// </summary>
        internal static string IDS_APP_TITLE {
            get {
                return ResourceManager.GetString("IDS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wissen.
        /// </summary>
        internal static string IDS_Clear {
            get {
                return ResourceManager.GetString("IDS_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangepaste.
        /// </summary>
        internal static string IDS_Custom {
            get {
                return ResourceManager.GetString("IDS_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequentie (Hz).
        /// </summary>
        internal static string IDS_INFO_Frequency {
            get {
                return ResourceManager.GetString("IDS_INFO_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %iHz.
        /// </summary>
        internal static string IDS_INFO_Hz {
            get {
                return ResourceManager.GetString("IDS_INFO_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string IDS_INFO_Meter {
            get {
                return ResourceManager.GetString("IDS_INFO_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toonhoogte.
        /// </summary>
        internal static string IDS_INFO_Pitch {
            get {
                return ResourceManager.GetString("IDS_INFO_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwaliteit van het signaal.
        /// </summary>
        internal static string IDS_INFO_SignalQuality {
            get {
                return ResourceManager.GetString("IDS_INFO_SignalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        internal static string IDS_INFO_Tempo {
            get {
                return ResourceManager.GetString("IDS_INFO_Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string IDS_MENU_About {
            get {
                return ResourceManager.GetString("IDS_MENU_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teruggaan.
        /// </summary>
        internal static string IDS_MENU_Back {
            get {
                return ResourceManager.GetString("IDS_MENU_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleer.
        /// </summary>
        internal static string IDS_MENU_Cancel {
            get {
                return ResourceManager.GetString("IDS_MENU_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akkoorden.
        /// </summary>
        internal static string IDS_MENU_Chords {
            get {
                return ResourceManager.GetString("IDS_MENU_Chords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitaal.
        /// </summary>
        internal static string IDS_MENU_Digital {
            get {
                return ResourceManager.GetString("IDS_MENU_Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsluiten.
        /// </summary>
        internal static string IDS_MENU_Exit {
            get {
                return ResourceManager.GetString("IDS_MENU_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string IDS_MENU_Help {
            get {
                return ResourceManager.GetString("IDS_MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string IDS_MENU_Menu {
            get {
                return ResourceManager.GetString("IDS_MENU_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metronoom.
        /// </summary>
        internal static string IDS_MENU_Metronome {
            get {
                return ResourceManager.GetString("IDS_MENU_Metronome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meer Apps.
        /// </summary>
        internal static string IDS_MENU_MoreApps {
            get {
                return ResourceManager.GetString("IDS_MENU_MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string IDS_MENU_No {
            get {
                return ResourceManager.GetString("IDS_MENU_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_MENU_Ok {
            get {
                return ResourceManager.GetString("IDS_MENU_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties.
        /// </summary>
        internal static string IDS_MENU_Options {
            get {
                return ResourceManager.GetString("IDS_MENU_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelen.
        /// </summary>
        internal static string IDS_MENU_Play {
            get {
                return ResourceManager.GetString("IDS_MENU_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afspeelmodus.
        /// </summary>
        internal static string IDS_MENU_PlayMode {
            get {
                return ResourceManager.GetString("IDS_MENU_PlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluit.
        /// </summary>
        internal static string IDS_MENU_Quit {
            get {
                return ResourceManager.GetString("IDS_MENU_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besparen.
        /// </summary>
        internal static string IDS_MENU_Save {
            get {
                return ResourceManager.GetString("IDS_MENU_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string IDS_MENU_Start {
            get {
                return ResourceManager.GetString("IDS_MENU_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string IDS_MENU_Stop {
            get {
                return ResourceManager.GetString("IDS_MENU_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner (oor).
        /// </summary>
        internal static string IDS_MENU_TuneByEar {
            get {
                return ResourceManager.GetString("IDS_MENU_TuneByEar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner.
        /// </summary>
        internal static string IDS_MENU_Tuner {
            get {
                return ResourceManager.GetString("IDS_MENU_Tuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string IDS_MENU_Yes {
            get {
                return ResourceManager.GetString("IDS_MENU_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versie 1.5.0\r\n\r\nCopyright 2009-2011\r\nwww.panoramicsoft.com.
        /// </summary>
        internal static string IDS_MSG_About {
            get {
                return ResourceManager.GetString("IDS_MSG_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij hopen dat u genoten uit te proberen Panoramic Guitar Suite, heeft uw proefperiode inmiddels verstreken.\r\n\r\nVoor de aankoop van: ga dan terug naar de website waarop uw trial download verstrekt..
        /// </summary>
        internal static string IDS_MSG_DemoOver {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u wilt Panoramic Guitar Suite afsluiten?.
        /// </summary>
        internal static string IDS_MSG_Exit {
            get {
                return ResourceManager.GetString("IDS_MSG_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tik Hier.
        /// </summary>
        internal static string IDS_MSG_SetBPM {
            get {
                return ResourceManager.GetString("IDS_MSG_SetBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akoestische Gitaar.
        /// </summary>
        internal static string IDS_OPT_Accoustic {
            get {
                return ResourceManager.GetString("IDS_OPT_Accoustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Els.
        /// </summary>
        internal static string IDS_OPT_Alder {
            get {
                return ResourceManager.GetString("IDS_OPT_Alder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banjo.
        /// </summary>
        internal static string IDS_OPT_Banjo {
            get {
                return ResourceManager.GetString("IDS_OPT_Banjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basgitaar.
        /// </summary>
        internal static string IDS_OPT_BassGuitar {
            get {
                return ResourceManager.GetString("IDS_OPT_BassGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basgitaar (5).
        /// </summary>
        internal static string IDS_OPT_BassGuitar5 {
            get {
                return ResourceManager.GetString("IDS_OPT_BassGuitar5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koolstof.
        /// </summary>
        internal static string IDS_OPT_Carbon {
            get {
                return ResourceManager.GetString("IDS_OPT_Carbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absoluut Stijl.
        /// </summary>
        internal static string IDS_OPT_ChordStrumMode {
            get {
                return ResourceManager.GetString("IDS_OPT_ChordStrumMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aangepaste tuning.
        /// </summary>
        internal static string IDS_OPT_CustomTuning {
            get {
                return ResourceManager.GetString("IDS_OPT_CustomTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snelle.
        /// </summary>
        internal static string IDS_OPT_FastStrum {
            get {
                return ResourceManager.GetString("IDS_OPT_FastStrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string IDS_OPT_Fire {
            get {
                return ResourceManager.GetString("IDS_OPT_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat (♭).
        /// </summary>
        internal static string IDS_OPT_Flat {
            get {
                return ResourceManager.GetString("IDS_OPT_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handmatig.
        /// </summary>
        internal static string IDS_OPT_FreeStrum {
            get {
                return ResourceManager.GetString("IDS_OPT_FreeStrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fret indicatoren.
        /// </summary>
        internal static string IDS_OPT_FretIndicators {
            get {
                return ResourceManager.GetString("IDS_OPT_FretIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitaar.
        /// </summary>
        internal static string IDS_OPT_Guitar {
            get {
                return ResourceManager.GetString("IDS_OPT_Guitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshandigen.
        /// </summary>
        internal static string IDS_OPT_LeftHanded {
            get {
                return ResourceManager.GetString("IDS_OPT_LeftHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luit.
        /// </summary>
        internal static string IDS_OPT_Lute {
            get {
                return ResourceManager.GetString("IDS_OPT_Lute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metaal.
        /// </summary>
        internal static string IDS_OPT_Metal {
            get {
                return ResourceManager.GetString("IDS_OPT_Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metronoomgeluid.
        /// </summary>
        internal static string IDS_OPT_MetronomeSound {
            get {
                return ResourceManager.GetString("IDS_OPT_MetronomeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mollen notatie.
        /// </summary>
        internal static string IDS_OPT_Notation {
            get {
                return ResourceManager.GetString("IDS_OPT_Notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getallen.
        /// </summary>
        internal static string IDS_OPT_Numbers {
            get {
                return ResourceManager.GetString("IDS_OPT_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitschakelen.
        /// </summary>
        internal static string IDS_OPT_Off {
            get {
                return ResourceManager.GetString("IDS_OPT_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op.
        /// </summary>
        internal static string IDS_OPT_On {
            get {
                return ResourceManager.GetString("IDS_OPT_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Opties.
        /// </summary>
        internal static string IDS_OPT_Options {
            get {
                return ResourceManager.GetString("IDS_OPT_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektrische Gitaar.
        /// </summary>
        internal static string IDS_OPT_Overdrive {
            get {
                return ResourceManager.GetString("IDS_OPT_Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roze.
        /// </summary>
        internal static string IDS_OPT_PinkBubbles {
            get {
                return ResourceManager.GetString("IDS_OPT_PinkBubbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string IDS_OPT_PlaySounds {
            get {
                return ResourceManager.GetString("IDS_OPT_PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebel.
        /// </summary>
        internal static string IDS_OPT_Rebel {
            get {
                return ResourceManager.GetString("IDS_OPT_Rebel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romeinse Cijfers.
        /// </summary>
        internal static string IDS_OPT_RomanNumerals {
            get {
                return ResourceManager.GetString("IDS_OPT_RomanNumerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozenhout.
        /// </summary>
        internal static string IDS_OPT_Rosewood {
            get {
                return ResourceManager.GetString("IDS_OPT_Rosewood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen.
        /// </summary>
        internal static string IDS_OPT_ScalesOff {
            get {
                return ResourceManager.GetString("IDS_OPT_ScalesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gevoeligheid van de Tuner.
        /// </summary>
        internal static string IDS_OPT_Sensitivity {
            get {
                return ResourceManager.GetString("IDS_OPT_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scherpe (♯).
        /// </summary>
        internal static string IDS_OPT_Sharp {
            get {
                return ResourceManager.GetString("IDS_OPT_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stille.
        /// </summary>
        internal static string IDS_OPT_Silent {
            get {
                return ResourceManager.GetString("IDS_OPT_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to huid.
        /// </summary>
        internal static string IDS_OPT_Skin {
            get {
                return ResourceManager.GetString("IDS_OPT_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertragen.
        /// </summary>
        internal static string IDS_OPT_SlowStrum {
            get {
                return ResourceManager.GetString("IDS_OPT_SlowStrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blauw.
        /// </summary>
        internal static string IDS_OPT_SonicBlue {
            get {
                return ResourceManager.GetString("IDS_OPT_SonicBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instrument geluid.
        /// </summary>
        internal static string IDS_OPT_SoundType {
            get {
                return ResourceManager.GetString("IDS_OPT_SoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synth.
        /// </summary>
        internal static string IDS_OPT_Synth {
            get {
                return ResourceManager.GetString("IDS_OPT_Synth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        internal static string IDS_OPT_Tempo {
            get {
                return ResourceManager.GetString("IDS_OPT_Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequentie Limiet.
        /// </summary>
        internal static string IDS_OPT_TunerCutoff {
            get {
                return ResourceManager.GetString("IDS_OPT_TunerCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner Frequentie.
        /// </summary>
        internal static string IDS_OPT_TunerFrequency {
            get {
                return ResourceManager.GetString("IDS_OPT_TunerFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner ber Eik.
        /// </summary>
        internal static string IDS_OPT_TuningRange {
            get {
                return ResourceManager.GetString("IDS_OPT_TuningRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukulele.
        /// </summary>
        internal static string IDS_OPT_Ukulele {
            get {
                return ResourceManager.GetString("IDS_OPT_Ukulele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hout.
        /// </summary>
        internal static string IDS_OPT_Wood {
            get {
                return ResourceManager.GetString("IDS_OPT_Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbel.
        /// </summary>
        internal static string IDS_TUN_Double {
            get {
                return ResourceManager.GetString("IDS_TUN_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omlaag.
        /// </summary>
        internal static string IDS_TUN_Down {
            get {
                return ResourceManager.GetString("IDS_TUN_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druppel.
        /// </summary>
        internal static string IDS_TUN_Drop {
            get {
                return ResourceManager.GetString("IDS_TUN_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vierde.
        /// </summary>
        internal static string IDS_TUN_Fourths {
            get {
                return ResourceManager.GetString("IDS_TUN_Fourths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hele.
        /// </summary>
        internal static string IDS_TUN_Full {
            get {
                return ResourceManager.GetString("IDS_TUN_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helft.
        /// </summary>
        internal static string IDS_TUN_Half {
            get {
                return ResourceManager.GetString("IDS_TUN_Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laag.
        /// </summary>
        internal static string IDS_TUN_Low {
            get {
                return ResourceManager.GetString("IDS_TUN_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modaal.
        /// </summary>
        internal static string IDS_TUN_Modal {
            get {
                return ResourceManager.GetString("IDS_TUN_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string IDS_TUN_Open {
            get {
                return ResourceManager.GetString("IDS_TUN_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschoven.
        /// </summary>
        internal static string IDS_TUN_Shifted {
            get {
                return ResourceManager.GetString("IDS_TUN_Shifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standaard.
        /// </summary>
        internal static string IDS_TUN_Standard {
            get {
                return ResourceManager.GetString("IDS_TUN_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omhoog.
        /// </summary>
        internal static string IDS_TUN_Up {
            get {
                return ResourceManager.GetString("IDS_TUN_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouzouki.
        /// </summary>
        internal static string IDS_TUNE_Bouzouki {
            get {
                return ResourceManager.GetString("IDS_TUNE_Bouzouki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouzouki 2.
        /// </summary>
        internal static string IDS_TUNE_Bouzouki2 {
            get {
                return ResourceManager.GetString("IDS_TUNE_Bouzouki2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouzouki 3.
        /// </summary>
        internal static string IDS_TUNE_Bouzouki3 {
            get {
                return ResourceManager.GetString("IDS_TUNE_Bouzouki3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandola.
        /// </summary>
        internal static string IDS_TUNE_Mandola {
            get {
                return ResourceManager.GetString("IDS_TUNE_Mandola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandoline.
        /// </summary>
        internal static string IDS_TUNE_Mandolin {
            get {
                return ResourceManager.GetString("IDS_TUNE_Mandolin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipa.
        /// </summary>
        internal static string IDS_TUNE_Pipa {
            get {
                return ResourceManager.GetString("IDS_TUNE_Pipa", resourceCulture);
            }
        }
    }
}
