//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuitarSuite.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable_jp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuitarSuite.Strings.StringTable.jp", typeof(StringTable_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar Suite.
        /// </summary>
        internal static string IDS_APP_TITLE {
            get {
                return ResourceManager.GetString("IDS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string IDS_CHORD_11 {
            get {
                return ResourceManager.GetString("IDS_CHORD_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string IDS_CHORD_13 {
            get {
                return ResourceManager.GetString("IDS_CHORD_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string IDS_CHORD_5 {
            get {
                return ResourceManager.GetString("IDS_CHORD_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string IDS_CHORD_6 {
            get {
                return ResourceManager.GetString("IDS_CHORD_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string IDS_CHORD_7 {
            get {
                return ResourceManager.GetString("IDS_CHORD_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7b5.
        /// </summary>
        internal static string IDS_CHORD_7b5 {
            get {
                return ResourceManager.GetString("IDS_CHORD_7b5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7b9.
        /// </summary>
        internal static string IDS_CHORD_7b9 {
            get {
                return ResourceManager.GetString("IDS_CHORD_7b9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7sus4.
        /// </summary>
        internal static string IDS_CHORD_7sus4 {
            get {
                return ResourceManager.GetString("IDS_CHORD_7sus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string IDS_CHORD_9 {
            get {
                return ResourceManager.GetString("IDS_CHORD_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9sus4.
        /// </summary>
        internal static string IDS_CHORD_9sus4 {
            get {
                return ResourceManager.GetString("IDS_CHORD_9sus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add9.
        /// </summary>
        internal static string IDS_CHORD_Add9 {
            get {
                return ResourceManager.GetString("IDS_CHORD_Add9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug.
        /// </summary>
        internal static string IDS_CHORD_Aug {
            get {
                return ResourceManager.GetString("IDS_CHORD_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug9.
        /// </summary>
        internal static string IDS_CHORD_Aug9 {
            get {
                return ResourceManager.GetString("IDS_CHORD_Aug9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim.
        /// </summary>
        internal static string IDS_CHORD_Dim {
            get {
                return ResourceManager.GetString("IDS_CHORD_Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string IDS_CHORD_M {
            get {
                return ResourceManager.GetString("IDS_CHORD_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m11.
        /// </summary>
        internal static string IDS_CHORD_M11 {
            get {
                return ResourceManager.GetString("IDS_CHORD_M11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m13.
        /// </summary>
        internal static string IDS_CHORD_M13 {
            get {
                return ResourceManager.GetString("IDS_CHORD_M13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m6.
        /// </summary>
        internal static string IDS_CHORD_M6 {
            get {
                return ResourceManager.GetString("IDS_CHORD_M6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m7.
        /// </summary>
        internal static string IDS_CHORD_M7 {
            get {
                return ResourceManager.GetString("IDS_CHORD_M7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m9.
        /// </summary>
        internal static string IDS_CHORD_M9 {
            get {
                return ResourceManager.GetString("IDS_CHORD_M9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj.
        /// </summary>
        internal static string IDS_CHORD_Maj {
            get {
                return ResourceManager.GetString("IDS_CHORD_Maj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj13.
        /// </summary>
        internal static string IDS_CHORD_Maj13 {
            get {
                return ResourceManager.GetString("IDS_CHORD_Maj13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj7.
        /// </summary>
        internal static string IDS_CHORD_Maj7 {
            get {
                return ResourceManager.GetString("IDS_CHORD_Maj7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj9.
        /// </summary>
        internal static string IDS_CHORD_Maj9 {
            get {
                return ResourceManager.GetString("IDS_CHORD_Maj9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus2.
        /// </summary>
        internal static string IDS_CHORD_Sus2 {
            get {
                return ResourceManager.GetString("IDS_CHORD_Sus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus4.
        /// </summary>
        internal static string IDS_CHORD_Sus4 {
            get {
                return ResourceManager.GetString("IDS_CHORD_Sus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消去します。.
        /// </summary>
        internal static string IDS_Clear {
            get {
                return ResourceManager.GetString("IDS_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カスタム.
        /// </summary>
        internal static string IDS_Custom {
            get {
                return ResourceManager.GetString("IDS_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周波数(Hz).
        /// </summary>
        internal static string IDS_INFO_Frequency {
            get {
                return ResourceManager.GetString("IDS_INFO_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %iHz.
        /// </summary>
        internal static string IDS_INFO_Hz {
            get {
                return ResourceManager.GetString("IDS_INFO_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拍子.
        /// </summary>
        internal static string IDS_INFO_Meter {
            get {
                return ResourceManager.GetString("IDS_INFO_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピッチ.
        /// </summary>
        internal static string IDS_INFO_Pitch {
            get {
                return ResourceManager.GetString("IDS_INFO_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信号品質.
        /// </summary>
        internal static string IDS_INFO_SignalQuality {
            get {
                return ResourceManager.GetString("IDS_INFO_SignalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テンポ.
        /// </summary>
        internal static string IDS_INFO_Tempo {
            get {
                return ResourceManager.GetString("IDS_INFO_Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string IDS_MENU_About {
            get {
                return ResourceManager.GetString("IDS_MENU_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        internal static string IDS_MENU_Back {
            get {
                return ResourceManager.GetString("IDS_MENU_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string IDS_MENU_Cancel {
            get {
                return ResourceManager.GetString("IDS_MENU_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コード.
        /// </summary>
        internal static string IDS_MENU_Chords {
            get {
                return ResourceManager.GetString("IDS_MENU_Chords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジタル.
        /// </summary>
        internal static string IDS_MENU_Digital {
            get {
                return ResourceManager.GetString("IDS_MENU_Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string IDS_MENU_Exit {
            get {
                return ResourceManager.GetString("IDS_MENU_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        internal static string IDS_MENU_Help {
            get {
                return ResourceManager.GetString("IDS_MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メニュー.
        /// </summary>
        internal static string IDS_MENU_Menu {
            get {
                return ResourceManager.GetString("IDS_MENU_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メトロノーム.
        /// </summary>
        internal static string IDS_MENU_Metronome {
            get {
                return ResourceManager.GetString("IDS_MENU_Metronome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のアプリを見る.
        /// </summary>
        internal static string IDS_MENU_MoreApps {
            get {
                return ResourceManager.GetString("IDS_MENU_MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いいえ.
        /// </summary>
        internal static string IDS_MENU_No {
            get {
                return ResourceManager.GetString("IDS_MENU_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_MENU_Ok {
            get {
                return ResourceManager.GetString("IDS_MENU_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オプション.
        /// </summary>
        internal static string IDS_MENU_Options {
            get {
                return ResourceManager.GetString("IDS_MENU_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 演奏.
        /// </summary>
        internal static string IDS_MENU_Play {
            get {
                return ResourceManager.GetString("IDS_MENU_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 演奏モード.
        /// </summary>
        internal static string IDS_MENU_PlayMode {
            get {
                return ResourceManager.GetString("IDS_MENU_PlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算式のプロを購入します。.
        /// </summary>
        internal static string IDS_MENU_Purchase {
            get {
                return ResourceManager.GetString("IDS_MENU_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やめる.
        /// </summary>
        internal static string IDS_MENU_Quit {
            get {
                return ResourceManager.GetString("IDS_MENU_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string IDS_MENU_Save {
            get {
                return ResourceManager.GetString("IDS_MENU_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始.
        /// </summary>
        internal static string IDS_MENU_Start {
            get {
                return ResourceManager.GetString("IDS_MENU_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一時停止.
        /// </summary>
        internal static string IDS_MENU_Stop {
            get {
                return ResourceManager.GetString("IDS_MENU_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耳チューン.
        /// </summary>
        internal static string IDS_MENU_TuneByEar {
            get {
                return ResourceManager.GetString("IDS_MENU_TuneByEar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チューナー.
        /// </summary>
        internal static string IDS_MENU_Tuner {
            get {
                return ResourceManager.GetString("IDS_MENU_Tuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to はい.
        /// </summary>
        internal static string IDS_MENU_Yes {
            get {
                return ResourceManager.GetString("IDS_MENU_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.5.0\r\nCopyright 2009-2011\r\n\r\nPanoramic Software Inc.\r\nwww.panoramicsoft.com.
        /// </summary>
        internal static string IDS_MSG_About {
            get {
                return ResourceManager.GetString("IDS_MSG_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string IDS_MSG_DemoOver {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お試し期間の終了.
        /// </summary>
        internal static string IDS_MSG_DemoOverShort {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOverShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギタースィートを終了しますか?.
        /// </summary>
        internal static string IDS_MSG_Exit {
            get {
                return ResourceManager.GetString("IDS_MSG_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to をタップします\r\n。BPM.
        /// </summary>
        internal static string IDS_MSG_SetBPM {
            get {
                return ResourceManager.GetString("IDS_MSG_SetBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11025Hz.
        /// </summary>
        internal static string IDS_OPT_11025Hz {
            get {
                return ResourceManager.GetString("IDS_OPT_11025Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22050Hz.
        /// </summary>
        internal static string IDS_OPT_22050Hz {
            get {
                return ResourceManager.GetString("IDS_OPT_22050Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44100Hz.
        /// </summary>
        internal static string IDS_OPT_44100Hz {
            get {
                return ResourceManager.GetString("IDS_OPT_44100Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アコースティック ・ ギター.
        /// </summary>
        internal static string IDS_OPT_Accoustic {
            get {
                return ResourceManager.GetString("IDS_OPT_Accoustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adagio.
        /// </summary>
        internal static string IDS_OPT_Adagio {
            get {
                return ResourceManager.GetString("IDS_OPT_Adagio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エオリアン.
        /// </summary>
        internal static string IDS_OPT_Aeolian {
            get {
                return ResourceManager.GetString("IDS_OPT_Aeolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アルダー.
        /// </summary>
        internal static string IDS_OPT_Alder {
            get {
                return ResourceManager.GetString("IDS_OPT_Alder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allegro.
        /// </summary>
        internal static string IDS_OPT_Allegro {
            get {
                return ResourceManager.GetString("IDS_OPT_Allegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andante.
        /// </summary>
        internal static string IDS_OPT_Andante {
            get {
                return ResourceManager.GetString("IDS_OPT_Andante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーキュメント.
        /// </summary>
        internal static string IDS_OPT_Augmented {
            get {
                return ResourceManager.GetString("IDS_OPT_Augmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーグジアリー・オーキュメント.
        /// </summary>
        internal static string IDS_OPT_AuxiliaryAugmented {
            get {
                return ResourceManager.GetString("IDS_OPT_AuxiliaryAugmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーグジアリー・ディミニッシュ.
        /// </summary>
        internal static string IDS_OPT_AuxiliaryDiminished {
            get {
                return ResourceManager.GetString("IDS_OPT_AuxiliaryDiminished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーグジアリー・ディミニッシュ　ブルース.
        /// </summary>
        internal static string IDS_OPT_AuxiliaryDiminishedBlues {
            get {
                return ResourceManager.GetString("IDS_OPT_AuxiliaryDiminishedBlues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バンジョー.
        /// </summary>
        internal static string IDS_OPT_Banjo {
            get {
                return ResourceManager.GetString("IDS_OPT_Banjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベースギター.
        /// </summary>
        internal static string IDS_OPT_BassGuitar {
            get {
                return ResourceManager.GetString("IDS_OPT_BassGuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベースギター(5).
        /// </summary>
        internal static string IDS_OPT_BassGuitar5 {
            get {
                return ResourceManager.GetString("IDS_OPT_BassGuitar5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブルース.
        /// </summary>
        internal static string IDS_OPT_Blues {
            get {
                return ResourceManager.GetString("IDS_OPT_Blues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カーボン.
        /// </summary>
        internal static string IDS_OPT_Carbon {
            get {
                return ResourceManager.GetString("IDS_OPT_Carbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コードストロークモード.
        /// </summary>
        internal static string IDS_OPT_ChordStrumMode {
            get {
                return ResourceManager.GetString("IDS_OPT_ChordStrumMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クロマティック.
        /// </summary>
        internal static string IDS_OPT_Chromatic {
            get {
                return ResourceManager.GetString("IDS_OPT_Chromatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カスタムのチューニング.
        /// </summary>
        internal static string IDS_OPT_CustomTuning {
            get {
                return ResourceManager.GetString("IDS_OPT_CustomTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディミニッシュ・ホールトーン.
        /// </summary>
        internal static string IDS_OPT_DiminishedWholeTone {
            get {
                return ResourceManager.GetString("IDS_OPT_DiminishedWholeTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドリアン.
        /// </summary>
        internal static string IDS_OPT_Dorian {
            get {
                return ResourceManager.GetString("IDS_OPT_Dorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブル・ハーモニック.
        /// </summary>
        internal static string IDS_OPT_DoubleHarmonic {
            get {
                return ResourceManager.GetString("IDS_OPT_DoubleHarmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8ノート・スパニッシュ.
        /// </summary>
        internal static string IDS_OPT_EightToneSpanish {
            get {
                return ResourceManager.GetString("IDS_OPT_EightToneSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エニグマティック.
        /// </summary>
        internal static string IDS_OPT_Enigmatic {
            get {
                return ResourceManager.GetString("IDS_OPT_Enigmatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファスト・ストローク.
        /// </summary>
        internal static string IDS_OPT_FastStrum {
            get {
                return ResourceManager.GetString("IDS_OPT_FastStrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 炎.
        /// </summary>
        internal static string IDS_OPT_Fire {
            get {
                return ResourceManager.GetString("IDS_OPT_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フラット (♭).
        /// </summary>
        internal static string IDS_OPT_Flat {
            get {
                return ResourceManager.GetString("IDS_OPT_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フリー・ストローク.
        /// </summary>
        internal static string IDS_OPT_FreeStrum {
            get {
                return ResourceManager.GetString("IDS_OPT_FreeStrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フレット表示.
        /// </summary>
        internal static string IDS_OPT_FretIndicators {
            get {
                return ResourceManager.GetString("IDS_OPT_FretIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギター.
        /// </summary>
        internal static string IDS_OPT_Guitar {
            get {
                return ResourceManager.GetString("IDS_OPT_Guitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハーフ・ディミニッシュ.
        /// </summary>
        internal static string IDS_OPT_HalfDiminished {
            get {
                return ResourceManager.GetString("IDS_OPT_HalfDiminished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハーモニックマイナー.
        /// </summary>
        internal static string IDS_OPT_HarmonicMinor {
            get {
                return ResourceManager.GetString("IDS_OPT_HarmonicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 楽器.
        /// </summary>
        internal static string IDS_OPT_Instrument {
            get {
                return ResourceManager.GetString("IDS_OPT_Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larghetto.
        /// </summary>
        internal static string IDS_OPT_Larghetto {
            get {
                return ResourceManager.GetString("IDS_OPT_Larghetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo.
        /// </summary>
        internal static string IDS_OPT_Largo {
            get {
                return ResourceManager.GetString("IDS_OPT_Largo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リーディング・ホール・トーン.
        /// </summary>
        internal static string IDS_OPT_LeadingWholeTone {
            get {
                return ResourceManager.GetString("IDS_OPT_LeadingWholeTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左利き.
        /// </summary>
        internal static string IDS_OPT_LeftHanded {
            get {
                return ResourceManager.GetString("IDS_OPT_LeftHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロクリアン.
        /// </summary>
        internal static string IDS_OPT_Locrian {
            get {
                return ResourceManager.GetString("IDS_OPT_Locrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リュート.
        /// </summary>
        internal static string IDS_OPT_Lute {
            get {
                return ResourceManager.GetString("IDS_OPT_Lute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リドリアン.
        /// </summary>
        internal static string IDS_OPT_Lydian {
            get {
                return ResourceManager.GetString("IDS_OPT_Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リディアン・オーキュメント.
        /// </summary>
        internal static string IDS_OPT_LydianAugmented {
            get {
                return ResourceManager.GetString("IDS_OPT_LydianAugmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リィディアン・ディミニッシュ.
        /// </summary>
        internal static string IDS_OPT_LydianDiminished {
            get {
                return ResourceManager.GetString("IDS_OPT_LydianDiminished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リディアン・マイナー.
        /// </summary>
        internal static string IDS_OPT_LydianMinor {
            get {
                return ResourceManager.GetString("IDS_OPT_LydianMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メジャー.
        /// </summary>
        internal static string IDS_OPT_Major {
            get {
                return ResourceManager.GetString("IDS_OPT_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メジャー・ロクリアン.
        /// </summary>
        internal static string IDS_OPT_MajorLocrian {
            get {
                return ResourceManager.GetString("IDS_OPT_MajorLocrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メロディック・マイナー上行型.
        /// </summary>
        internal static string IDS_OPT_MelodicMinorAscending {
            get {
                return ResourceManager.GetString("IDS_OPT_MelodicMinorAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メロディック・マイナー下行型.
        /// </summary>
        internal static string IDS_OPT_MelodicMinorDescending {
            get {
                return ResourceManager.GetString("IDS_OPT_MelodicMinorDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メタル.
        /// </summary>
        internal static string IDS_OPT_Metal {
            get {
                return ResourceManager.GetString("IDS_OPT_Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メトロノーム音.
        /// </summary>
        internal static string IDS_OPT_MetronomeSound {
            get {
                return ResourceManager.GetString("IDS_OPT_MetronomeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミクソリディアン.
        /// </summary>
        internal static string IDS_OPT_Mixolydian {
            get {
                return ResourceManager.GetString("IDS_OPT_Mixolydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderato.
        /// </summary>
        internal static string IDS_OPT_Moderato {
            get {
                return ResourceManager.GetString("IDS_OPT_Moderato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナポリタン・メジャー.
        /// </summary>
        internal static string IDS_OPT_NeopolitanMajor {
            get {
                return ResourceManager.GetString("IDS_OPT_NeopolitanMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナポリタン・マイナー.
        /// </summary>
        internal static string IDS_OPT_NeopolitanMinor {
            get {
                return ResourceManager.GetString("IDS_OPT_NeopolitanMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9トーン・スケール.
        /// </summary>
        internal static string IDS_OPT_NineToneScale {
            get {
                return ResourceManager.GetString("IDS_OPT_NineToneScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常.
        /// </summary>
        internal static string IDS_OPT_Normal {
            get {
                return ResourceManager.GetString("IDS_OPT_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音階の表記.
        /// </summary>
        internal static string IDS_OPT_Notation {
            get {
                return ResourceManager.GetString("IDS_OPT_Notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナンバース.
        /// </summary>
        internal static string IDS_OPT_Numbers {
            get {
                return ResourceManager.GetString("IDS_OPT_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オフ.
        /// </summary>
        internal static string IDS_OPT_Off {
            get {
                return ResourceManager.GetString("IDS_OPT_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オン.
        /// </summary>
        internal static string IDS_OPT_On {
            get {
                return ResourceManager.GetString("IDS_OPT_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  オプション.
        /// </summary>
        internal static string IDS_OPT_Options {
            get {
                return ResourceManager.GetString("IDS_OPT_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エレキギター.
        /// </summary>
        internal static string IDS_OPT_Overdrive {
            get {
                return ResourceManager.GetString("IDS_OPT_Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーバートーン.
        /// </summary>
        internal static string IDS_OPT_Overtone {
            get {
                return ResourceManager.GetString("IDS_OPT_Overtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペログ.
        /// </summary>
        internal static string IDS_OPT_Pelog {
            get {
                return ResourceManager.GetString("IDS_OPT_Pelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペンタトニック・ブルース.
        /// </summary>
        internal static string IDS_OPT_PentatonicBlues {
            get {
                return ResourceManager.GetString("IDS_OPT_PentatonicBlues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペンタトニック・メジャー.
        /// </summary>
        internal static string IDS_OPT_PentatonicMajor {
            get {
                return ResourceManager.GetString("IDS_OPT_PentatonicMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペンタトニック・マイナー.
        /// </summary>
        internal static string IDS_OPT_PentatonicMinor {
            get {
                return ResourceManager.GetString("IDS_OPT_PentatonicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペンタトニック・ナチュラル.
        /// </summary>
        internal static string IDS_OPT_PentatonicNeutral {
            get {
                return ResourceManager.GetString("IDS_OPT_PentatonicNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フリジアン.
        /// </summary>
        internal static string IDS_OPT_Phrygian {
            get {
                return ResourceManager.GetString("IDS_OPT_Phrygian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピンクバブル.
        /// </summary>
        internal static string IDS_OPT_PinkBubbles {
            get {
                return ResourceManager.GetString("IDS_OPT_PinkBubbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボリューム.
        /// </summary>
        internal static string IDS_OPT_PlaySounds {
            get {
                return ResourceManager.GetString("IDS_OPT_PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestissimo.
        /// </summary>
        internal static string IDS_OPT_Prestissimo {
            get {
                return ResourceManager.GetString("IDS_OPT_Prestissimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presto.
        /// </summary>
        internal static string IDS_OPT_Presto {
            get {
                return ResourceManager.GetString("IDS_OPT_Presto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロメテウス.
        /// </summary>
        internal static string IDS_OPT_Prometheus {
            get {
                return ResourceManager.GetString("IDS_OPT_Prometheus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロメテウス・ナポリタン.
        /// </summary>
        internal static string IDS_OPT_PrometheusNeopolitan {
            get {
                return ResourceManager.GetString("IDS_OPT_PrometheusNeopolitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反逆者.
        /// </summary>
        internal static string IDS_OPT_Rebel {
            get {
                return ResourceManager.GetString("IDS_OPT_Rebel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロマニアン・マイナー.
        /// </summary>
        internal static string IDS_OPT_RomanianMinor {
            get {
                return ResourceManager.GetString("IDS_OPT_RomanianMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ローマン・ヌーメラル.
        /// </summary>
        internal static string IDS_OPT_RomanNumerals {
            get {
                return ResourceManager.GetString("IDS_OPT_RomanNumerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ローズウッド.
        /// </summary>
        internal static string IDS_OPT_Rosewood {
            get {
                return ResourceManager.GetString("IDS_OPT_Rosewood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スケールオフ.
        /// </summary>
        internal static string IDS_OPT_Scale {
            get {
                return ResourceManager.GetString("IDS_OPT_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スケールオフ.
        /// </summary>
        internal static string IDS_OPT_ScalesOff {
            get {
                return ResourceManager.GetString("IDS_OPT_ScalesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チューナーの感度.
        /// </summary>
        internal static string IDS_OPT_Sensitivity {
            get {
                return ResourceManager.GetString("IDS_OPT_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シャープ (♯).
        /// </summary>
        internal static string IDS_OPT_Sharp {
            get {
                return ResourceManager.GetString("IDS_OPT_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シフト.
        /// </summary>
        internal static string IDS_OPT_Shift {
            get {
                return ResourceManager.GetString("IDS_OPT_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイレント.
        /// </summary>
        internal static string IDS_OPT_Silent {
            get {
                return ResourceManager.GetString("IDS_OPT_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6トーン・シンメトリック.
        /// </summary>
        internal static string IDS_OPT_SixToneSymmetrical {
            get {
                return ResourceManager.GetString("IDS_OPT_SixToneSymmetrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキン.
        /// </summary>
        internal static string IDS_OPT_Skin {
            get {
                return ResourceManager.GetString("IDS_OPT_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スロー・ストローク.
        /// </summary>
        internal static string IDS_OPT_SlowStrum {
            get {
                return ResourceManager.GetString("IDS_OPT_SlowStrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソニックブルー.
        /// </summary>
        internal static string IDS_OPT_SonicBlue {
            get {
                return ResourceManager.GetString("IDS_OPT_SonicBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 楽器音.
        /// </summary>
        internal static string IDS_OPT_SoundType {
            get {
                return ResourceManager.GetString("IDS_OPT_SoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スパニッシュ・ジプシー.
        /// </summary>
        internal static string IDS_OPT_SpanishGypsy {
            get {
                return ResourceManager.GetString("IDS_OPT_SpanishGypsy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スーパーロクリアン.
        /// </summary>
        internal static string IDS_OPT_SuperLocrian {
            get {
                return ResourceManager.GetString("IDS_OPT_SuperLocrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テンポ.
        /// </summary>
        internal static string IDS_OPT_Tempo {
            get {
                return ResourceManager.GetString("IDS_OPT_Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チューナー入力カットオフ.
        /// </summary>
        internal static string IDS_OPT_TunerCutoff {
            get {
                return ResourceManager.GetString("IDS_OPT_TunerCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チューナーサンプル周波数.
        /// </summary>
        internal static string IDS_OPT_TunerFrequency {
            get {
                return ResourceManager.GetString("IDS_OPT_TunerFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チューナーの範囲.
        /// </summary>
        internal static string IDS_OPT_TuningRange {
            get {
                return ResourceManager.GetString("IDS_OPT_TuningRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウクレレ.
        /// </summary>
        internal static string IDS_OPT_Ukulele {
            get {
                return ResourceManager.GetString("IDS_OPT_Ukulele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホール.
        /// </summary>
        internal static string IDS_OPT_Whole {
            get {
                return ResourceManager.GetString("IDS_OPT_Whole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホール・ディミニッシュ.
        /// </summary>
        internal static string IDS_OPT_WholeDiminished {
            get {
                return ResourceManager.GetString("IDS_OPT_WholeDiminished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウッド.
        /// </summary>
        internal static string IDS_OPT_Wood {
            get {
                return ResourceManager.GetString("IDS_OPT_Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string IDS_TUN_Double {
            get {
                return ResourceManager.GetString("IDS_TUN_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップ.
        /// </summary>
        internal static string IDS_TUN_Down {
            get {
                return ResourceManager.GetString("IDS_TUN_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドロップ.
        /// </summary>
        internal static string IDS_TUN_Drop {
            get {
                return ResourceManager.GetString("IDS_TUN_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォース.
        /// </summary>
        internal static string IDS_TUN_Fourths {
            get {
                return ResourceManager.GetString("IDS_TUN_Fourths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウン.
        /// </summary>
        internal static string IDS_TUN_Full {
            get {
                return ResourceManager.GetString("IDS_TUN_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全体.
        /// </summary>
        internal static string IDS_TUN_Half {
            get {
                return ResourceManager.GetString("IDS_TUN_Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロー.
        /// </summary>
        internal static string IDS_TUN_Low {
            get {
                return ResourceManager.GetString("IDS_TUN_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モーダル.
        /// </summary>
        internal static string IDS_TUN_Modal {
            get {
                return ResourceManager.GetString("IDS_TUN_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オープン.
        /// </summary>
        internal static string IDS_TUN_Open {
            get {
                return ResourceManager.GetString("IDS_TUN_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シフテッド.
        /// </summary>
        internal static string IDS_TUN_Shifted {
            get {
                return ResourceManager.GetString("IDS_TUN_Shifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタンダード.
        /// </summary>
        internal static string IDS_TUN_Standard {
            get {
                return ResourceManager.GetString("IDS_TUN_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブル.
        /// </summary>
        internal static string IDS_TUN_Up {
            get {
                return ResourceManager.GetString("IDS_TUN_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブズーキ.
        /// </summary>
        internal static string IDS_TUNE_Bouzouki {
            get {
                return ResourceManager.GetString("IDS_TUNE_Bouzouki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブズーキ 2.
        /// </summary>
        internal static string IDS_TUNE_Bouzouki2 {
            get {
                return ResourceManager.GetString("IDS_TUNE_Bouzouki2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブズーキ 3.
        /// </summary>
        internal static string IDS_TUNE_Bouzouki3 {
            get {
                return ResourceManager.GetString("IDS_TUNE_Bouzouki3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マンドーラ.
        /// </summary>
        internal static string IDS_TUNE_Mandola {
            get {
                return ResourceManager.GetString("IDS_TUNE_Mandola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マンドリン.
        /// </summary>
        internal static string IDS_TUNE_Mandolin {
            get {
                return ResourceManager.GetString("IDS_TUNE_Mandolin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピパ.
        /// </summary>
        internal static string IDS_TUNE_Pipa {
            get {
                return ResourceManager.GetString("IDS_TUNE_Pipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.0.
        /// </summary>
        internal static string IDS_VERSION {
            get {
                return ResourceManager.GetString("IDS_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.panoramicsoft.com.
        /// </summary>
        internal static string IDS_WEBSITE {
            get {
                return ResourceManager.GetString("IDS_WEBSITE", resourceCulture);
            }
        }
    }
}
