//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackJack.Strings.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.4.0\r\nCopyright 2008-2013\r\n\r\n Panoramic Software Inc.\r\nwww.panoramicsoft.com.
        /// </summary>
        public static string IDS_ABOUT_1 {
            get {
                return ResourceManager.GetString("IDS_ABOUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a pair of 8s twice in a game.
        /// </summary>
        public static string IDS_ACH1_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Hate 8s.
        /// </summary>
        public static string IDS_ACH1_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH1_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer busts 5 times in a row.
        /// </summary>
        public static string IDS_ACH10_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH10_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Up.
        /// </summary>
        public static string IDS_ACH10_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH10_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 10 hands in a row on card counting.
        /// </summary>
        public static string IDS_ACH11_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH11_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Count.
        /// </summary>
        public static string IDS_ACH11_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH11_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max bet on a high count.
        /// </summary>
        public static string IDS_ACH12_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH12_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Roller.
        /// </summary>
        public static string IDS_ACH12_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH12_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit on 18.
        /// </summary>
        public static string IDS_ACH13_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH13_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Gambler.
        /// </summary>
        public static string IDS_ACH13_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH13_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubling on 12 or more 5 times in a game and winning each hand.
        /// </summary>
        public static string IDS_ACH14_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH14_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Trouble.
        /// </summary>
        public static string IDS_ACH14_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH14_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-card 21 - all 5’s make an appearance.
        /// </summary>
        public static string IDS_ACH2_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH2_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woooh.
        /// </summary>
        public static string IDS_ACH2_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH2_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit blackjack 3 times in a row.
        /// </summary>
        public static string IDS_ACH3_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH3_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Fire.
        /// </summary>
        public static string IDS_ACH3_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH3_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 21 on both split hands.
        /// </summary>
        public static string IDS_ACH4_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH4_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Split.
        /// </summary>
        public static string IDS_ACH4_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH4_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 25,000.
        /// </summary>
        public static string IDS_ACH5_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH5_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25K!.
        /// </summary>
        public static string IDS_ACH5_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH5_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 50,000.
        /// </summary>
        public static string IDS_ACH6_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH6_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50K!.
        /// </summary>
        public static string IDS_ACH6_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH6_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 75,000.
        /// </summary>
        public static string IDS_ACH7_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH7_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75Gs.
        /// </summary>
        public static string IDS_ACH7_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH7_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 100,000.
        /// </summary>
        public static string IDS_ACH8_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH8_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100K!.
        /// </summary>
        public static string IDS_ACH8_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH8_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win the hand with 8 or more cards.
        /// </summary>
        public static string IDS_ACH9_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH9_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky Break.
        /// </summary>
        public static string IDS_ACH9_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH9_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panoramic Blackjack.
        /// </summary>
        public static string IDS_APP_TITLE {
            get {
                return ResourceManager.GetString("IDS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Color: Blue.
        /// </summary>
        public static string IDS_BGCOLOR_BLUE {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Color: Green.
        /// </summary>
        public static string IDS_BGCOLOR_GREEN {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Color: Purple.
        /// </summary>
        public static string IDS_BGCOLOR_PURPLE {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_PURPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Color: Red.
        /// </summary>
        public static string IDS_BGCOLOR_RED {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet.
        /// </summary>
        public static string IDS_BTNS_Bet {
            get {
                return ResourceManager.GetString("IDS_BTNS_Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        public static string IDS_BTNS_Deal {
            get {
                return ResourceManager.GetString("IDS_BTNS_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        public static string IDS_BTNS_Double {
            get {
                return ResourceManager.GetString("IDS_BTNS_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        public static string IDS_BTNS_Hit {
            get {
                return ResourceManager.GetString("IDS_BTNS_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string IDS_BTNS_Insurance {
            get {
                return ResourceManager.GetString("IDS_BTNS_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string IDS_BTNS_Late {
            get {
                return ResourceManager.GetString("IDS_BTNS_Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string IDS_BTNS_Reset {
            get {
                return ResourceManager.GetString("IDS_BTNS_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string IDS_BTNS_Split {
            get {
                return ResourceManager.GetString("IDS_BTNS_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand.
        /// </summary>
        public static string IDS_BTNS_Stand {
            get {
                return ResourceManager.GetString("IDS_BTNS_Stand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Low.
        /// </summary>
        public static string IDS_CMB_CC_HiLow {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiOpt1.
        /// </summary>
        public static string IDS_CMB_CC_HiOpt1 {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiOpt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiOpt2.
        /// </summary>
        public static string IDS_CMB_CC_HiOpt2 {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiOpt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KO.
        /// </summary>
        public static string IDS_CMB_CC_KO {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega II.
        /// </summary>
        public static string IDS_CMB_CC_OmegaII {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_OmegaII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string IDS_CMB_CC_Wizard {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zen.
        /// </summary>
        public static string IDS_CMB_CC_Zen {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_Zen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string IDS_CMB_CCV_Off {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string IDS_CMB_CCV_On {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Demand.
        /// </summary>
        public static string IDS_CMB_CCV_Semi {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_Semi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string IDS_CMB_GD_Custom {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficult.
        /// </summary>
        public static string IDS_CMB_GD_Difficult {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string IDS_CMB_GD_Easy {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn to Play.
        /// </summary>
        public static string IDS_CMB_GD_Learn {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string IDS_CMB_GD_Normal {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank: $%i.
        /// </summary>
        public static string IDS_INFO_BankAmt {
            get {
                return ResourceManager.GetString("IDS_INFO_BankAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank: demo.
        /// </summary>
        public static string IDS_INFO_BankDemo {
            get {
                return ResourceManager.GetString("IDS_INFO_BankDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet: $%i.
        /// </summary>
        public static string IDS_INFO_BetAmt {
            get {
                return ResourceManager.GetString("IDS_INFO_BetAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet: demo.
        /// </summary>
        public static string IDS_INFO_BetDemo {
            get {
                return ResourceManager.GetString("IDS_INFO_BetDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card\r\nCount.
        /// </summary>
        public static string IDS_INFO_CardCount {
            get {
                return ResourceManager.GetString("IDS_INFO_CardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string IDS_INFO_Count {
            get {
                return ResourceManager.GetString("IDS_INFO_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement Unlocked!.
        /// </summary>
        public static string IDS_LBL_AchievementUnlock {
            get {
                return ResourceManager.GetString("IDS_LBL_AchievementUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string IDS_LBL_Bank {
            get {
                return ResourceManager.GetString("IDS_LBL_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Count Style.
        /// </summary>
        public static string IDS_LBL_CardCounting {
            get {
                return ResourceManager.GetString("IDS_LBL_CardCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Count.
        /// </summary>
        public static string IDS_LBL_CardCountView {
            get {
                return ResourceManager.GetString("IDS_LBL_CardCountView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string IDS_LBL_Date {
            get {
                return ResourceManager.GetString("IDS_LBL_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Difficulty.
        /// </summary>
        public static string IDS_LBL_GameDifficulty {
            get {
                return ResourceManager.GetString("IDS_LBL_GameDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string IDS_LBL_Language {
            get {
                return ResourceManager.GetString("IDS_LBL_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sounds.
        /// </summary>
        public static string IDS_LBL_PlaySounds {
            get {
                return ResourceManager.GetString("IDS_LBL_PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string IDS_MENU_About {
            get {
                return ResourceManager.GetString("IDS_MENU_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string IDS_MENU_Achievements {
            get {
                return ResourceManager.GetString("IDS_MENU_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string IDS_MENU_Back {
            get {
                return ResourceManager.GetString("IDS_MENU_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string IDS_MENU_Cancel {
            get {
                return ResourceManager.GetString("IDS_MENU_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string IDS_MENU_Exit {
            get {
                return ResourceManager.GetString("IDS_MENU_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string IDS_MENU_Help {
            get {
                return ResourceManager.GetString("IDS_MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiScores.
        /// </summary>
        public static string IDS_MENU_HiScores {
            get {
                return ResourceManager.GetString("IDS_MENU_HiScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string IDS_MENU_Menu {
            get {
                return ResourceManager.GetString("IDS_MENU_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Apps.
        /// </summary>
        public static string IDS_MENU_MoreApps {
            get {
                return ResourceManager.GetString("IDS_MENU_MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string IDS_MENU_NewGame {
            get {
                return ResourceManager.GetString("IDS_MENU_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string IDS_MENU_No {
            get {
                return ResourceManager.GetString("IDS_MENU_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string IDS_MENU_Ok {
            get {
                return ResourceManager.GetString("IDS_MENU_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string IDS_MENU_Options {
            get {
                return ResourceManager.GetString("IDS_MENU_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string IDS_MENU_Quit {
            get {
                return ResourceManager.GetString("IDS_MENU_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string IDS_MENU_Resume {
            get {
                return ResourceManager.GetString("IDS_MENU_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        public static string IDS_MENU_ResumeGame {
            get {
                return ResourceManager.GetString("IDS_MENU_ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string IDS_MENU_Save {
            get {
                return ResourceManager.GetString("IDS_MENU_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string IDS_MENU_Yes {
            get {
                return ResourceManager.GetString("IDS_MENU_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re Broke! Would you like to start a new game?.
        /// </summary>
        public static string IDS_MSG_Broke {
            get {
                return ResourceManager.GetString("IDS_MSG_Broke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re Broke.
        /// </summary>
        public static string IDS_MSG_BrokeShort {
            get {
                return ResourceManager.GetString("IDS_MSG_BrokeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoyed playing Panoramic Blackjack, your trial has expired. To purchase: please return to the website that provided your trial download..
        /// </summary>
        public static string IDS_MSG_DemoOver {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit Panoramic Blackjack?.
        /// </summary>
        public static string IDS_MSG_Exit {
            get {
                return ResourceManager.GetString("IDS_MSG_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game is over but you achieved a high score! Would you like to start a new game? .
        /// </summary>
        public static string IDS_MSG_HiEndGame {
            get {
                return ResourceManager.GetString("IDS_MSG_HiEndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start a new game?.
        /// </summary>
        public static string IDS_MSG_NewGame {
            get {
                return ResourceManager.GetString("IDS_MSG_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoyed playing Panoramic Blackjack, your trial has expired..
        /// </summary>
        public static string IDS_MSG_TrialOverShort {
            get {
                return ResourceManager.GetString("IDS_MSG_TrialOverShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout Type.
        /// </summary>
        public static string IDS_OPT_BJPayout {
            get {
                return ResourceManager.GetString("IDS_OPT_BJPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn First Card.
        /// </summary>
        public static string IDS_OPT_BurnFirst {
            get {
                return ResourceManager.GetString("IDS_OPT_BurnFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Hits on Soft 17.
        /// </summary>
        public static string IDS_OPT_DealerHitSoft17 {
            get {
                return ResourceManager.GetString("IDS_OPT_DealerHitSoft17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Bank.
        /// </summary>
        public static string IDS_OPT_InitialBank {
            get {
                return ResourceManager.GetString("IDS_OPT_InitialBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Decks.
        /// </summary>
        public static string IDS_OPT_NumDecks {
            get {
                return ResourceManager.GetString("IDS_OPT_NumDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dealer Card.
        /// </summary>
        public static string IDS_OPT_ShowDealerCard {
            get {
                return ResourceManager.GetString("IDS_OPT_ShowDealerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scores.
        /// </summary>
        public static string IDS_OPT_ShowScores {
            get {
                return ResourceManager.GetString("IDS_OPT_ShowScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack!.
        /// </summary>
        public static string IDS_RESULT_Blackjack {
            get {
                return ResourceManager.GetString("IDS_RESULT_Blackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Busts - Win!.
        /// </summary>
        public static string IDS_RESULT_DealerBusts {
            get {
                return ResourceManager.GetString("IDS_RESULT_DealerBusts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string IDS_RESULT_Draw {
            get {
                return ResourceManager.GetString("IDS_RESULT_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose.
        /// </summary>
        public static string IDS_RESULT_Lose {
            get {
                return ResourceManager.GetString("IDS_RESULT_Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender.
        /// </summary>
        public static string IDS_RESULT_Surrender {
            get {
                return ResourceManager.GetString("IDS_RESULT_Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string IDS_RESULT_Win {
            get {
                return ResourceManager.GetString("IDS_RESULT_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win!.
        /// </summary>
        public static string IDS_RESULT_Win2 {
            get {
                return ResourceManager.GetString("IDS_RESULT_Win2", resourceCulture);
            }
        }
    }
}
