//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable_du {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable_du() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackJack.Strings.StringTable.du", typeof(StringTable_du).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.4.0\r\nAuteursrechten 2008-2013\r\n\r\n Panoramic Software Inc.\r\nwww.panoramicsoft.com.
        /// </summary>
        internal static string IDS_ABOUT_1 {
            get {
                return ResourceManager.GetString("IDS_ABOUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paar 8s tweemaal in een spel.
        /// </summary>
        internal static string IDS_ACH1_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik Haat 8s.
        /// </summary>
        internal static string IDS_ACH1_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH1_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer bustes 5 keer op een rij.
        /// </summary>
        internal static string IDS_ACH10_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH10_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Up.
        /// </summary>
        internal static string IDS_ACH10_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH10_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winnen 10 handen in een rij op kaarten tellen.
        /// </summary>
        internal static string IDS_ACH11_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH11_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopende Telling.
        /// </summary>
        internal static string IDS_ACH11_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH11_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max inzet op een hoog count.
        /// </summary>
        internal static string IDS_ACH12_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH12_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Roller.
        /// </summary>
        internal static string IDS_ACH12_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH12_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit op 18.
        /// </summary>
        internal static string IDS_ACH13_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH13_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Gokker.
        /// </summary>
        internal static string IDS_ACH13_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH13_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een verdubbeling op 12 of meer 5 keer in een spel en het winnen van elke hand.
        /// </summary>
        internal static string IDS_ACH14_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH14_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Trouble.
        /// </summary>
        internal static string IDS_ACH14_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH14_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-kaart 21 - alle 5 de maken hun opwachting.
        /// </summary>
        internal static string IDS_ACH2_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH2_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woooh.
        /// </summary>
        internal static string IDS_ACH2_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH2_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit blackjack 3 keer op een rij.
        /// </summary>
        internal static string IDS_ACH3_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH3_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Brand.
        /// </summary>
        internal static string IDS_ACH3_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH3_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 21 op beide split handen.
        /// </summary>
        internal static string IDS_ACH4_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH4_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Split.
        /// </summary>
        internal static string IDS_ACH4_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH4_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 25.000.
        /// </summary>
        internal static string IDS_ACH5_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH5_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25K!.
        /// </summary>
        internal static string IDS_ACH5_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH5_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 50.000.
        /// </summary>
        internal static string IDS_ACH6_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH6_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50K!.
        /// </summary>
        internal static string IDS_ACH6_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH6_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 75.000.
        /// </summary>
        internal static string IDS_ACH7_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH7_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75Gs.
        /// </summary>
        internal static string IDS_ACH7_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH7_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score 100.000.
        /// </summary>
        internal static string IDS_ACH8_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH8_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100K!.
        /// </summary>
        internal static string IDS_ACH8_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH8_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winnen de hand met 8 of meer kaarten.
        /// </summary>
        internal static string IDS_ACH9_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH9_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelukkig Pauze.
        /// </summary>
        internal static string IDS_ACH9_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH9_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panoramic Blackjack.
        /// </summary>
        internal static string IDS_APP_TITLE {
            get {
                return ResourceManager.GetString("IDS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blauw.
        /// </summary>
        internal static string IDS_BGCOLOR_BLUE {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groen.
        /// </summary>
        internal static string IDS_BGCOLOR_GREEN {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paars.
        /// </summary>
        internal static string IDS_BGCOLOR_PURPLE {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_PURPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rood.
        /// </summary>
        internal static string IDS_BGCOLOR_RED {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inzet.
        /// </summary>
        internal static string IDS_BTNS_Bet {
            get {
                return ResourceManager.GetString("IDS_BTNS_Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delen.
        /// </summary>
        internal static string IDS_BTNS_Deal {
            get {
                return ResourceManager.GetString("IDS_BTNS_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbel.
        /// </summary>
        internal static string IDS_BTNS_Double {
            get {
                return ResourceManager.GetString("IDS_BTNS_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaart.
        /// </summary>
        internal static string IDS_BTNS_Hit {
            get {
                return ResourceManager.GetString("IDS_BTNS_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzekeren.
        /// </summary>
        internal static string IDS_BTNS_Insurance {
            get {
                return ResourceManager.GetString("IDS_BTNS_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat.
        /// </summary>
        internal static string IDS_BTNS_Late {
            get {
                return ResourceManager.GetString("IDS_BTNS_Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herstel.
        /// </summary>
        internal static string IDS_BTNS_Reset {
            get {
                return ResourceManager.GetString("IDS_BTNS_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitsen.
        /// </summary>
        internal static string IDS_BTNS_Split {
            get {
                return ResourceManager.GetString("IDS_BTNS_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas.
        /// </summary>
        internal static string IDS_BTNS_Stand {
            get {
                return ResourceManager.GetString("IDS_BTNS_Stand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoog Laag.
        /// </summary>
        internal static string IDS_CMB_CC_HiLow {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoogOpt1.
        /// </summary>
        internal static string IDS_CMB_CC_HiOpt1 {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiOpt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoogOpt2.
        /// </summary>
        internal static string IDS_CMB_CC_HiOpt2 {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiOpt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KO.
        /// </summary>
        internal static string IDS_CMB_CC_KO {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega II.
        /// </summary>
        internal static string IDS_CMB_CC_OmegaII {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_OmegaII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string IDS_CMB_CC_Wizard {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zen.
        /// </summary>
        internal static string IDS_CMB_CC_Zen {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_Zen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uit.
        /// </summary>
        internal static string IDS_CMB_CCV_Off {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aan.
        /// </summary>
        internal static string IDS_CMB_CCV_On {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op Verzoek.
        /// </summary>
        internal static string IDS_CMB_CCV_Semi {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_Semi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangepast.
        /// </summary>
        internal static string IDS_CMB_GD_Custom {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeilijk.
        /// </summary>
        internal static string IDS_CMB_GD_Difficult {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makkelijk.
        /// </summary>
        internal static string IDS_CMB_GD_Easy {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leer Spelen.
        /// </summary>
        internal static string IDS_CMB_GD_Learn {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normaal.
        /// </summary>
        internal static string IDS_CMB_GD_Normal {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank: $%i.
        /// </summary>
        internal static string IDS_INFO_BankAmt {
            get {
                return ResourceManager.GetString("IDS_INFO_BankAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank: demo.
        /// </summary>
        internal static string IDS_INFO_BankDemo {
            get {
                return ResourceManager.GetString("IDS_INFO_BankDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inzet: $%i.
        /// </summary>
        internal static string IDS_INFO_BetAmt {
            get {
                return ResourceManager.GetString("IDS_INFO_BetAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inzet: demo.
        /// </summary>
        internal static string IDS_INFO_BetDemo {
            get {
                return ResourceManager.GetString("IDS_INFO_BetDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaart\r\nTellen.
        /// </summary>
        internal static string IDS_INFO_CardCount {
            get {
                return ResourceManager.GetString("IDS_INFO_CardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telling.
        /// </summary>
        internal static string IDS_INFO_Count {
            get {
                return ResourceManager.GetString("IDS_INFO_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement unlocked!.
        /// </summary>
        internal static string IDS_LBL_AchievementUnlock {
            get {
                return ResourceManager.GetString("IDS_LBL_AchievementUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string IDS_LBL_Bank {
            get {
                return ResourceManager.GetString("IDS_LBL_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaart Tellen Stijl.
        /// </summary>
        internal static string IDS_LBL_CardCounting {
            get {
                return ResourceManager.GetString("IDS_LBL_CardCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaart Tellen.
        /// </summary>
        internal static string IDS_LBL_CardCountView {
            get {
                return ResourceManager.GetString("IDS_LBL_CardCountView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string IDS_LBL_Date {
            get {
                return ResourceManager.GetString("IDS_LBL_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeilijkheidsgraad.
        /// </summary>
        internal static string IDS_LBL_GameDifficulty {
            get {
                return ResourceManager.GetString("IDS_LBL_GameDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal:.
        /// </summary>
        internal static string IDS_LBL_Language {
            get {
                return ResourceManager.GetString("IDS_LBL_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geluid.
        /// </summary>
        internal static string IDS_LBL_PlaySounds {
            get {
                return ResourceManager.GetString("IDS_LBL_PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        internal static string IDS_MENU_About {
            get {
                return ResourceManager.GetString("IDS_MENU_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string IDS_MENU_Achievements {
            get {
                return ResourceManager.GetString("IDS_MENU_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        internal static string IDS_MENU_Back {
            get {
                return ResourceManager.GetString("IDS_MENU_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        internal static string IDS_MENU_Cancel {
            get {
                return ResourceManager.GetString("IDS_MENU_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsluiten.
        /// </summary>
        internal static string IDS_MENU_Exit {
            get {
                return ResourceManager.GetString("IDS_MENU_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string IDS_MENU_Help {
            get {
                return ResourceManager.GetString("IDS_MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscores.
        /// </summary>
        internal static string IDS_MENU_HiScores {
            get {
                return ResourceManager.GetString("IDS_MENU_HiScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string IDS_MENU_Menu {
            get {
                return ResourceManager.GetString("IDS_MENU_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meer Apps.
        /// </summary>
        internal static string IDS_MENU_MoreApps {
            get {
                return ResourceManager.GetString("IDS_MENU_MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw spel.
        /// </summary>
        internal static string IDS_MENU_NewGame {
            get {
                return ResourceManager.GetString("IDS_MENU_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string IDS_MENU_No {
            get {
                return ResourceManager.GetString("IDS_MENU_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string IDS_MENU_Ok {
            get {
                return ResourceManager.GetString("IDS_MENU_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties.
        /// </summary>
        internal static string IDS_MENU_Options {
            get {
                return ResourceManager.GetString("IDS_MENU_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppen.
        /// </summary>
        internal static string IDS_MENU_Quit {
            get {
                return ResourceManager.GetString("IDS_MENU_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hervatten.
        /// </summary>
        internal static string IDS_MENU_Resume {
            get {
                return ResourceManager.GetString("IDS_MENU_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hervat spel.
        /// </summary>
        internal static string IDS_MENU_ResumeGame {
            get {
                return ResourceManager.GetString("IDS_MENU_ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string IDS_MENU_Save {
            get {
                return ResourceManager.GetString("IDS_MENU_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string IDS_MENU_Yes {
            get {
                return ResourceManager.GetString("IDS_MENU_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U bent blut! Nieuw spel starten?.
        /// </summary>
        internal static string IDS_MSG_Broke {
            get {
                return ResourceManager.GetString("IDS_MSG_Broke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij hopen dat u genoten heeft van Panoramic Blackjack. Uw probeerversie is verlopen. Om deze aan te schaffen verzoeken wij u de website te bezoeken waar u deze probeerversie gedownload heeft..
        /// </summary>
        internal static string IDS_MSG_DemoOver {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit Panoramic Blackjack? Weet u zeker dat u Panoramic Blackjack wilt verlaten?.
        /// </summary>
        internal static string IDS_MSG_Exit {
            get {
                return ResourceManager.GetString("IDS_MSG_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het spel is afgelopen, maar u heeft een nieuwe highscore behaald! Wilt u een nieuw spel starten?.
        /// </summary>
        internal static string IDS_MSG_HiEndGame {
            get {
                return ResourceManager.GetString("IDS_MSG_HiEndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u een nieuw spel wilt starten?.
        /// </summary>
        internal static string IDS_MSG_NewGame {
            get {
                return ResourceManager.GetString("IDS_MSG_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij hopen dat u genoten heeft van Panoramic Blackjack. Uw probeerversie is verlopen..
        /// </summary>
        internal static string IDS_MSG_TrialOverShort {
            get {
                return ResourceManager.GetString("IDS_MSG_TrialOverShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitbetaling Type.
        /// </summary>
        internal static string IDS_OPT_BJPayout {
            get {
                return ResourceManager.GetString("IDS_OPT_BJPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn eerste kaart.
        /// </summary>
        internal static string IDS_OPT_BurnFirst {
            get {
                return ResourceManager.GetString("IDS_OPT_BurnFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer hits op zachte 17.
        /// </summary>
        internal static string IDS_OPT_DealerHitSoft17 {
            get {
                return ResourceManager.GetString("IDS_OPT_DealerHitSoft17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Beginnen.
        /// </summary>
        internal static string IDS_OPT_InitialBank {
            get {
                return ResourceManager.GetString("IDS_OPT_InitialBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal Dekken.
        /// </summary>
        internal static string IDS_OPT_NumDecks {
            get {
                return ResourceManager.GetString("IDS_OPT_NumDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon Dealer Card.
        /// </summary>
        internal static string IDS_OPT_ShowDealerCard {
            get {
                return ResourceManager.GetString("IDS_OPT_ShowDealerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon scores.
        /// </summary>
        internal static string IDS_OPT_ShowScores {
            get {
                return ResourceManager.GetString("IDS_OPT_ShowScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack!.
        /// </summary>
        internal static string IDS_RESULT_Blackjack {
            get {
                return ResourceManager.GetString("IDS_RESULT_Blackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Kapot – Gewonnen!.
        /// </summary>
        internal static string IDS_RESULT_DealerBusts {
            get {
                return ResourceManager.GetString("IDS_RESULT_DealerBusts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaart.
        /// </summary>
        internal static string IDS_RESULT_Draw {
            get {
                return ResourceManager.GetString("IDS_RESULT_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verloren.
        /// </summary>
        internal static string IDS_RESULT_Lose {
            get {
                return ResourceManager.GetString("IDS_RESULT_Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgeven.
        /// </summary>
        internal static string IDS_RESULT_Surrender {
            get {
                return ResourceManager.GetString("IDS_RESULT_Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewonnen.
        /// </summary>
        internal static string IDS_RESULT_Win {
            get {
                return ResourceManager.GetString("IDS_RESULT_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewonnen!.
        /// </summary>
        internal static string IDS_RESULT_Win2 {
            get {
                return ResourceManager.GetString("IDS_RESULT_Win2", resourceCulture);
            }
        }
    }
}
