//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable_jp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackJack.Strings.StringTable.jp", typeof(StringTable_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パノラミック　ブラックジャック\r\nversion 1.4.0.1\r\nCopyright 2008-2013\r\n\r\nPanoramic Software Inc.\r\nwww.panoramicsoft.com.
        /// </summary>
        internal static string IDS_ABOUT_1 {
            get {
                return ResourceManager.GetString("IDS_ABOUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームで二度8のペア.
        /// </summary>
        internal static string IDS_ACH1_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私はやっぱ嫌い.
        /// </summary>
        internal static string IDS_ACH1_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH1_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディーラーの胸像連続で5回.
        /// </summary>
        internal static string IDS_ACH10_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH10_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旅行アップ.
        /// </summary>
        internal static string IDS_ACH10_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH10_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カード上の行に10勝手がカウント.
        /// </summary>
        internal static string IDS_ACH11_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH11_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runing数.
        /// </summary>
        internal static string IDS_ACH11_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH11_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高カウントの最大の賭け.
        /// </summary>
        internal static string IDS_ACH12_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH12_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハイローラー.
        /// </summary>
        internal static string IDS_ACH12_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH12_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18ヒット.
        /// </summary>
        internal static string IDS_ACH13_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH13_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギャンブラー.
        /// </summary>
        internal static string IDS_ACH13_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH13_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試合で12以上の5回に倍増させ、それぞれの手を獲得.
        /// </summary>
        internal static string IDS_ACH14_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH14_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブルトラブル.
        /// </summary>
        internal static string IDS_ACH14_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH14_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単一のデッキの試合で5カード21、全5さんが登場する.
        /// </summary>
        internal static string IDS_ACH2_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH2_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woooh.
        /// </summary>
        internal static string IDS_ACH2_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH2_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行のヒットブラックジャック3回.
        /// </summary>
        internal static string IDS_ACH3_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH3_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火災で.
        /// </summary>
        internal static string IDS_ACH3_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH3_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 両分割手にスコア21.
        /// </summary>
        internal static string IDS_ACH4_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH4_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スプリット.
        /// </summary>
        internal static string IDS_ACH4_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH4_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スコア25000.
        /// </summary>
        internal static string IDS_ACH5_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH5_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25,000！.
        /// </summary>
        internal static string IDS_ACH5_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH5_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スコア50000.
        /// </summary>
        internal static string IDS_ACH6_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH6_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5万！.
        /// </summary>
        internal static string IDS_ACH6_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH6_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スコア75000.
        /// </summary>
        internal static string IDS_ACH7_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH7_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75Gs.
        /// </summary>
        internal static string IDS_ACH7_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH7_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スコア100000.
        /// </summary>
        internal static string IDS_ACH8_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH8_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10万！.
        /// </summary>
        internal static string IDS_ACH8_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH8_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8以上のカードで勝利の手.
        /// </summary>
        internal static string IDS_ACH9_DESC {
            get {
                return ResourceManager.GetString("IDS_ACH9_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラッキーブレイク.
        /// </summary>
        internal static string IDS_ACH9_TITLE {
            get {
                return ResourceManager.GetString("IDS_ACH9_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パノラミック　ブラックジャック.
        /// </summary>
        internal static string IDS_APP_TITLE {
            get {
                return ResourceManager.GetString("IDS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青.
        /// </summary>
        internal static string IDS_BGCOLOR_BLUE {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緑.
        /// </summary>
        internal static string IDS_BGCOLOR_GREEN {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紫.
        /// </summary>
        internal static string IDS_BGCOLOR_PURPLE {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_PURPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤.
        /// </summary>
        internal static string IDS_BGCOLOR_RED {
            get {
                return ResourceManager.GetString("IDS_BGCOLOR_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベット.
        /// </summary>
        internal static string IDS_BTNS_Bet {
            get {
                return ResourceManager.GetString("IDS_BTNS_Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディール.
        /// </summary>
        internal static string IDS_BTNS_Deal {
            get {
                return ResourceManager.GetString("IDS_BTNS_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブル.
        /// </summary>
        internal static string IDS_BTNS_Double {
            get {
                return ResourceManager.GetString("IDS_BTNS_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒット.
        /// </summary>
        internal static string IDS_BTNS_Hit {
            get {
                return ResourceManager.GetString("IDS_BTNS_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保険.
        /// </summary>
        internal static string IDS_BTNS_Insurance {
            get {
                return ResourceManager.GetString("IDS_BTNS_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイト.
        /// </summary>
        internal static string IDS_BTNS_Late {
            get {
                return ResourceManager.GetString("IDS_BTNS_Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リセット.
        /// </summary>
        internal static string IDS_BTNS_Reset {
            get {
                return ResourceManager.GetString("IDS_BTNS_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スプリット.
        /// </summary>
        internal static string IDS_BTNS_Split {
            get {
                return ResourceManager.GetString("IDS_BTNS_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタンド.
        /// </summary>
        internal static string IDS_BTNS_Stand {
            get {
                return ResourceManager.GetString("IDS_BTNS_Stand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハイ　ロー.
        /// </summary>
        internal static string IDS_CMB_CC_HiLow {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハイオプト１.
        /// </summary>
        internal static string IDS_CMB_CC_HiOpt1 {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiOpt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハイオプト２.
        /// </summary>
        internal static string IDS_CMB_CC_HiOpt2 {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_HiOpt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KO.
        /// </summary>
        internal static string IDS_CMB_CC_KO {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オメガII.
        /// </summary>
        internal static string IDS_CMB_CC_OmegaII {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_OmegaII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィザード.
        /// </summary>
        internal static string IDS_CMB_CC_Wizard {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゼン.
        /// </summary>
        internal static string IDS_CMB_CC_Zen {
            get {
                return ResourceManager.GetString("IDS_CMB_CC_Zen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string IDS_CMB_CCV_Off {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始.
        /// </summary>
        internal static string IDS_CMB_CCV_On {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オンデマンド.
        /// </summary>
        internal static string IDS_CMB_CCV_Semi {
            get {
                return ResourceManager.GetString("IDS_CMB_CCV_Semi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カスタム.
        /// </summary>
        internal static string IDS_CMB_GD_Custom {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to むずかしい.
        /// </summary>
        internal static string IDS_CMB_GD_Difficult {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やさしい.
        /// </summary>
        internal static string IDS_CMB_GD_Easy {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遊び方を知る.
        /// </summary>
        internal static string IDS_CMB_GD_Learn {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふつう.
        /// </summary>
        internal static string IDS_CMB_GD_Normal {
            get {
                return ResourceManager.GetString("IDS_CMB_GD_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀行: $%i.
        /// </summary>
        internal static string IDS_INFO_BankAmt {
            get {
                return ResourceManager.GetString("IDS_INFO_BankAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀行: デモ.
        /// </summary>
        internal static string IDS_INFO_BankDemo {
            get {
                return ResourceManager.GetString("IDS_INFO_BankDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベット: $%i.
        /// </summary>
        internal static string IDS_INFO_BetAmt {
            get {
                return ResourceManager.GetString("IDS_INFO_BetAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベット: デモ.
        /// </summary>
        internal static string IDS_INFO_BetDemo {
            get {
                return ResourceManager.GetString("IDS_INFO_BetDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カード\r\nカウント.
        /// </summary>
        internal static string IDS_INFO_CardCount {
            get {
                return ResourceManager.GetString("IDS_INFO_CardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カウント.
        /// </summary>
        internal static string IDS_INFO_Count {
            get {
                return ResourceManager.GetString("IDS_INFO_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実績のロックが解除！.
        /// </summary>
        internal static string IDS_LBL_AchievementUnlock {
            get {
                return ResourceManager.GetString("IDS_LBL_AchievementUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀行.
        /// </summary>
        internal static string IDS_LBL_Bank {
            get {
                return ResourceManager.GetString("IDS_LBL_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カードの計算スタイル.
        /// </summary>
        internal static string IDS_LBL_CardCounting {
            get {
                return ResourceManager.GetString("IDS_LBL_CardCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カードの計算.
        /// </summary>
        internal static string IDS_LBL_CardCountView {
            get {
                return ResourceManager.GetString("IDS_LBL_CardCountView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付.
        /// </summary>
        internal static string IDS_LBL_Date {
            get {
                return ResourceManager.GetString("IDS_LBL_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームの難易度.
        /// </summary>
        internal static string IDS_LBL_GameDifficulty {
            get {
                return ResourceManager.GetString("IDS_LBL_GameDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語:.
        /// </summary>
        internal static string IDS_LBL_Language {
            get {
                return ResourceManager.GetString("IDS_LBL_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム中の音.
        /// </summary>
        internal static string IDS_LBL_PlaySounds {
            get {
                return ResourceManager.GetString("IDS_LBL_PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本ソフトに関して.
        /// </summary>
        internal static string IDS_MENU_About {
            get {
                return ResourceManager.GetString("IDS_MENU_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実績.
        /// </summary>
        internal static string IDS_MENU_Achievements {
            get {
                return ResourceManager.GetString("IDS_MENU_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to もどる.
        /// </summary>
        internal static string IDS_MENU_Back {
            get {
                return ResourceManager.GetString("IDS_MENU_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string IDS_MENU_Cancel {
            get {
                return ResourceManager.GetString("IDS_MENU_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string IDS_MENU_Exit {
            get {
                return ResourceManager.GetString("IDS_MENU_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        internal static string IDS_MENU_Help {
            get {
                return ResourceManager.GetString("IDS_MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハイスコア.
        /// </summary>
        internal static string IDS_MENU_HiScores {
            get {
                return ResourceManager.GetString("IDS_MENU_HiScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メニュー.
        /// </summary>
        internal static string IDS_MENU_Menu {
            get {
                return ResourceManager.GetString("IDS_MENU_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のアプリを見る.
        /// </summary>
        internal static string IDS_MENU_MoreApps {
            get {
                return ResourceManager.GetString("IDS_MENU_MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規開始.
        /// </summary>
        internal static string IDS_MENU_NewGame {
            get {
                return ResourceManager.GetString("IDS_MENU_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いいえ.
        /// </summary>
        internal static string IDS_MENU_No {
            get {
                return ResourceManager.GetString("IDS_MENU_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_MENU_Ok {
            get {
                return ResourceManager.GetString("IDS_MENU_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オプション.
        /// </summary>
        internal static string IDS_MENU_Options {
            get {
                return ResourceManager.GetString("IDS_MENU_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やめる.
        /// </summary>
        internal static string IDS_MENU_Quit {
            get {
                return ResourceManager.GetString("IDS_MENU_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再開.
        /// </summary>
        internal static string IDS_MENU_Resume {
            get {
                return ResourceManager.GetString("IDS_MENU_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームを再開する.
        /// </summary>
        internal static string IDS_MENU_ResumeGame {
            get {
                return ResourceManager.GetString("IDS_MENU_ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string IDS_MENU_Save {
            get {
                return ResourceManager.GetString("IDS_MENU_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to はい.
        /// </summary>
        internal static string IDS_MENU_Yes {
            get {
                return ResourceManager.GetString("IDS_MENU_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたの負けです。新しくゲームを始めますか？.
        /// </summary>
        internal static string IDS_MSG_Broke {
            get {
                return ResourceManager.GetString("IDS_MSG_Broke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パノラミック ブラックジャックをお楽しみ頂きましてありがとうございます。お試し期間が終了しました。もし購入される場合は試行版をダウンロードされたWebサイトにお戻りください.
        /// </summary>
        internal static string IDS_MSG_DemoOver {
            get {
                return ResourceManager.GetString("IDS_MSG_DemoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パノラミック ブラックジャックを終わりますか？.
        /// </summary>
        internal static string IDS_MSG_Exit {
            get {
                return ResourceManager.GetString("IDS_MSG_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームは終わり、ハイスコアです。新しくゲームを始めますか？.
        /// </summary>
        internal static string IDS_MSG_HiEndGame {
            get {
                return ResourceManager.GetString("IDS_MSG_HiEndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しくゲームを始めますか？.
        /// </summary>
        internal static string IDS_MSG_NewGame {
            get {
                return ResourceManager.GetString("IDS_MSG_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お試し期間が終了しました。.
        /// </summary>
        internal static string IDS_MSG_TrialOverShort {
            get {
                return ResourceManager.GetString("IDS_MSG_TrialOverShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お支払いの種類.
        /// </summary>
        internal static string IDS_OPT_BJPayout {
            get {
                return ResourceManager.GetString("IDS_OPT_BJPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最初のカードをバーン.
        /// </summary>
        internal static string IDS_OPT_BurnFirst {
            get {
                return ResourceManager.GetString("IDS_OPT_BurnFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディーラーはソフト17でヒット.
        /// </summary>
        internal static string IDS_OPT_DealerHitSoft17 {
            get {
                return ResourceManager.GetString("IDS_OPT_DealerHitSoft17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀行を開始.
        /// </summary>
        internal static string IDS_OPT_InitialBank {
            get {
                return ResourceManager.GetString("IDS_OPT_InitialBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デッキ数.
        /// </summary>
        internal static string IDS_OPT_NumDecks {
            get {
                return ResourceManager.GetString("IDS_OPT_NumDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地図ディーラーカード.
        /// </summary>
        internal static string IDS_OPT_ShowDealerCard {
            get {
                return ResourceManager.GetString("IDS_OPT_ShowDealerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示スコア.
        /// </summary>
        internal static string IDS_OPT_ShowScores {
            get {
                return ResourceManager.GetString("IDS_OPT_ShowScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラックジャック!.
        /// </summary>
        internal static string IDS_RESULT_Blackjack {
            get {
                return ResourceManager.GetString("IDS_RESULT_Blackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディーラーのバースト - 勝ち!.
        /// </summary>
        internal static string IDS_RESULT_DealerBusts {
            get {
                return ResourceManager.GetString("IDS_RESULT_DealerBusts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引き分け.
        /// </summary>
        internal static string IDS_RESULT_Draw {
            get {
                return ResourceManager.GetString("IDS_RESULT_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 負け.
        /// </summary>
        internal static string IDS_RESULT_Lose {
            get {
                return ResourceManager.GetString("IDS_RESULT_Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 降参.
        /// </summary>
        internal static string IDS_RESULT_Surrender {
            get {
                return ResourceManager.GetString("IDS_RESULT_Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勝ち.
        /// </summary>
        internal static string IDS_RESULT_Win {
            get {
                return ResourceManager.GetString("IDS_RESULT_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勝ち！.
        /// </summary>
        internal static string IDS_RESULT_Win2 {
            get {
                return ResourceManager.GetString("IDS_RESULT_Win2", resourceCulture);
            }
        }
    }
}
