//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Strings.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.4.0\r\nCopyright 2009-2011\r\n\r\n Panoramic Software Inc.\r\nwww.panoramicsoft.com.
        /// </summary>
        public static string IDS_ABOUT_1 {
            get {
                return ResourceManager.GetString("IDS_ABOUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoyed playing Panoramic Ultimate Sudoku, your trial has now expired.\r\n\r\nTo purchase: please return to the website that provided your trial download..
        /// </summary>
        public static string IDS_DEMO_Over {
            get {
                return ResourceManager.GetString("IDS_DEMO_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        public static string IDS_Greater {
            get {
                return ResourceManager.GetString("IDS_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kakuro.
        /// </summary>
        public static string IDS_Kakuro {
            get {
                return ResourceManager.GetString("IDS_Kakuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KenKen.
        /// </summary>
        public static string IDS_KenKen {
            get {
                return ResourceManager.GetString("IDS_KenKen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killer Sudoku.
        /// </summary>
        public static string IDS_KillerSudoku {
            get {
                return ResourceManager.GetString("IDS_KillerSudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over\r\nWould you like to\r\n start a new Game?.
        /// </summary>
        public static string IDS_LOSE {
            get {
                return ResourceManager.GetString("IDS_LOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Lose.
        /// </summary>
        public static string IDS_LOSE_IT {
            get {
                return ResourceManager.GetString("IDS_LOSE_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SudokuClass.
        /// </summary>
        public static string IDS_MAIN_CLASS {
            get {
                return ResourceManager.GetString("IDS_MAIN_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string IDS_MENU_About {
            get {
                return ResourceManager.GetString("IDS_MENU_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto pencil marks.
        /// </summary>
        public static string IDS_MENU_AutoPencil {
            get {
                return ResourceManager.GetString("IDS_MENU_AutoPencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        public static string IDS_MENU_Avg {
            get {
                return ResourceManager.GetString("IDS_MENU_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string IDS_MENU_Back {
            get {
                return ResourceManager.GetString("IDS_MENU_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string IDS_MENU_Camera {
            get {
                return ResourceManager.GetString("IDS_MENU_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string IDS_MENU_Cancel {
            get {
                return ResourceManager.GetString("IDS_MENU_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear pencil marks.
        /// </summary>
        public static string IDS_MENU_ClearPencil {
            get {
                return ResourceManager.GetString("IDS_MENU_ClearPencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string IDS_MENU_Exit {
            get {
                return ResourceManager.GetString("IDS_MENU_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string IDS_MENU_Free {
            get {
                return ResourceManager.GetString("IDS_MENU_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string IDS_MENU_Game {
            get {
                return ResourceManager.GetString("IDS_MENU_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string IDS_MENU_Help {
            get {
                return ResourceManager.GetString("IDS_MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string IDS_MENU_Hint {
            get {
                return ResourceManager.GetString("IDS_MENU_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string IDS_MENU_Image {
            get {
                return ResourceManager.GetString("IDS_MENU_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string IDS_MENU_Menu {
            get {
                return ResourceManager.GetString("IDS_MENU_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Apps.
        /// </summary>
        public static string IDS_MENU_MoreApps {
            get {
                return ResourceManager.GetString("IDS_MENU_MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string IDS_MENU_NewGame {
            get {
                return ResourceManager.GetString("IDS_MENU_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string IDS_MENU_No {
            get {
                return ResourceManager.GetString("IDS_MENU_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string IDS_MENU_Ok {
            get {
                return ResourceManager.GetString("IDS_MENU_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string IDS_MENU_Options {
            get {
                return ResourceManager.GetString("IDS_MENU_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        public static string IDS_MENU_Pen {
            get {
                return ResourceManager.GetString("IDS_MENU_Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencil.
        /// </summary>
        public static string IDS_MENU_Pencil {
            get {
                return ResourceManager.GetString("IDS_MENU_Pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string IDS_MENU_Picture {
            get {
                return ResourceManager.GetString("IDS_MENU_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string IDS_MENU_Quit {
            get {
                return ResourceManager.GetString("IDS_MENU_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string IDS_MENU_Reset {
            get {
                return ResourceManager.GetString("IDS_MENU_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Game.
        /// </summary>
        public static string IDS_MENU_RestartGame {
            get {
                return ResourceManager.GetString("IDS_MENU_RestartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string IDS_MENU_Resume {
            get {
                return ResourceManager.GetString("IDS_MENU_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string IDS_MENU_Save {
            get {
                return ResourceManager.GetString("IDS_MENU_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Game.
        /// </summary>
        public static string IDS_MENU_SelectGame {
            get {
                return ResourceManager.GetString("IDS_MENU_SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        public static string IDS_MENU_Solve {
            get {
                return ResourceManager.GetString("IDS_MENU_Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string IDS_MENU_Stats {
            get {
                return ResourceManager.GetString("IDS_MENU_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string IDS_MENU_Total {
            get {
                return ResourceManager.GetString("IDS_MENU_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string IDS_MENU_Undo {
            get {
                return ResourceManager.GetString("IDS_MENU_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string IDS_MENU_Yes {
            get {
                return ResourceManager.GetString("IDS_MENU_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all statistics?.
        /// </summary>
        public static string IDS_MSG_ClearStatistics {
            get {
                return ResourceManager.GetString("IDS_MSG_ClearStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You completed the {0} {1} puzzle in {2}. Would you like to play a new game?.
        /// </summary>
        public static string IDS_MSG_Congrats {
            get {
                return ResourceManager.GetString("IDS_MSG_Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit Panoramic Ultimate Sudoku?.
        /// </summary>
        public static string IDS_MSG_Exit {
            get {
                return ResourceManager.GetString("IDS_MSG_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string IDS_MSG_Loading {
            get {
                return ResourceManager.GetString("IDS_MSG_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start a new game?.
        /// </summary>
        public static string IDS_MSG_NewGame {
            get {
                return ResourceManager.GetString("IDS_MSG_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play a new game?.
        /// </summary>
        public static string IDS_MSG_NewGame2 {
            get {
                return ResourceManager.GetString("IDS_MSG_NewGame2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart this game?.
        /// </summary>
        public static string IDS_MSG_RestartGame {
            get {
                return ResourceManager.GetString("IDS_MSG_RestartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string IDS_MSG_Trial {
            get {
                return ResourceManager.GetString("IDS_MSG_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate Sudoku.
        /// </summary>
        public static string IDS_NAME_Sudoku {
            get {
                return ResourceManager.GetString("IDS_NAME_Sudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5x5.
        /// </summary>
        public static string IDS_PREF_5x5 {
            get {
                return ResourceManager.GetString("IDS_PREF_5x5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7x7.
        /// </summary>
        public static string IDS_PREF_7x7 {
            get {
                return ResourceManager.GetString("IDS_PREF_7x7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9x9.
        /// </summary>
        public static string IDS_PREF_9x9 {
            get {
                return ResourceManager.GetString("IDS_PREF_9x9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-clear pencilmarks.
        /// </summary>
        public static string IDS_PREF_AutoClear {
            get {
                return ResourceManager.GetString("IDS_PREF_AutoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        public static string IDS_PREF_Background {
            get {
                return ResourceManager.GetString("IDS_PREF_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string IDS_PREF_Black {
            get {
                return ResourceManager.GetString("IDS_PREF_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black-White.
        /// </summary>
        public static string IDS_PREF_BlackWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string IDS_PREF_Blue {
            get {
                return ResourceManager.GetString("IDS_PREF_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue-Black.
        /// </summary>
        public static string IDS_PREF_BlueBlack {
            get {
                return ResourceManager.GetString("IDS_PREF_BlueBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue-Green.
        /// </summary>
        public static string IDS_PREF_BlueGreen {
            get {
                return ResourceManager.GetString("IDS_PREF_BlueGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue-White.
        /// </summary>
        public static string IDS_PREF_BlueWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_BlueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 1.
        /// </summary>
        public static string IDS_PREF_Cust1 {
            get {
                return ResourceManager.GetString("IDS_PREF_Cust1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 2.
        /// </summary>
        public static string IDS_PREF_Cust2 {
            get {
                return ResourceManager.GetString("IDS_PREF_Cust2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 3.
        /// </summary>
        public static string IDS_PREF_Cust3 {
            get {
                return ResourceManager.GetString("IDS_PREF_Cust3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 4.
        /// </summary>
        public static string IDS_PREF_Cust4 {
            get {
                return ResourceManager.GetString("IDS_PREF_Cust4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 5.
        /// </summary>
        public static string IDS_PREF_Cust5 {
            get {
                return ResourceManager.GetString("IDS_PREF_Cust5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 6.
        /// </summary>
        public static string IDS_PREF_Cust6 {
            get {
                return ResourceManager.GetString("IDS_PREF_Cust6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Image.
        /// </summary>
        public static string IDS_PREF_CustImage {
            get {
                return ResourceManager.GetString("IDS_PREF_CustImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string IDS_PREF_Custom {
            get {
                return ResourceManager.GetString("IDS_PREF_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (white).
        /// </summary>
        public static string IDS_PREF_DefWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_DefWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        public static string IDS_PREF_DkBlue {
            get {
                return ResourceManager.GetString("IDS_PREF_DkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue-Blue.
        /// </summary>
        public static string IDS_PREF_DkBlueBlue {
            get {
                return ResourceManager.GetString("IDS_PREF_DkBlueBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue-White.
        /// </summary>
        public static string IDS_PREF_DkBlueWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_DkBlueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Green.
        /// </summary>
        public static string IDS_PREF_DkGreen {
            get {
                return ResourceManager.GetString("IDS_PREF_DkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Green-Green.
        /// </summary>
        public static string IDS_PREF_DkGreenGreen {
            get {
                return ResourceManager.GetString("IDS_PREF_DkGreenGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw blank cells (Kakuro).
        /// </summary>
        public static string IDS_PREF_DrawCells {
            get {
                return ResourceManager.GetString("IDS_PREF_DrawCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string IDS_PREF_Easy {
            get {
                return ResourceManager.GetString("IDS_PREF_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string IDS_PREF_Expert {
            get {
                return ResourceManager.GetString("IDS_PREF_Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genius.
        /// </summary>
        public static string IDS_PREF_Genius {
            get {
                return ResourceManager.GetString("IDS_PREF_Genius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        public static string IDS_PREF_Glass {
            get {
                return ResourceManager.GetString("IDS_PREF_Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string IDS_PREF_Green {
            get {
                return ResourceManager.GetString("IDS_PREF_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green-Black.
        /// </summary>
        public static string IDS_PREF_GreenBlack {
            get {
                return ResourceManager.GetString("IDS_PREF_GreenBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green-White.
        /// </summary>
        public static string IDS_PREF_GreenWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_GreenWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        public static string IDS_PREF_Grey {
            get {
                return ResourceManager.GetString("IDS_PREF_Grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey-Black.
        /// </summary>
        public static string IDS_PREF_GreyBlack {
            get {
                return ResourceManager.GetString("IDS_PREF_GreyBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string IDS_PREF_Hard {
            get {
                return ResourceManager.GetString("IDS_PREF_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock completed.
        /// </summary>
        public static string IDS_PREF_LockCompleted {
            get {
                return ResourceManager.GetString("IDS_PREF_LockCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Pink.
        /// </summary>
        public static string IDS_PREF_LtPink {
            get {
                return ResourceManager.GetString("IDS_PREF_LtPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string IDS_PREF_Normal {
            get {
                return ResourceManager.GetString("IDS_PREF_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad.
        /// </summary>
        public static string IDS_PREF_Notepad {
            get {
                return ResourceManager.GetString("IDS_PREF_Notepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string IDS_PREF_Orange {
            get {
                return ResourceManager.GetString("IDS_PREF_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange-White.
        /// </summary>
        public static string IDS_PREF_OrangeWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_OrangeWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string IDS_PREF_Pink {
            get {
                return ResourceManager.GetString("IDS_PREF_Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink-White.
        /// </summary>
        public static string IDS_PREF_PinkWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_PinkWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sounds.
        /// </summary>
        public static string IDS_PREF_PlaySounds {
            get {
                return ResourceManager.GetString("IDS_PREF_PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string IDS_PREF_Purple {
            get {
                return ResourceManager.GetString("IDS_PREF_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple-Black.
        /// </summary>
        public static string IDS_PREF_PurpleBlack {
            get {
                return ResourceManager.GetString("IDS_PREF_PurpleBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple-White.
        /// </summary>
        public static string IDS_PREF_PurpleWhite {
            get {
                return ResourceManager.GetString("IDS_PREF_PurpleWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red-Black.
        /// </summary>
        public static string IDS_PREF_RedBlack {
            get {
                return ResourceManager.GetString("IDS_PREF_RedBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors.
        /// </summary>
        public static string IDS_PREF_ShowErrors {
            get {
                return ResourceManager.GetString("IDS_PREF_ShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show highlights.
        /// </summary>
        public static string IDS_PREF_ShowHighlights {
            get {
                return ResourceManager.GetString("IDS_PREF_ShowHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hints.
        /// </summary>
        public static string IDS_PREF_ShowHints {
            get {
                return ResourceManager.GetString("IDS_PREF_ShowHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string IDS_PREF_Skin {
            get {
                return ResourceManager.GetString("IDS_PREF_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Easy.
        /// </summary>
        public static string IDS_PREF_VeryEasy {
            get {
                return ResourceManager.GetString("IDS_PREF_VeryEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string IDS_PREF_White {
            get {
                return ResourceManager.GetString("IDS_PREF_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string IDS_PREF_Wood {
            get {
                return ResourceManager.GetString("IDS_PREF_Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku.
        /// </summary>
        public static string IDS_Sudoku {
            get {
                return ResourceManager.GetString("IDS_Sudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string IDS_TOOLS {
            get {
                return ResourceManager.GetString("IDS_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.panoramicsoft.com.
        /// </summary>
        public static string IDS_WEBSITE {
            get {
                return ResourceManager.GetString("IDS_WEBSITE", resourceCulture);
            }
        }
    }
}
