//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Contactsppc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_Contacts                    2
#define IDS_MENU_SetContactPicture      3
#define IDS_MENU_SetContactCamera       4
#define IDS_MENU_SetContactRingtone     5
#define IDS_Yes                         6
#define IDS_STRING7                     7
#define IDS_No                          7
#define IDI_Contacts                    101
#define IDS_MENU_Quit                   102
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_MENU_Unlock                 105
#define IDS_MENU_Ok                     106
#define IDS_MENU_Cancel                 107
#define IDS_MENU_AddItem                108
#define IDS_MENU_RemoveItem             109
#define IDS_MENU_EditContact            110
#define IDS_MENU_NewContact             111
#define IDS_MENU_DeleteContact          112
#define IDS_MENU_SmartArrange           113
#define IDS_MENU_LockItems              114
#define IDS_TOOLBAR_FAV                 115
#define IDS_TOOLBAR_CONTACTS            116
#define IDS_TOOLBAR_HISTORY             117
#define IDS_TOOLBAR_EXIT                118
#define IDS_SLIDER_Personal             119
#define IDS_SLIDER_Business             120
#define IDR_PNG_ToolbarSelector_p       130
#define IDR_PNG_ToolbarSelector_l       131
#define IDR_PNG_ToolbarSelectorVGA_p    132
#define IDR_PNG_ToolbarSelectorVGA_l    133
#define IDR_PNG_ToolbarIconArray        134
#define IDR_PNG_ToolbarIconArrayVGA     135
#define IDR_PNG_Glow                    136
#define IDR_PNG_GlowVGA                 137
#define IDR_PNG_FavoritesArrowArray     138
#define IDR_PNG_FavoritesArrowArrayVGA  139
#define IDR_PNG_FavoritesAdd            141
#define IDR_PNG_FavoritesImgAlpha       142
#define IDR_PNG_FavoritesImgBorder      143
#define IDR_PNG_FavoritesImgBorderVGA   144
#define IDR_PNG_FavoritesImgDefault     145
#define IDR_PNG_FavoritesImgSelect      146
#define IDR_PNG_FavoritesImgShadow      147
#define IDR_PNG_FavoritesNameBbl        148
#define IDR_PNG_FavoritesGrid           149
#define IDR_PNG_FavoritesSlider         150
#define IDR_PNG_FavoritesSliderLan      151
#define IDR_PNG_DetailsBackGreenVGA     152
#define IDR_PNG_FavoritesSliderBg       153
#define IDR_PNG_FavoritesSliderBgLan    154
#define IDR_PNG_DetailsBackGreen        155
#define IDR_PNG_DetailsBtnGreen         156
#define IDR_PNG_DetailsBtn              157
#define IDR_PNG_DetailsDefault          158
#define IDR_PNG_DetailsDefaultVGA       159
#define IDR_PNG_ContactsBorder          160
#define IDR_PNG_ContactsBorderVGA       161
#define IDR_PNG_ContactsSelector        162
#define IDR_PNG_ContactsLetterBubble    170
#define IDR_PNG_ContactsLetterBubbleVGA 171
#define IDR_PNG_Font                    173
#define IDR_PNG_FontVGA                 174
#define IDR_PNG_Group                   175
#define IDR_PNG_MenuArray               176
#define IDR_PNG_MenuArrayVGA            177
#define IDR_PNG_Selector                178
#define IDR_MENU_Unlock                 179
#define IDR_MENU_OkCancel               180
#define IDR_PNG_B_Arrow_LanVGA          180
#define IDD_DIALOG1                     181
#define IDD_DIALOG2                     182
#define IDD_DLG_Basic                   183
#define IDD_DLG_Add                     184
#define IDI_ICO_Contacts                185
#define IDI_ICO_Favorites               186
#define IDI_ICO_History                 187
#define IDI_ICO_Folder                  188
#define IDS_MENU_Conversation           190
#define IDS_MENU_Options                191
#define IDR_PNG_B_MenuArray             192
#define IDS_MENU_Help                   193
#define IDR_PNG_B_MenuArrayVGA          193
#define IDS_MENU_About                  194
#define IDR_PNG_O_MenuArray             194
#define IDR_PNG_O_MenuArrayVGA          195
#define IDR_PNG_PI_MenuArray            196
#define IDR_PNG_PI_MenuArrayVGA         197
#define IDR_PNG_P_MenuArray             198
#define IDR_PNG_P_MenuArrayVGA          199
#define IDR_PNG_R_MenuArray             200
#define IDR_PNG_R_MenuArrayVGA          201
#define IDR_PNG_B_Selector              202
#define IDR_PNG_O_Selector              203
#define IDR_PNG_PI_Selector             204
#define IDR_PNG_P_Selector              205
#define IDR_GIF2                        206
#define IDR_PNG_R_Selector              206
#define IDR_PNG_B_DetailsBtnGreenVGA    207
#define IDR_PNG_B_DetailsBackGreen      208
#define IDR_PNG_B_DetailsBackGreenVGA   209
#define IDR_PNG_B_DetailsBtnGreen       210
#define IDR_PNG_O_DetailsBtnGreenVGA    211
#define IDR_PNG_O_DetailsBtnGreen       212
#define IDR_PNG_O_DetailsBackGreen      213
#define IDR_PNG_O_DetailsBackGreenVGA   214
#define IDR_PNG_PI_DetailsBackGreen     215
#define IDR_PNG_PI_DetailsBackGreenVGA  216
#define IDR_PNG_PI_DetailsBtnGreen      217
#define IDR_PNG_PI_DetailsBtnGreenVGA   218
#define IDR_PNG_P_DetailsBackGreen      219
#define IDR_PNG_P_DetailsBackGreenVGA   220
#define IDR_PNG_P_DetailsBtnGreen       221
#define IDR_PNG_P_DetailsBtnGreenVGA    222
#define IDR_PNG_R_DetailsBtnGreenVGA    223
#define IDR_PNG_R_DetailsBackGreenVGA   224
#define IDR_PNG_R_DetailsBackGreen      225
#define IDR_PNG_R_DetailsBtnGreen       226
#define IDR_PNG_DetailsBtnGreenVGA      227
#define IDR_PNG_B_FavSelectVGA          228
#define IDR_PNG_B_Glow                  229
#define IDR_PNG_B_GlowVGA               230
#define IDR_PNG_B_FavSelect             231
#define IDR_PNG_O_Glow                  232
#define IDR_PNG_O_GlowVGA               233
#define IDR_PNG_O_FavSelect             234
#define IDR_PNG_O_FavSelectVGA          235
#define IDR_PNG_PI_Glow                 238
#define IDR_PNG_PI_GlowVGA              239
#define IDR_PNG_PI_FavSelect            240
#define IDR_PNG_PI_FavSelectVGA         241
#define IDR_PNG_P_Glow                  242
#define IDR_PNG_P_GlowVGA               243
#define IDR_PNG_P_FavSelect             244
#define IDR_PNG_P_FavSelectVGA          245
#define IDR_PNG_R_Glow                  246
#define IDR_PNG_R_GlowVGA               247
#define IDR_PNG_R_FavSelect             248
#define IDR_PNG_R_FavSelectVGA          249
#define IDR_PNG_B_Arrow                 250
#define IDR_PNG_B_Arrow_Lan             251
#define IDR_PNG_B_ArrowVGA              252
#define IDR_PNG_Arrow_LanVGA            254
#define IDR_PNG_Arrow                   255
#define IDR_PNG_Arrow_Lan               256
#define IDR_PNG_ArrowVGA                257
#define IDR_PNG_O_Arrow_LanVGA          258
#define IDR_PNG_O_Arrow                 259
#define IDR_PNG_O_Arrow_Lan             260
#define IDR_PNG_O_ArrowVGA              261
#define IDR_PNG_PI_ArrowVGA             262
#define IDR_PNG_PI_Arrow_LanVGA         263
#define IDR_PNG_PI_Arrow                264
#define IDR_PNG_PI_Arrow_Lan            265
#define IDR_PNG_P_Arrow_LanVGA          266
#define IDR_PNG_P_Arrow                 267
#define IDR_PNG_P_Arrow_Lan             268
#define IDR_PNG_P_ArrowVGA              269
#define IDR_PNG_R_ArrowVGA              270
#define IDR_PNG_R_Arrow_LanVGA          271
#define IDR_PNG_R_Arrow                 272
#define IDR_PNG_R_Arrow_Lan             273
#define IDR_GIF1                        274
#define IDR_PNG_DetailsBtnVGA           274
#define IDR_GIF3                        275
#define IDR_PNG_CallBg                  275
#define IDR_PNG_CallBgVGA               276
#define IDR_GIF4                        277
#define IDR_PNG_HistoryArrow            277
#define IDR_PNG_HistoryArrowVGA         278
#define IDR_PNG_FavoritesGridVGA        300
#define IDR_PNG_FavoritesSliderVGA      301
#define IDR_PNG_FavoritesSliderLanVGA   302
#define IDR_PNG_FavoritesSliderBgVGA    303
#define IDR_PNG_FavoritesSliderBgLanVGA 304
#define IDR_PNG_FavoritesNameBblVGA     305
#define IDR_PNG_FavoritesImgSelectVGA   306
#define IDR_PNG_FavoritesAddVGA         307
#define IDR_PNG_FavoritesImgAlphaVGA    308
#define IDR_PNG_FavoritesImgDefaultVGA  309
#define IDR_PNG_FavoritesImgShadowVGA   310
#define IDR_PNG_HistoryArray            311
#define IDR_PNG_HistoryArrayVGA         312
#define IDMENU_Quit                     32762
#define IDMENU_SmartArrange             32763
#define IDMENU_LockItems                32764
#define IDMENU_AddItem                  32765
#define IDMENU_RemoveItem               32766
#define IDMENU_NewContact               32767
#define IDMENU_CallHome                 32768
#define IDMENU_CallMobile               32769
#define IDMENU_CallWork                 32770
#define IDMENU_SetContactPicture        32771
#define IDMENU_Unlock                   32772
#define IDMENU_SetContactCamera         32773
#define IDMENU_Cancel                   32774
#define IDMENU_SetContactRingtone       32775
#define IDMENU_Ok                       32776
#define IDMENU_Conversation             32777
#define IDMENU_Options                  32778
#define IDMENU_Help                     32779
#define IDMENU_EditContact              32780
#define IDMENU_DeleteContact            32781
#define IDMENU_About                    32782
#define IDMENU_MarkAllAsRead            32783
#define IDMENU_Delete                   32784
#define IDMENU_DeleteEntry              32785
#define IDMENU_DeleteAllSMS             32786
#define IDMENU_DeleteAllCalls           32787
#define IDMENU_DeleteAll                32788
#define IDM_HELP                        40001
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        279
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
