//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Launcherppc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_Contacts                    2
#define IDS_About_Launchpad             3
#define IDS_Close                       4
#define IDS_VERSION_Launchpad           5
#define IDS_NO_Programs                 6
#define IDS_SELECT_Program              7
#define IDS_SELECT_Setting              8
#define IDS_OPEN_File                   9
#define IDS_SAVE_File                   10
#define IDS_FILE_ExistOverwrite         11
#define IDS_Name                        12
#define IDS_Type                        13
#define IDS_Warning                     14
#define IDS_MY_Device                   15
#define IDS_TRIAL_Over                  16
#define IDS_Yes                         17
#define IDS_No                          18
#define IDS_On                          19
#define IDS_Off                         20
#define IDS_Large                       21
#define IDS_Small                       22
#define IDS_Normal                      23
#define IDS_Windows                     24
#define IDS_Rocket                      25
#define IDS_Default                     26
#define IDS_COLOR_Blue                  27
#define IDS_COLOR_Green                 28
#define IDS_COLOR_Pink                  29
#define IDS_COLOR_Purple                30
#define IDS_COLOR_Orange                31
#define IDS_COLOR_Red                   32
#define IDS_SLIDER_Apps                 33
#define IDS_SLIDER_Settings             34
#define IDS_SLIDER_Utilities            35
#define IDS_SLIDER_Music                36
#define IDS_SLIDER_Folders              37
#define IDS_SLIDER_Files                38
#define IDS_SLIDER_Pictures             39
#define IDS_SLIDER_Favorites            40
#define IDS_SLIDER_Videos               41
#define IDS_CAT_General                 42
#define IDS_SoftReset                   43
#define IDS_OPTION_ShowName             44
#define IDS_OPTION_HideOnAppLaunch      45
#define IDS_OPTION_SetTodayMenu         46
#define IDS_OPTION_SetStartMenu         47
#define IDS_OPTION_ColorScheme          48
#define IDS_OPTION_IconSize             49
#define IDS_OPTION_LeftSliderTitle      50
#define IDS_OPTION_RightSliderTitle     51
#define IDS_OPTION_StartMenu            52
#define IDS_OPTION_SeparateBySection    53
#define IDS_MENU_AddFileFolder          54
#define IDS_MENU_AddFavorite            55
#define IDS_Back                        56
#define IDS_Connections                 57
#define IDS_Today                       58
#define IDS_NO_Contacts                 59
#define IDS_TITLE_SelectContact         60
#define IDS_ITEM_Mobile                 61
#define IDS_ITEM_Home                   62
#define IDS_ITEM_HomeFax                63
#define IDS_ITEM_Work                   64
#define IDS_ITEM_WorkFax                65
#define IDS_ITEM_Car                    66
#define IDS_ITEM_Pager                  67
#define IDS_ITEM_Email                  68
#define IDS_MENU_AddContact             69
#define IDS_SLIDER_SelectTitle          70
#define IDS_SLIDER_Blank                71
#define IDS_OPTION_Background           72
#define IDS_SLIDER_Contacts             73
#define IDS_BK_TakePicture              74
#define IDS_BK_SelectPicture            75
#define IDS_OPTION_UseFullscreen        76
#define IDS_OPTION_DrawTiles            77
#define IDS_MENU_SoftReset              78
#define IDS_MENU_CloseAll               79
#define IDS_MSG_SoftReset               80
#define IDS_MENU_AddProgram             90
#define IDS_MENU_AddSetting             91
#define IDS_MENU_Quit                   100
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_MENU_Unlock                 105
#define IDS_MENU_Ok                     106
#define IDS_MENU_Cancel                 107
#define IDS_MENU_RemoveItem             109
#define IDS_MENU_DeleteContact          112
#define IDS_MENU_SmartArrange           113
#define IDS_MENU_LockItems              114
#define IDS_TOOLBAR_FAV                 115
#define IDS_TOOLBAR_CONTACTS            116
#define IDS_TOOLBAR_HISTORY             117
#define IDS_TOOLBAR_EXIT                118
#define IDS_SLIDER_Personal             119
#define IDS_SLIDER_Business             120
#define IDR_PNG_StartVGA                120
#define IDS_TOOLBAR_PROGRAMS            121
#define IDR_PNG_Start35                 121
#define IDS_TOOLBAR_SETTINGS            122
#define IDR_PNG_Start                   122
#define IDS_SLIDER_Programs             123
#define IDR_PNG_StartVGA2               123
#define IDS_SLIDER_Games                124
#define IDR_PNG_Start352                124
#define IDS_MENU_Open                   125
#define IDR_PNG_Start2                  125
#define IDS_MENU_Save                   126
#define IDR_MENU_Unlock                 179
#define IDR_MENU_OkCancel               180
#define IDR_BLUE_Arrow_VGA              180
#define IDD_DLG_Basic                   183
#define IDD_DLG_Add                     184
#define IDS_MENU_Options                191
#define IDS_MENU_Help                   193
#define IDS_MENU_About                  194
#define IDI_Launcher                    277
#define IDR_MENU_OpenMenu               278
#define IDR_MENU_SaveMenu               279
#define IDD_DIALOG1                     282
#define IDD_DLG_Blank                   282
#define IDR_BOT_VGA                     283
#define IDR_BOT                         284
#define IDR_BOT_Lan                     285
#define IDR_BOT_Lan_VGA                 286
#define IDR_PROG_Icons_VGA              287
#define IDR_PROG_Icons                  288
#define IDR_SEL_VGA                     289
#define IDR_SEL                         290
#define IDR_SEL_Lan                     291
#define IDR_SEL_Lan_VGA                 292
#define IDR_BLUE_Arrow_Lan_VGA          293
#define IDR_BLUE_Arrow                  294
#define IDR_BLUE_Arrow_Lan              295
#define IDR_GREEN_Arrow_Lan_VGA         297
#define IDR_GREEN_Arrow                 298
#define IDR_GREEN_Arrow_Lan             299
#define IDR_GREEN_Arrow_VGA             300
#define IDR_ORANGE_Arrow_Lan_VGA        301
#define IDR_ORANGE_Arrow                302
#define IDR_ORANGE_Arrow_Lan            303
#define IDR_ORANGE_Arrow_VGA            304
#define IDR_PINK_Arrow_Lan_VGA          305
#define IDR_PINK_Arrow                  306
#define IDR_PINK_Arrow_Lan              307
#define IDR_PINK_Arrow_VGA              308
#define IDR_PURPLE_Arrow_Lan_VGA        309
#define IDR_PURPLE_Arrow                310
#define IDR_PURPLE_Arrow_Lan            311
#define IDR_PURPLE_Arrow_VGA            312
#define IDR_RED_Arrow_Lan_VGA           313
#define IDR_RED_Arrow                   314
#define IDR_RED_Arrow_Lan               315
#define IDR_RED_Arrow_VGA               316
#define IDR_BLUE_Glow_VGA               317
#define IDR_BLUE_Glow                   318
#define IDR_GREEN_Glow                  319
#define IDR_GREEN_Glow_VGA              320
#define IDR_ORANGE_Glow_VGA             321
#define IDR_ORANGE_Glow                 322
#define IDR_PINK_Glow_VGA               323
#define IDR_PINK_Glow                   324
#define IDR_GIF1                        325
#define IDR_PURPLE_Glow_VGA             325
#define IDR_PURPLE_Glow                 326
#define IDR_RED_Glow_VGA                327
#define IDR_RED_Glow                    328
#define IDR_FOLDER_Arrow_VGA            329
#define IDR_FOLDER_Arrow                330
#define IDR_FOLDER_Arrow_Flip           331
#define IDR_FOLDER_Arrow_Flip_VGA       332
#define IDR_BLUE_IA_VGA                 333
#define IDR_BLUE_IA                     334
#define IDR_GREEN_IA_VGA                335
#define IDR_GREEN_IA                    336
#define IDR_ORANGE_IA_VGA               337
#define IDR_ORANGE_IA                   338
#define IDR_PINK_IA_VGA                 339
#define IDR_PINK_IA                     340
#define IDR_PURPLE_IA_VGA               341
#define IDR_PURPLE_IA                   342
#define IDR_RED_IA_VGA                  343
#define IDR_RED_IA                      344
#define IDR_BLUE_Selector_VGA           345
#define IDR_BLUE_Selector               346
#define IDR_PNG_Group                   347
#define IDR_GREEN_Selector_VGA          348
#define IDR_GREEN_Selector              349
#define IDR_ORANGE_Selector_VGA         350
#define IDR_ORANGE_Selector             351
#define IDR_PINK_Selector_VGA           352
#define IDR_PINK_Selector               353
#define IDR_PURPLE_Selector_VGA         354
#define IDR_PURPLE_Selector             355
#define IDR_RED_Selector_VGA            356
#define IDR_RED_Selector                357
#define IDR_GIF2                        358
#define IDR_DLG_Border_VGA              358
#define IDR_DLG_Border                  359
#define IDR_Close_VGA                   360
#define IDR_Box_Shine_VGA               361
#define IDR_GIF4                        362
#define IDR_RP                          362
#define IDR_Box_VGA                     363
#define IDR_Dots                        364
#define IDR_Dots_VGA                    365
#define IDR_Top                         366
#define IDR_Top_VGA                     367
#define IDR_Add                         368
#define IDR_Add_VGA                     369
#define IDR_Top_Lan                     370
#define IDR_Top_Lan_VGA                 371
#define IDR_BLUE_SelectorGlass_VGA      372
#define IDR_GREEN_SelectorGlass_VGA     373
#define IDR_ORANGE_SelectorGlass_VGA    374
#define IDR_PINK_SelectorGlass_VGA      375
#define IDR_PURPLE_SelectorGlass_VGA    376
#define IDR_RED_SelectorGlass_VGA       377
#define IDR_DETAILS_Mask                378
#define IDR_DETAILS_Mask_VGA            379
#define IDR_DETAILS_Border              380
#define IDR_DETAILS_Border_VGA          381
#define IDR_DETAILS_Default             382
#define IDR_DETAILS_Default_VGA         383
#define IDR_DETAILS_BackArrow           384
#define IDR_DETAILS_BackArrow_VGA       385
#define IDR_GREEN_DETAILS_ButtonSelect  386
#define IDR_GREEN_DETAILS_ButtonSelectVGA 387
#define IDR_DETAILS_Button              388
#define IDR_DETAILS_Button_VGA          389
#define IDR_BLUE_DETAILS_ButtonSelect   390
#define IDR_BLUE_DETAILS_ButtonSelectVGA 391
#define IDR_GIF5                        392
#define IDR_RP_VGA                      392
#define IDR_GIF6                        393
#define IDR_Close                       393
#define IDR_ORANGE_DETAILS_ButtonSelect 394
#define IDR_ORANGE_DETAILS_ButtonSelectVGA 395
#define IDR_PINK_DETAILS_ButtonSelect   398
#define IDR_PINK_DETAILS_ButtonSelectVGA 399
#define IDR_PURPLE_DETAILS_ButtonSelect 402
#define IDR_PURPLE_DETAILS_ButtonSelectVGA 403
#define IDR_RED_DETAILS_ButtonSelect    406
#define IDR_RED_DETAILS_ButtonSelectVGA 407
#define IDR_PNG_Today                   414
#define IDR_PNG_TodayVGA                415
#define IDR_RecycleBin                  416
#define IDR_RecycleBinVGA               417
#define IDS_About_Launchpad_ZH          4003
#define IDS_Close_ZH                    4004
#define IDS_VERSION_Launchpad_ZH        4005
#define IDS_NO_Programs_ZH              4006
#define IDS_SELECT_Program_ZH           4007
#define IDS_SELECT_Setting_ZH           4008
#define IDS_OPEN_File_ZH                4009
#define IDS_SAVE_File_ZH                4010
#define IDS_FILE_ExistOverwrite_ZH      4011
#define IDS_Name_ZH                     4012
#define IDS_Type_ZH                     4013
#define IDS_Warning_ZH                  4014
#define IDS_MY_Device_ZH                4015
#define IDS_TRIAL_Over_ZH               4016
#define IDS_Yes_ZH                      4017
#define IDS_No_ZH                       4018
#define IDS_On_ZH                       4019
#define IDS_Off_ZH                      4020
#define IDS_Large_ZH                    4021
#define IDS_Small_ZH                    4022
#define IDS_Normal_ZH                   4023
#define IDS_Windows_ZH                  4024
#define IDS_Rocket_ZH                   4025
#define IDS_Default_ZH                  4026
#define IDS_COLOR_Blue_ZH               4027
#define IDS_COLOR_Green_ZH              4028
#define IDS_COLOR_Pink_ZH               4029
#define IDS_COLOR_Purple_ZH             4030
#define IDS_COLOR_Orange_ZH             4031
#define IDS_COLOR_Red_ZH                4032
#define IDS_SLIDER_Apps_ZH              4033
#define IDS_SLIDER_Settings_ZH          4034
#define IDS_SLIDER_Utilities_ZH         4035
#define IDS_SLIDER_Music_ZH             4036
#define IDS_SLIDER_Folders_ZH           4037
#define IDS_SLIDER_Files_ZH             4038
#define IDS_SLIDER_Pictures_ZH          4039
#define IDS_SLIDER_Favorites_ZH         4040
#define IDS_SLIDER_Videos_ZH            4041
#define IDS_CAT_General_ZH              4042
#define IDS_SoftReset_ZH                4043
#define IDS_OPTION_ShowName_ZH          4044
#define IDS_OPTION_HideOnAppLaunch_ZH   4045
#define IDS_OPTION_SetTodayMenu_ZH      4046
#define IDS_OPTION_SetStartMenu_ZH      4047
#define IDS_OPTION_ColorScheme_ZH       4048
#define IDS_OPTION_IconSize_ZH          4049
#define IDS_OPTION_LeftSliderTitle_ZH   4050
#define IDS_OPTION_RightSliderTitle_ZH  4051
#define IDS_OPTION_StartMenu_ZH         4052
#define IDS_OPTION_SeparateBySection_ZH 4053
#define IDS_MENU_AddFileFolder_ZH       4054
#define IDS_MENU_AddFavorite_ZH         4055
#define IDS_Back_ZH                     4056
#define IDS_Connections_ZH              4057
#define IDS_Today_ZH                    4058
#define IDS_NO_Contacts_ZH              4059
#define IDS_TITLE_SelectContact_ZH      4060
#define IDS_ITEM_Mobile_ZH              4061
#define IDS_ITEM_Home_ZH                4062
#define IDS_ITEM_HomeFax_ZH             4063
#define IDS_ITEM_Work_ZH                4064
#define IDS_ITEM_WorkFax_ZH             4065
#define IDS_ITEM_Car_ZH                 4066
#define IDS_ITEM_Pager_ZH               4067
#define IDS_ITEM_Email_ZH               4068
#define IDS_MENU_AddContact_ZH          4069
#define IDS_SLIDER_SelectTitle_ZH       4070
#define IDS_SLIDER_Blank_ZH             4071
#define IDS_OPTION_Background_ZH        4072
#define IDS_SLIDER_Contacts_ZH          4073
#define IDS_BK_TakePicture_ZH           4074
#define IDS_BK_SelectPicture_ZH         4075
#define IDS_OPTION_UseFullscreen_ZH     4076
#define IDS_OPTION_DrawTiles_ZH         4077
#define IDS_MENU_SoftReset_ZH           4078
#define IDS_MENU_CloseAll_ZH            4079
#define IDS_MSG_SoftReset_ZH            4080
#define IDS_MENU_AddProgram_ZH          4090
#define IDS_MENU_AddSetting_ZH          4091
#define IDS_MENU_Quit_ZH                4100
#define IDS_OK_ZH                       4103
#define IDS_HELP_ZH                     4104
#define IDS_MENU_Unlock_ZH              4105
#define IDS_MENU_Ok_ZH                  4106
#define IDS_MENU_Cancel_ZH              4107
#define IDS_MENU_RemoveItem_ZH          4109
#define IDS_MENU_DeleteContact_ZH       4112
#define IDS_MENU_SmartArrange_ZH        4113
#define IDS_MENU_LockItems_ZH           4114
#define IDS_TOOLBAR_FAV_ZH              4115
#define IDS_TOOLBAR_CONTACTS_ZH         4116
#define IDS_TOOLBAR_HISTORY_ZH          4117
#define IDS_TOOLBAR_EXIT_ZH             4118
#define IDS_SLIDER_Personal_ZH          4119
#define IDS_SLIDER_Business_ZH          4120
#define IDS_TOOLBAR_PROGRAMS_ZH         4121
#define IDS_TOOLBAR_SETTINGS_ZH         4122
#define IDS_SLIDER_Programs_ZH          4123
#define IDS_SLIDER_Games_ZH             4124
#define IDS_MENU_Open_ZH                4125
#define IDS_MENU_Save_ZH                4126
#define IDS_MENU_Options_ZH             4191
#define IDS_MENU_Help_ZH                4193
#define IDS_MENU_About_ZH               4194
#define IDS_About_Launchpad_DE          7003
#define IDS_Close_DE                    7004
#define IDS_VERSION_Launchpad_DE        7005
#define IDS_NO_Programs_DE              7006
#define IDS_SELECT_Program_DE           7007
#define IDS_SELECT_Setting_DE           7008
#define IDS_OPEN_File_DE                7009
#define IDS_SAVE_File_DE                7010
#define IDS_FILE_ExistOverwrite_DE      7011
#define IDS_Name_DE                     7012
#define IDS_Type_DE                     7013
#define IDS_Warning_DE                  7014
#define IDS_MY_Device_DE                7015
#define IDS_TRIAL_Over_DE               7016
#define IDS_Yes_DE                      7017
#define IDS_No_DE                       7018
#define IDS_On_DE                       7019
#define IDS_Off_DE                      7020
#define IDS_Large_DE                    7021
#define IDS_Small_DE                    7022
#define IDS_Normal_DE                   7023
#define IDS_Windows_DE                  7024
#define IDS_Rocket_DE                   7025
#define IDS_Default_DE                  7026
#define IDS_COLOR_Blue_DE               7027
#define IDS_COLOR_Green_DE              7028
#define IDS_COLOR_Pink_DE               7029
#define IDS_COLOR_Purple_DE             7030
#define IDS_COLOR_Orange_DE             7031
#define IDS_COLOR_Red_DE                7032
#define IDS_SLIDER_Apps_DE              7033
#define IDS_SLIDER_Settings_DE          7034
#define IDS_SLIDER_Utilities_DE         7035
#define IDS_SLIDER_Music_DE             7036
#define IDS_SLIDER_Folders_DE           7037
#define IDS_SLIDER_Files_DE             7038
#define IDS_SLIDER_Pictures_DE          7039
#define IDS_SLIDER_Favorites_DE         7040
#define IDS_SLIDER_Videos_DE            7041
#define IDS_CAT_General_DE              7042
#define IDS_SoftReset_DE                7043
#define IDS_OPTION_ShowName_DE          7044
#define IDS_OPTION_HideOnAppLaunch_DE   7045
#define IDS_OPTION_SetTodayMenu_DE      7046
#define IDS_OPTION_SetStartMenu_DE      7047
#define IDS_OPTION_ColorScheme_DE       7048
#define IDS_OPTION_IconSize_DE          7049
#define IDS_OPTION_LeftSliderTitle_DE   7050
#define IDS_OPTION_RightSliderTitle_DE  7051
#define IDS_OPTION_StartMenu_DE         7052
#define IDS_OPTION_SeparateBySection_DE 7053
#define IDS_MENU_AddFileFolder_DE       7054
#define IDS_MENU_AddFavorite_DE         7055
#define IDS_Back_DE                     7056
#define IDS_Connections_DE              7057
#define IDS_Today_DE                    7058
#define IDS_NO_Contacts_DE              7059
#define IDS_TITLE_SelectContact_DE      7060
#define IDS_ITEM_Mobile_DE              7061
#define IDS_ITEM_Home_DE                7062
#define IDS_ITEM_HomeFax_DE             7063
#define IDS_ITEM_Work_DE                7064
#define IDS_ITEM_WorkFax_DE             7065
#define IDS_ITEM_Car_DE                 7066
#define IDS_ITEM_Pager_DE               7067
#define IDS_ITEM_Email_DE               7068
#define IDS_MENU_AddContact_DE          7069
#define IDS_SLIDER_SelectTitle_DE       7070
#define IDS_SLIDER_Blank_DE             7071
#define IDS_OPTION_Background_DE        7072
#define IDS_SLIDER_Contacts_DE          7073
#define IDS_BK_TakePicture_DE           7074
#define IDS_BK_SelectPicture_DE         7075
#define IDS_OPTION_UseFullscreen_DE     7076
#define IDS_OPTION_DrawTiles_DE         7077
#define IDS_MENU_SoftReset_DE           7078
#define IDS_MENU_CloseAll_DE            7079
#define IDS_MSG_SoftReset_DE            7080
#define IDS_MENU_AddProgram_DE          7090
#define IDS_MENU_AddSetting_DE          7091
#define IDS_MENU_Quit_DE                7100
#define IDS_OK_DE                       7103
#define IDS_HELP_DE                     7104
#define IDS_MENU_Unlock_DE              7105
#define IDS_MENU_Ok_DE                  7106
#define IDS_MENU_Cancel_DE              7107
#define IDS_MENU_RemoveItem_DE          7109
#define IDS_MENU_DeleteContact_DE       7112
#define IDS_MENU_SmartArrange_DE        7113
#define IDS_MENU_LockItems_DE           7114
#define IDS_TOOLBAR_FAV_DE              7115
#define IDS_TOOLBAR_CONTACTS_DE         7116
#define IDS_TOOLBAR_HISTORY_DE          7117
#define IDS_TOOLBAR_EXIT_DE             7118
#define IDS_SLIDER_Personal_DE          7119
#define IDS_SLIDER_Business_DE          7120
#define IDS_TOOLBAR_PROGRAMS_DE         7121
#define IDS_TOOLBAR_SETTINGS_DE         7122
#define IDS_SLIDER_Programs_DE          7123
#define IDS_SLIDER_Games_DE             7124
#define IDS_MENU_Open_DE                7125
#define IDS_MENU_Save_DE                7126
#define IDS_MENU_Options_DE             7191
#define IDS_MENU_Help_DE                7193
#define IDS_MENU_About_DE               7194
#define IDS_About_Launchpad_ES          10003
#define IDS_Close_ES                    10004
#define IDS_VERSION_Launchpad_ES        10005
#define IDS_NO_Programs_ES              10006
#define IDS_SELECT_Program_ES           10007
#define IDS_SELECT_Setting_ES           10008
#define IDS_OPEN_File_ES                10009
#define IDS_SAVE_File_ES                10010
#define IDS_FILE_ExistOverwrite_ES      10011
#define IDS_Name_ES                     10012
#define IDS_Type_ES                     10013
#define IDS_Warning_ES                  10014
#define IDS_MY_Device_ES                10015
#define IDS_TRIAL_Over_ES               10016
#define IDS_Yes_ES                      10017
#define IDS_No_ES                       10018
#define IDS_On_ES                       10019
#define IDS_Off_ES                      10020
#define IDS_Large_ES                    10021
#define IDS_Small_ES                    10022
#define IDS_Normal_ES                   10023
#define IDS_Windows_ES                  10024
#define IDS_Rocket_ES                   10025
#define IDS_Default_ES                  10026
#define IDS_COLOR_Blue_ES               10027
#define IDS_COLOR_Green_ES              10028
#define IDS_COLOR_Pink_ES               10029
#define IDS_COLOR_Purple_ES             10030
#define IDS_COLOR_Orange_ES             10031
#define IDS_COLOR_Red_ES                10032
#define IDS_SLIDER_Apps_ES              10033
#define IDS_SLIDER_Settings_ES          10034
#define IDS_SLIDER_Utilities_ES         10035
#define IDS_SLIDER_Music_ES             10036
#define IDS_SLIDER_Folders_ES           10037
#define IDS_SLIDER_Files_ES             10038
#define IDS_SLIDER_Pictures_ES          10039
#define IDS_SLIDER_Favorites_ES         10040
#define IDS_SLIDER_Videos_ES            10041
#define IDS_CAT_General_ES              10042
#define IDS_SoftReset_ES                10043
#define IDS_OPTION_ShowName_ES          10044
#define IDS_OPTION_HideOnAppLaunch_ES   10045
#define IDS_OPTION_SetTodayMenu_ES      10046
#define IDS_OPTION_SetStartMenu_ES      10047
#define IDS_OPTION_ColorScheme_ES       10048
#define IDS_OPTION_IconSize_ES          10049
#define IDS_OPTION_LeftSliderTitle_ES   10050
#define IDS_OPTION_RightSliderTitle_ES  10051
#define IDS_OPTION_StartMenu_ES         10052
#define IDS_OPTION_SeparateBySection_ES 10053
#define IDS_MENU_AddFileFolder_ES       10054
#define IDS_MENU_AddFavorite_ES         10055
#define IDS_Back_ES                     10056
#define IDS_Connections_ES              10057
#define IDS_Today_ES                    10058
#define IDS_NO_Contacts_ES              10059
#define IDS_TITLE_SelectContact_ES      10060
#define IDS_ITEM_Mobile_ES              10061
#define IDS_ITEM_Home_ES                10062
#define IDS_ITEM_HomeFax_ES             10063
#define IDS_ITEM_Work_ES                10064
#define IDS_ITEM_WorkFax_ES             10065
#define IDS_ITEM_Car_ES                 10066
#define IDS_ITEM_Pager_ES               10067
#define IDS_ITEM_Email_ES               10068
#define IDS_MENU_AddContact_ES          10069
#define IDS_SLIDER_SelectTitle_ES       10070
#define IDS_SLIDER_Blank_ES             10071
#define IDS_OPTION_Background_ES        10072
#define IDS_SLIDER_Contacts_ES          10073
#define IDS_BK_TakePicture_ES           10074
#define IDS_BK_SelectPicture_ES         10075
#define IDS_OPTION_UseFullscreen_ES     10076
#define IDS_OPTION_DrawTiles_ES         10077
#define IDS_MENU_SoftReset_ES           10078
#define IDS_MENU_CloseAll_ES            10079
#define IDS_MSG_SoftReset_ES            10080
#define IDS_MENU_AddProgram_ES          10090
#define IDS_MENU_AddSetting_ES          10091
#define IDS_MENU_Quit_ES                10100
#define IDS_OK_ES                       10103
#define IDS_HELP_ES                     10104
#define IDS_MENU_Unlock_ES              10105
#define IDS_MENU_Ok_ES                  10106
#define IDS_MENU_Cancel_ES              10107
#define IDS_MENU_RemoveItem_ES          10109
#define IDS_MENU_DeleteContact_ES       10112
#define IDS_MENU_SmartArrange_ES        10113
#define IDS_MENU_LockItems_ES           10114
#define IDS_TOOLBAR_FAV_ES              10115
#define IDS_TOOLBAR_CONTACTS_ES         10116
#define IDS_TOOLBAR_HISTORY_ES          10117
#define IDS_TOOLBAR_EXIT_ES             10118
#define IDS_SLIDER_Personal_ES          10119
#define IDS_SLIDER_Business_ES          10120
#define IDS_TOOLBAR_PROGRAMS_ES         10121
#define IDS_TOOLBAR_SETTINGS_ES         10122
#define IDS_SLIDER_Programs_ES          10123
#define IDS_SLIDER_Games_ES             10124
#define IDS_MENU_Open_ES                10125
#define IDS_MENU_Save_ES                10126
#define IDS_MENU_Options_ES             10191
#define IDS_MENU_Help_ES                10193
#define IDS_MENU_About_ES               10194
#define IDS_About_Launchpad_FR          12003
#define IDS_Close_FR                    12004
#define IDS_VERSION_Launchpad_FR        12005
#define IDS_NO_Programs_FR              12006
#define IDS_SELECT_Program_FR           12007
#define IDS_SELECT_Setting_FR           12008
#define IDS_OPEN_File_FR                12009
#define IDS_SAVE_File_FR                12010
#define IDS_FILE_ExistOverwrite_FR      12011
#define IDS_Name_FR                     12012
#define IDS_Type_FR                     12013
#define IDS_Warning_FR                  12014
#define IDS_MY_Device_FR                12015
#define IDS_TRIAL_Over_FR               12016
#define IDS_Yes_FR                      12017
#define IDS_No_FR                       12018
#define IDS_On_FR                       12019
#define IDS_Off_FR                      12020
#define IDS_Large_FR                    12021
#define IDS_Small_FR                    12022
#define IDS_Normal_FR                   12023
#define IDS_Windows_FR                  12024
#define IDS_Rocket_FR                   12025
#define IDS_Default_FR                  12026
#define IDS_COLOR_Blue_FR               12027
#define IDS_COLOR_Green_FR              12028
#define IDS_COLOR_Pink_FR               12029
#define IDS_COLOR_Purple_FR             12030
#define IDS_COLOR_Orange_FR             12031
#define IDS_COLOR_Red_FR                12032
#define IDS_SLIDER_Apps_FR              12033
#define IDS_SLIDER_Settings_FR          12034
#define IDS_SLIDER_Utilities_FR         12035
#define IDS_SLIDER_Music_FR             12036
#define IDS_SLIDER_Folders_FR           12037
#define IDS_SLIDER_Files_FR             12038
#define IDS_SLIDER_Pictures_FR          12039
#define IDS_SLIDER_Favorites_FR         12040
#define IDS_SLIDER_Videos_FR            12041
#define IDS_CAT_General_FR              12042
#define IDS_SoftReset_FR                12043
#define IDS_OPTION_ShowName_FR          12044
#define IDS_OPTION_HideOnAppLaunch_FR   12045
#define IDS_OPTION_SetTodayMenu_FR      12046
#define IDS_OPTION_SetStartMenu_FR      12047
#define IDS_OPTION_ColorScheme_FR       12048
#define IDS_OPTION_IconSize_FR          12049
#define IDS_OPTION_LeftSliderTitle_FR   12050
#define IDS_OPTION_RightSliderTitle_FR  12051
#define IDS_OPTION_StartMenu_FR         12052
#define IDS_OPTION_SeparateBySection_FR 12053
#define IDS_MENU_AddFileFolder_FR       12054
#define IDS_MENU_AddFavorite_FR         12055
#define IDS_Back_FR                     12056
#define IDS_Connections_FR              12057
#define IDS_Today_FR                    12058
#define IDS_NO_Contacts_FR              12059
#define IDS_TITLE_SelectContact_FR      12060
#define IDS_ITEM_Mobile_FR              12061
#define IDS_ITEM_Home_FR                12062
#define IDS_ITEM_HomeFax_FR             12063
#define IDS_ITEM_Work_FR                12064
#define IDS_ITEM_WorkFax_FR             12065
#define IDS_ITEM_Car_FR                 12066
#define IDS_ITEM_Pager_FR               12067
#define IDS_ITEM_Email_FR               12068
#define IDS_MENU_AddContact_FR          12069
#define IDS_SLIDER_SelectTitle_FR       12070
#define IDS_SLIDER_Blank_FR             12071
#define IDS_OPTION_Background_FR        12072
#define IDS_SLIDER_Contacts_FR          12073
#define IDS_BK_TakePicture_FR           12074
#define IDS_BK_SelectPicture_FR         12075
#define IDS_OPTION_UseFullscreen_FR     12076
#define IDS_OPTION_DrawTiles_FR         12077
#define IDS_MENU_SoftReset_FR           12078
#define IDS_MENU_CloseAll_FR            12079
#define IDS_MSG_SoftReset_FR            12080
#define IDS_MENU_AddProgram_FR          12090
#define IDS_MENU_AddSetting_FR          12091
#define IDS_MENU_Quit_FR                12100
#define IDS_OK_FR                       12103
#define IDS_HELP_FR                     12104
#define IDS_MENU_Unlock_FR              12105
#define IDS_MENU_Ok_FR                  12106
#define IDS_MENU_Cancel_FR              12107
#define IDS_MENU_RemoveItem_FR          12109
#define IDS_MENU_DeleteContact_FR       12112
#define IDS_MENU_SmartArrange_FR        12113
#define IDS_MENU_LockItems_FR           12114
#define IDS_TOOLBAR_FAV_FR              12115
#define IDS_TOOLBAR_CONTACTS_FR         12116
#define IDS_TOOLBAR_HISTORY_FR          12117
#define IDS_TOOLBAR_EXIT_FR             12118
#define IDS_SLIDER_Personal_FR          12119
#define IDS_SLIDER_Business_FR          12120
#define IDS_TOOLBAR_PROGRAMS_FR         12121
#define IDS_TOOLBAR_SETTINGS_FR         12122
#define IDS_SLIDER_Programs_FR          12123
#define IDS_SLIDER_Games_FR             12124
#define IDS_MENU_Open_FR                12125
#define IDS_MENU_Save_FR                12126
#define IDS_MENU_Options_FR             12191
#define IDS_MENU_Help_FR                12193
#define IDS_MENU_About_FR               12194
#define IDS_About_Launchpad_IT          16003
#define IDS_Close_IT                    16004
#define IDS_VERSION_Launchpad_IT        16005
#define IDS_NO_Programs_IT              16006
#define IDS_SELECT_Program_IT           16007
#define IDS_SELECT_Setting_IT           16008
#define IDS_OPEN_File_IT                16009
#define IDS_SAVE_File_IT                16010
#define IDS_FILE_ExistOverwrite_IT      16011
#define IDS_Name_IT                     16012
#define IDS_Type_IT                     16013
#define IDS_Warning_IT                  16014
#define IDS_MY_Device_IT                16015
#define IDS_TRIAL_Over_IT               16016
#define IDS_Yes_IT                      16017
#define IDS_No_IT                       16018
#define IDS_On_IT                       16019
#define IDS_Off_IT                      16020
#define IDS_Large_IT                    16021
#define IDS_Small_IT                    16022
#define IDS_Normal_IT                   16023
#define IDS_Windows_IT                  16024
#define IDS_Rocket_IT                   16025
#define IDS_Default_IT                  16026
#define IDS_COLOR_Blue_IT               16027
#define IDS_COLOR_Green_IT              16028
#define IDS_COLOR_Pink_IT               16029
#define IDS_COLOR_Purple_IT             16030
#define IDS_COLOR_Orange_IT             16031
#define IDS_COLOR_Red_IT                16032
#define IDS_SLIDER_Apps_IT              16033
#define IDS_SLIDER_Settings_IT          16034
#define IDS_SLIDER_Utilities_IT         16035
#define IDS_SLIDER_Music_IT             16036
#define IDS_SLIDER_Folders_IT           16037
#define IDS_SLIDER_Files_IT             16038
#define IDS_SLIDER_Pictures_IT          16039
#define IDS_SLIDER_Favorites_IT         16040
#define IDS_SLIDER_Videos_IT            16041
#define IDS_CAT_General_IT              16042
#define IDS_SoftReset_IT                16043
#define IDS_OPTION_ShowName_IT          16044
#define IDS_OPTION_HideOnAppLaunch_IT   16045
#define IDS_OPTION_SetTodayMenu_IT      16046
#define IDS_OPTION_SetStartMenu_IT      16047
#define IDS_OPTION_ColorScheme_IT       16048
#define IDS_OPTION_IconSize_IT          16049
#define IDS_OPTION_LeftSliderTitle_IT   16050
#define IDS_OPTION_RightSliderTitle_IT  16051
#define IDS_OPTION_StartMenu_IT         16052
#define IDS_OPTION_SeparateBySection_IT 16053
#define IDS_MENU_AddFileFolder_IT       16054
#define IDS_MENU_AddFavorite_IT         16055
#define IDS_Back_IT                     16056
#define IDS_Connections_IT              16057
#define IDS_Today_IT                    16058
#define IDS_NO_Contacts_IT              16059
#define IDS_TITLE_SelectContact_IT      16060
#define IDS_ITEM_Mobile_IT              16061
#define IDS_ITEM_Home_IT                16062
#define IDS_ITEM_HomeFax_IT             16063
#define IDS_ITEM_Work_IT                16064
#define IDS_ITEM_WorkFax_IT             16065
#define IDS_ITEM_Car_IT                 16066
#define IDS_ITEM_Pager_IT               16067
#define IDS_ITEM_Email_IT               16068
#define IDS_MENU_AddContact_IT          16069
#define IDS_SLIDER_SelectTitle_IT       16070
#define IDS_SLIDER_Blank_IT             16071
#define IDS_OPTION_Background_IT        16072
#define IDS_SLIDER_Contacts_IT          16073
#define IDS_BK_TakePicture_IT           16074
#define IDS_BK_SelectPicture_IT         16075
#define IDS_OPTION_UseFullscreen_IT     16076
#define IDS_OPTION_DrawTiles_IT         16077
#define IDS_MENU_SoftReset_IT           16078
#define IDS_MENU_CloseAll_IT            16079
#define IDS_MSG_SoftReset_IT            16080
#define IDS_MENU_AddProgram_IT          16090
#define IDS_MENU_AddSetting_IT          16091
#define IDS_MENU_Quit_IT                16100
#define IDS_OK_IT                       16103
#define IDS_HELP_IT                     16104
#define IDS_MENU_Unlock_IT              16105
#define IDS_MENU_Ok_IT                  16106
#define IDS_MENU_Cancel_IT              16107
#define IDS_MENU_RemoveItem_IT          16109
#define IDS_MENU_DeleteContact_IT       16112
#define IDS_MENU_SmartArrange_IT        16113
#define IDS_MENU_LockItems_IT           16114
#define IDS_TOOLBAR_FAV_IT              16115
#define IDS_TOOLBAR_CONTACTS_IT         16116
#define IDS_TOOLBAR_HISTORY_IT          16117
#define IDS_TOOLBAR_EXIT_IT             16118
#define IDS_SLIDER_Personal_IT          16119
#define IDS_SLIDER_Business_IT          16120
#define IDS_TOOLBAR_PROGRAMS_IT         16121
#define IDS_TOOLBAR_SETTINGS_IT         16122
#define IDS_SLIDER_Programs_IT          16123
#define IDS_SLIDER_Games_IT             16124
#define IDS_MENU_Open_IT                16125
#define IDS_MENU_Save_IT                16126
#define IDS_MENU_Options_IT             16191
#define IDS_MENU_Help_IT                16193
#define IDS_MENU_About_IT               16194
#define IDS_About_Launchpad_DU          19003
#define IDS_Close_DU                    19004
#define IDS_VERSION_Launchpad_DU        19005
#define IDS_NO_Programs_DU              19006
#define IDS_SELECT_Program_DU           19007
#define IDS_SELECT_Setting_DU           19008
#define IDS_OPEN_File_DU                19009
#define IDS_SAVE_File_DU                19010
#define IDS_FILE_ExistOverwrite_DU      19011
#define IDS_Name_DU                     19012
#define IDS_Type_DU                     19013
#define IDS_Warning_DU                  19014
#define IDS_MY_Device_DU                19015
#define IDS_TRIAL_Over_DU               19016
#define IDS_Yes_DU                      19017
#define IDS_No_DU                       19018
#define IDS_On_DU                       19019
#define IDS_Off_DU                      19020
#define IDS_Large_DU                    19021
#define IDS_Small_DU                    19022
#define IDS_Normal_DU                   19023
#define IDS_Windows_DU                  19024
#define IDS_Rocket_DU                   19025
#define IDS_Default_DU                  19026
#define IDS_COLOR_Blue_DU               19027
#define IDS_COLOR_Green_DU              19028
#define IDS_COLOR_Pink_DU               19029
#define IDS_COLOR_Purple_DU             19030
#define IDS_COLOR_Orange_DU             19031
#define IDS_COLOR_Red_DU                19032
#define IDS_SLIDER_Apps_DU              19033
#define IDS_SLIDER_Settings_DU          19034
#define IDS_SLIDER_Utilities_DU         19035
#define IDS_SLIDER_Music_DU             19036
#define IDS_SLIDER_Folders_DU           19037
#define IDS_SLIDER_Files_DU             19038
#define IDS_SLIDER_Pictures_DU          19039
#define IDS_SLIDER_Favorites_DU         19040
#define IDS_SLIDER_Videos_DU            19041
#define IDS_CAT_General_DU              19042
#define IDS_SoftReset_DU                19043
#define IDS_OPTION_ShowName_DU          19044
#define IDS_OPTION_HideOnAppLaunch_DU   19045
#define IDS_OPTION_SetTodayMenu_DU      19046
#define IDS_OPTION_SetStartMenu_DU      19047
#define IDS_OPTION_ColorScheme_DU       19048
#define IDS_OPTION_IconSize_DU          19049
#define IDS_OPTION_LeftSliderTitle_DU   19050
#define IDS_OPTION_RightSliderTitle_DU  19051
#define IDS_OPTION_StartMenu_DU         19052
#define IDS_OPTION_SeparateBySection_DU 19053
#define IDS_MENU_AddFileFolder_DU       19054
#define IDS_MENU_AddFavorite_DU         19055
#define IDS_Back_DU                     19056
#define IDS_Connections_DU              19057
#define IDS_Today_DU                    19058
#define IDS_NO_Contacts_DU              19059
#define IDS_TITLE_SelectContact_DU      19060
#define IDS_ITEM_Mobile_DU              19061
#define IDS_ITEM_Home_DU                19062
#define IDS_ITEM_HomeFax_DU             19063
#define IDS_ITEM_Work_DU                19064
#define IDS_ITEM_WorkFax_DU             19065
#define IDS_ITEM_Car_DU                 19066
#define IDS_ITEM_Pager_DU               19067
#define IDS_ITEM_Email_DU               19068
#define IDS_MENU_AddContact_DU          19069
#define IDS_SLIDER_SelectTitle_DU       19070
#define IDS_SLIDER_Blank_DU             19071
#define IDS_OPTION_Background_DU        19072
#define IDS_SLIDER_Contacts_DU          19073
#define IDS_BK_TakePicture_DU           19074
#define IDS_BK_SelectPicture_DU         19075
#define IDS_OPTION_UseFullscreen_DU     19076
#define IDS_OPTION_DrawTiles_DU         19077
#define IDS_MENU_SoftReset_DU           19078
#define IDS_MENU_CloseAll_DU            19079
#define IDS_MSG_SoftReset_DU            19080
#define IDS_MENU_AddProgram_DU          19090
#define IDS_MENU_AddSetting_DU          19091
#define IDS_MENU_Quit_DU                19100
#define IDS_OK_DU                       19103
#define IDS_HELP_DU                     19104
#define IDS_MENU_Unlock_DU              19105
#define IDS_MENU_Ok_DU                  19106
#define IDS_MENU_Cancel_DU              19107
#define IDS_MENU_RemoveItem_DU          19109
#define IDS_MENU_DeleteContact_DU       19112
#define IDS_MENU_SmartArrange_DU        19113
#define IDS_MENU_LockItems_DU           19114
#define IDS_TOOLBAR_FAV_DU              19115
#define IDS_TOOLBAR_CONTACTS_DU         19116
#define IDS_TOOLBAR_HISTORY_DU          19117
#define IDS_TOOLBAR_EXIT_DU             19118
#define IDS_SLIDER_Personal_DU          19119
#define IDS_SLIDER_Business_DU          19120
#define IDS_TOOLBAR_PROGRAMS_DU         19121
#define IDS_TOOLBAR_SETTINGS_DU         19122
#define IDS_SLIDER_Programs_DU          19123
#define IDS_SLIDER_Games_DU             19124
#define IDS_MENU_Open_DU                19125
#define IDS_MENU_Save_DU                19126
#define IDS_MENU_Options_DU             19191
#define IDS_MENU_Help_DU                19193
#define IDS_MENU_About_DU               19194
#define IDS_About_Launchpad_NO          20003
#define IDS_Close_NO                    20004
#define IDS_VERSION_Launchpad_NO        20005
#define IDS_NO_Programs_NO              20006
#define IDS_SELECT_Program_NO           20007
#define IDS_SELECT_Setting_NO           20008
#define IDS_OPEN_File_NO                20009
#define IDS_SAVE_File_NO                20010
#define IDS_FILE_ExistOverwrite_NO      20011
#define IDS_Name_NO                     20012
#define IDS_Type_NO                     20013
#define IDS_Warning_NO                  20014
#define IDS_MY_Device_NO                20015
#define IDS_TRIAL_Over_NO               20016
#define IDS_Yes_NO                      20017
#define IDS_No_NO                       20018
#define IDS_On_NO                       20019
#define IDS_Off_NO                      20020
#define IDS_Large_NO                    20021
#define IDS_Small_NO                    20022
#define IDS_Normal_NO                   20023
#define IDS_Windows_NO                  20024
#define IDS_Rocket_NO                   20025
#define IDS_Default_NO                  20026
#define IDS_COLOR_Blue_NO               20027
#define IDS_COLOR_Green_NO              20028
#define IDS_COLOR_Pink_NO               20029
#define IDS_COLOR_Purple_NO             20030
#define IDS_COLOR_Orange_NO             20031
#define IDS_COLOR_Red_NO                20032
#define IDS_SLIDER_Apps_NO              20033
#define IDS_SLIDER_Settings_NO          20034
#define IDS_SLIDER_Utilities_NO         20035
#define IDS_SLIDER_Music_NO             20036
#define IDS_SLIDER_Folders_NO           20037
#define IDS_SLIDER_Files_NO             20038
#define IDS_SLIDER_Pictures_NO          20039
#define IDS_SLIDER_Favorites_NO         20040
#define IDS_SLIDER_Videos_NO            20041
#define IDS_CAT_General_NO              20042
#define IDS_SoftReset_NO                20043
#define IDS_OPTION_ShowName_NO          20044
#define IDS_OPTION_HideOnAppLaunch_NO   20045
#define IDS_OPTION_SetTodayMenu_NO      20046
#define IDS_OPTION_SetStartMenu_NO      20047
#define IDS_OPTION_ColorScheme_NO       20048
#define IDS_OPTION_IconSize_NO          20049
#define IDS_OPTION_LeftSliderTitle_NO   20050
#define IDS_OPTION_RightSliderTitle_NO  20051
#define IDS_OPTION_StartMenu_NO         20052
#define IDS_OPTION_SeparateBySection_NO 20053
#define IDS_MENU_AddFileFolder_NO       20054
#define IDS_MENU_AddFavorite_NO         20055
#define IDS_Back_NO                     20056
#define IDS_Connections_NO              20057
#define IDS_Today_NO                    20058
#define IDS_NO_Contacts_NO              20059
#define IDS_TITLE_SelectContact_NO      20060
#define IDS_ITEM_Mobile_NO              20061
#define IDS_ITEM_Home_NO                20062
#define IDS_ITEM_HomeFax_NO             20063
#define IDS_ITEM_Work_NO                20064
#define IDS_ITEM_WorkFax_NO             20065
#define IDS_ITEM_Car_NO                 20066
#define IDS_ITEM_Pager_NO               20067
#define IDS_ITEM_Email_NO               20068
#define IDS_MENU_AddContact_NO          20069
#define IDS_SLIDER_SelectTitle_NO       20070
#define IDS_SLIDER_Blank_NO             20071
#define IDS_OPTION_Background_NO        20072
#define IDS_SLIDER_Contacts_NO          20073
#define IDS_BK_TakePicture_NO           20074
#define IDS_BK_SelectPicture_NO         20075
#define IDS_OPTION_UseFullscreen_NO     20076
#define IDS_OPTION_DrawTiles_NO         20077
#define IDS_MENU_SoftReset_NO           20078
#define IDS_MENU_CloseAll_NO            20079
#define IDS_MSG_SoftReset_NO            20080
#define IDS_MENU_AddProgram_NO          20090
#define IDS_MENU_AddSetting_NO          20091
#define IDS_MENU_Quit_NO                20100
#define IDS_OK_NO                       20103
#define IDS_HELP_NO                     20104
#define IDS_MENU_Unlock_NO              20105
#define IDS_MENU_Ok_NO                  20106
#define IDS_MENU_Cancel_NO              20107
#define IDS_MENU_RemoveItem_NO          20109
#define IDS_MENU_NOleteContact_NO       20112
#define IDS_MENU_SmartArrange_NO        20113
#define IDS_MENU_LockItems_NO           20114
#define IDS_TOOLBAR_FAV_NO              20115
#define IDS_TOOLBAR_CONTACTS_NO         20116
#define IDS_TOOLBAR_HISTORY_NO          20117
#define IDS_TOOLBAR_EXIT_NO             20118
#define IDS_SLIDER_Personal_NO          20119
#define IDS_SLIDER_Business_NO          20120
#define IDS_TOOLBAR_PROGRAMS_NO         20121
#define IDS_TOOLBAR_SETTINGS_NO         20122
#define IDS_SLIDER_Programs_NO          20123
#define IDS_SLIDER_Games_NO             20124
#define IDS_MENU_Open_NO                20125
#define IDS_MENU_Save_NO                20126
#define IDS_MENU_Options_NO             20191
#define IDS_MENU_Help_NO                20193
#define IDS_MENU_About_NO               20194
#define IDS_About_Launchpad_PT          22003
#define IDS_Close_PT                    22004
#define IDS_VERSION_Launchpad_PT        22005
#define IDS_NO_Programs_PT              22006
#define IDS_SELECT_Program_PT           22007
#define IDS_SELECT_Setting_PT           22008
#define IDS_OPEN_File_PT                22009
#define IDS_SAVE_File_PT                22010
#define IDS_FILE_ExistOverwrite_PT      22011
#define IDS_Name_PT                     22012
#define IDS_Type_PT                     22013
#define IDS_Warning_PT                  22014
#define IDS_MY_Device_PT                22015
#define IDS_TRIAL_Over_PT               22016
#define IDS_Yes_PT                      22017
#define IDS_No_PT                       22018
#define IDS_On_PT                       22019
#define IDS_Off_PT                      22020
#define IDS_Large_PT                    22021
#define IDS_Small_PT                    22022
#define IDS_Normal_PT                   22023
#define IDS_Windows_PT                  22024
#define IDS_Rocket_PT                   22025
#define IDS_Default_PT                  22026
#define IDS_COLOR_Blue_PT               22027
#define IDS_COLOR_Green_PT              22028
#define IDS_COLOR_Pink_PT               22029
#define IDS_COLOR_Purple_PT             22030
#define IDS_COLOR_Orange_PT             22031
#define IDS_COLOR_Red_PT                22032
#define IDS_SLIDER_Apps_PT              22033
#define IDS_SLIDER_Settings_PT          22034
#define IDS_SLIDER_Utilities_PT         22035
#define IDS_SLIDER_Music_PT             22036
#define IDS_SLIDER_Folders_PT           22037
#define IDS_SLIDER_Files_PT             22038
#define IDS_SLIDER_Pictures_PT          22039
#define IDS_SLIDER_Favorites_PT         22040
#define IDS_SLIDER_Videos_PT            22041
#define IDS_CAT_General_PT              22042
#define IDS_SoftReset_PT                22043
#define IDS_OPTION_ShowName_PT          22044
#define IDS_OPTION_HideOnAppLaunch_PT   22045
#define IDS_OPTION_SetTodayMenu_PT      22046
#define IDS_OPTION_SetStartMenu_PT      22047
#define IDS_OPTION_ColorScheme_PT       22048
#define IDS_OPTION_IconSize_PT          22049
#define IDS_OPTION_LeftSliderTitle_PT   22050
#define IDS_OPTION_RightSliderTitle_PT  22051
#define IDS_OPTION_StartMenu_PT         22052
#define IDS_OPTION_SeparateBySection_PT 22053
#define IDS_MENU_AddFileFolder_PT       22054
#define IDS_MENU_AddFavorite_PT         22055
#define IDS_Back_PT                     22056
#define IDS_Connections_PT              22057
#define IDS_Today_PT                    22058
#define IDS_NO_Contacts_PT              22059
#define IDS_TITLE_SelectContact_PT      22060
#define IDS_ITEM_Mobile_PT              22061
#define IDS_ITEM_Home_PT                22062
#define IDS_ITEM_HomeFax_PT             22063
#define IDS_ITEM_Work_PT                22064
#define IDS_ITEM_WorkFax_PT             22065
#define IDS_ITEM_Car_PT                 22066
#define IDS_ITEM_Pager_PT               22067
#define IDS_ITEM_Email_PT               22068
#define IDS_MENU_AddContact_PT          22069
#define IDS_SLIDER_SelectTitle_PT       22070
#define IDS_SLIDER_Blank_PT             22071
#define IDS_OPTION_Background_PT        22072
#define IDS_SLIDER_Contacts_PT          22073
#define IDS_BK_TakePicture_PT           22074
#define IDS_BK_SelectPicture_PT         22075
#define IDS_OPTION_UseFullscreen_PT     22076
#define IDS_OPTION_DrawTiles_PT         22077
#define IDS_MENU_SoftReset_PT           22078
#define IDS_MENU_CloseAll_PT            22079
#define IDS_MSG_SoftReset_PT            22080
#define IDS_MENU_AddProgram_PT          22090
#define IDS_MENU_AddSetting_PT          22091
#define IDS_MENU_Quit_PT                22100
#define IDS_OK_PT                       22103
#define IDS_HELP_PT                     22104
#define IDS_MENU_Unlock_PT              22105
#define IDS_MENU_Ok_PT                  22106
#define IDS_MENU_Cancel_PT              22107
#define IDS_MENU_RemoveItem_PT          22109
#define IDS_MENU_DeleteContact_PT       22112
#define IDS_MENU_SmartArrange_PT        22113
#define IDS_MENU_LockItems_PT           22114
#define IDS_TOOLBAR_FAV_PT              22115
#define IDS_TOOLBAR_CONTACTS_PT         22116
#define IDS_TOOLBAR_HISTORY_PT          22117
#define IDS_TOOLBAR_EXIT_PT             22118
#define IDS_SLIDER_Personal_PT          22119
#define IDS_SLIDER_Business_PT          22120
#define IDS_TOOLBAR_PROGRAMS_PT         22121
#define IDS_TOOLBAR_SETTINGS_PT         22122
#define IDS_SLIDER_Programs_PT          22123
#define IDS_SLIDER_Games_PT             22124
#define IDS_MENU_Open_PT                22125
#define IDS_MENU_Save_PT                22126
#define IDS_MENU_Options_PT             22191
#define IDS_MENU_Help_PT                22193
#define IDS_MENU_About_PT               22194
#define IDS_About_Launchpad_RO          24003
#define IDS_Close_RO                    24004
#define IDS_VERSION_Launchpad_RO        24005
#define IDS_NO_Programs_RO              24006
#define IDS_SELECT_Program_RO           24007
#define IDS_SELECT_Setting_RO           24008
#define IDS_OPEN_File_RO                24009
#define IDS_SAVE_File_RO                24010
#define IDS_FILE_ExistOverwrite_RO      24011
#define IDS_Name_RO                     24012
#define IDS_Type_RO                     24013
#define IDS_Warning_RO                  24014
#define IDS_MY_Device_RO                24015
#define IDS_TRIAL_Over_RO               24016
#define IDS_Yes_RO                      24017
#define IDS_No_RO                       24018
#define IDS_On_RO                       24019
#define IDS_Off_RO                      24020
#define IDS_Large_RO                    24021
#define IDS_Small_RO                    24022
#define IDS_Normal_RO                   24023
#define IDS_Windows_RO                  24024
#define IDS_Rocket_RO                   24025
#define IDS_Default_RO                  24026
#define IDS_COLOR_Blue_RO               24027
#define IDS_COLOR_Green_RO              24028
#define IDS_COLOR_Pink_RO               24029
#define IDS_COLOR_Purple_RO             24030
#define IDS_COLOR_Orange_RO             24031
#define IDS_COLOR_Red_RO                24032
#define IDS_SLIDER_Apps_RO              24033
#define IDS_SLIDER_Settings_RO          24034
#define IDS_SLIDER_Utilities_RO         24035
#define IDS_SLIDER_Music_RO             24036
#define IDS_SLIDER_Folders_RO           24037
#define IDS_SLIDER_Files_RO             24038
#define IDS_SLIDER_Pictures_RO          24039
#define IDS_SLIDER_Favorites_RO         24040
#define IDS_SLIDER_Videos_RO            24041
#define IDS_CAT_General_RO              24042
#define IDS_SoftReset_RO                24043
#define IDS_OPTION_ShowName_RO          24044
#define IDS_OPTION_HideOnAppLaunch_RO   24045
#define IDS_OPTION_SetTodayMenu_RO      24046
#define IDS_OPTION_SetStartMenu_RO      24047
#define IDS_OPTION_ColorScheme_RO       24048
#define IDS_OPTION_IconSize_RO          24049
#define IDS_OPTION_LeftSliderTitle_RO   24050
#define IDS_OPTION_RightSliderTitle_RO  24051
#define IDS_OPTION_StartMenu_RO         24052
#define IDS_OPTION_SeparateBySection_RO 24053
#define IDS_MENU_AddFileFolder_RO       24054
#define IDS_MENU_AddFavorite_RO         24055
#define IDS_Back_RO                     24056
#define IDS_Connections_RO              24057
#define IDS_Today_RO                    24058
#define IDS_NO_Contacts_RO              24059
#define IDS_TITLE_SelectContact_RO      24060
#define IDS_ITEM_Mobile_RO              24061
#define IDS_ITEM_Home_RO                24062
#define IDS_ITEM_HomeFax_RO             24063
#define IDS_ITEM_Work_RO                24064
#define IDS_ITEM_WorkFax_RO             24065
#define IDS_ITEM_Car_RO                 24066
#define IDS_ITEM_Pager_RO               24067
#define IDS_ITEM_Email_RO               24068
#define IDS_MENU_AddContact_RO          24069
#define IDS_SLIDER_SelectTitle_RO       24070
#define IDS_SLIDER_Blank_RO             24071
#define IDS_OPTION_Background_RO        24072
#define IDS_SLIDER_Contacts_RO          24073
#define IDS_BK_TakePicture_RO           24074
#define IDS_BK_SelectPicture_RO         24075
#define IDS_OPTION_UseFullscreen_RO     24076
#define IDS_OPTION_DrawTiles_RO         24077
#define IDS_MENU_SoftReset_RO           24078
#define IDS_MENU_CloseAll_RO            24079
#define IDS_MSG_SoftReset_RO            24080
#define IDS_MENU_AddProgram_RO          24090
#define IDS_MENU_AddSetting_RO          24091
#define IDS_MENU_Quit_RO                24100
#define IDS_OK_RO                       24103
#define IDS_HELP_RO                     24104
#define IDS_MENU_Unlock_RO              24105
#define IDS_MENU_Ok_RO                  24106
#define IDS_MENU_Cancel_RO              24107
#define IDS_MENU_RemoveItem_RO          24109
#define IDS_MENU_ROleteContact_RO       24112
#define IDS_MENU_SmartArrange_RO        24113
#define IDS_MENU_LockItems_RO           24114
#define IDS_TOOLBAR_FAV_RO              24115
#define IDS_TOOLBAR_CONTACTS_RO         24116
#define IDS_TOOLBAR_HISTORY_RO          24117
#define IDS_TOOLBAR_EXIT_RO             24118
#define IDS_SLIDER_Personal_RO          24119
#define IDS_SLIDER_Business_RO          24120
#define IDS_TOOLBAR_PROGRAMS_RO         24121
#define IDS_TOOLBAR_SETTINGS_RO         24122
#define IDS_SLIDER_Programs_RO          24123
#define IDS_SLIDER_Games_RO             24124
#define IDS_MENU_Open_RO                24125
#define IDS_MENU_Save_RO                24126
#define IDS_MENU_Options_RO             24191
#define IDS_MENU_Help_RO                24193
#define IDS_MENU_About_RO               24194
#define IDS_About_Launchpad_RU          25003
#define IDS_Close_RU                    25004
#define IDS_VERSION_Launchpad_RU        25005
#define IDS_NO_Programs_RU              25006
#define IDS_SELECT_Program_RU           25007
#define IDS_SELECT_Setting_RU           25008
#define IDS_OPEN_File_RU                25009
#define IDS_SAVE_File_RU                25010
#define IDS_FILE_ExistOverwrite_RU      25011
#define IDS_Name_RU                     25012
#define IDS_Type_RU                     25013
#define IDS_Warning_RU                  25014
#define IDS_MY_Device_RU                25015
#define IDS_TRIAL_Over_RU               25016
#define IDS_Yes_RU                      25017
#define IDS_No_RU                       25018
#define IDS_On_RU                       25019
#define IDS_Off_RU                      25020
#define IDS_Large_RU                    25021
#define IDS_Small_RU                    25022
#define IDS_Normal_RU                   25023
#define IDS_Windows_RU                  25024
#define IDS_Rocket_RU                   25025
#define IDS_Default_RU                  25026
#define IDS_COLOR_Blue_RU               25027
#define IDS_COLOR_Green_RU              25028
#define IDS_COLOR_Pink_RU               25029
#define IDS_COLOR_Purple_RU             25030
#define IDS_COLOR_Orange_RU             25031
#define IDS_COLOR_Red_RU                25032
#define IDS_SLIDER_Apps_RU              25033
#define IDS_SLIDER_Settings_RU          25034
#define IDS_SLIDER_Utilities_RU         25035
#define IDS_SLIDER_Music_RU             25036
#define IDS_SLIDER_Folders_RU           25037
#define IDS_SLIDER_Files_RU             25038
#define IDS_SLIDER_Pictures_RU          25039
#define IDS_SLIDER_Favorites_RU         25040
#define IDS_SLIDER_Videos_RU            25041
#define IDS_CAT_General_RU              25042
#define IDS_SoftReset_RU                25043
#define IDS_OPTION_ShowName_RU          25044
#define IDS_OPTION_HideOnAppLaunch_RU   25045
#define IDS_OPTION_SetTodayMenu_RU      25046
#define IDS_OPTION_SetStartMenu_RU      25047
#define IDS_OPTION_ColorScheme_RU       25048
#define IDS_OPTION_IconSize_RU          25049
#define IDS_OPTION_LeftSliderTitle_RU   25050
#define IDS_OPTION_RightSliderTitle_RU  25051
#define IDS_OPTION_StartMenu_RU         25052
#define IDS_OPTION_SeparateBySection_RU 25053
#define IDS_MENU_AddFileFolder_RU       25054
#define IDS_MENU_AddFavorite_RU         25055
#define IDS_Back_RU                     25056
#define IDS_Connections_RU              25057
#define IDS_Today_RU                    25058
#define IDS_NO_Contacts_RU              25059
#define IDS_TITLE_SelectContact_RU      25060
#define IDS_ITEM_Mobile_RU              25061
#define IDS_ITEM_Home_RU                25062
#define IDS_ITEM_HomeFax_RU             25063
#define IDS_ITEM_Work_RU                25064
#define IDS_ITEM_WorkFax_RU             25065
#define IDS_ITEM_Car_RU                 25066
#define IDS_ITEM_Pager_RU               25067
#define IDS_ITEM_Email_RU               25068
#define IDS_MENU_AddContact_RU          25069
#define IDS_SLIDER_SelectTitle_RU       25070
#define IDS_SLIDER_Blank_RU             25071
#define IDS_OPTION_Background_RU        25072
#define IDS_SLIDER_Contacts_RU          25073
#define IDS_BK_TakePicture_RU           25074
#define IDS_BK_SelectPicture_RU         25075
#define IDS_OPTION_UseFullscreen_RU     25076
#define IDS_OPTION_DrawTiles_RU         25077
#define IDS_MENU_SoftReset_RU           25078
#define IDS_MENU_CloseAll_RU            25079
#define IDS_MSG_SoftReset_RU            25080
#define IDS_MENU_AddProgram_RU          25090
#define IDS_MENU_AddSetting_RU          25091
#define IDS_MENU_Quit_RU                25100
#define IDS_OK_RU                       25103
#define IDS_HELP_RU                     25104
#define IDS_MENU_Unlock_RU              25105
#define IDS_MENU_Ok_RU                  25106
#define IDS_MENU_Cancel_RU              25107
#define IDS_MENU_RemoveItem_RU          25109
#define IDS_MENU_RUleteContact_RU       25112
#define IDS_MENU_SmartArrange_RU        25113
#define IDS_MENU_LockItems_RU           25114
#define IDS_TOOLBAR_FAV_RU              25115
#define IDS_TOOLBAR_CONTACTS_RU         25116
#define IDS_TOOLBAR_HISTORY_RU          25117
#define IDS_TOOLBAR_EXIT_RU             25118
#define IDS_SLIDER_Personal_RU          25119
#define IDS_SLIDER_Business_RU          25120
#define IDS_TOOLBAR_PROGRAMS_RU         25121
#define IDS_TOOLBAR_SETTINGS_RU         25122
#define IDS_SLIDER_Programs_RU          25123
#define IDS_SLIDER_Games_RU             25124
#define IDS_MENU_Open_RU                25125
#define IDS_MENU_Save_RU                25126
#define IDS_MENU_Options_RU             25191
#define IDS_MENU_Help_RU                25193
#define IDS_MENU_About_RU               25194
#define IDMENU_SoftReset                32757
#define IDMENU_CloseAll                 32758
#define IDMENU_RunningPrograms          32759
#define IDMENU_Quit                     32760
#define IDMENU_AddProgram               32761
#define IDMENU_AddSetting               32762
#define IDMENU_SmartArrange             32763
#define IDMENU_LockItems                32764
#define IDMENU_AddItem                  32765
#define IDMENU_RemoveItem               32766
#define IDMENU_NewContact               32767
#define IDMENU_CallHome                 32768
#define IDMENU_CallMobile               32769
#define IDMENU_CallWork                 32770
#define IDMENU_SetContactPicture        32771
#define IDMENU_Unlock                   32772
#define IDMENU_SetContactCamera         32773
#define IDMENU_Cancel                   32774
#define IDMENU_Ok                       32776
#define IDMENU_Conversation             32777
#define IDMENU_Options                  32778
#define IDMENU_Open                     32778
#define IDMENU_Help                     32779
#define IDMENU_EditContact              32780
#define IDMENU_DeleteContact            32781
#define IDMENU_Save                     32781
#define IDMENU_About                    32782
#define IDMENU_MarkAllAsRead            32783
#define IDMENU_AddFileFolder            32784
#define IDMENU_Menu                     32785
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        394
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
