//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Hextrisppc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_Hextris                     2
#define IDS_MAIN_CLASS                  3
#define IDS_SOFTKEY_TEXT_LEFT           4
#define IDS_SOFTKEY_TEXT_RIGHT          5
#define IDS_MESSAGE_Save                6
#define IDS_CloseWindowMessage          6
#define IDS_MENU_Restart                6
#define IDS_DEMO_Over                   7
#define IDS_MENU_GameClassic            8
#define IDS_MENU_GameChallenge          9
#define IDS_MENU_Game40                 10
#define IDS_MENU_GameTimed              11
#define IDS_MENU_Pause                  12
#define IDS_MENU_HiScores               13
#define IDS_MENU_About                  14
#define IDS_MENU_Help                   15
#define IDS_MENU_NewGame                16
#define IDS_MENU_Resume                 17
#define IDS_ABOUT_1                     18
#define IDS_ABOUT_2                     19
#define IDS_MENU_Back                   19
#define IDS_LBL_Music                   20
#define IDS_LBL_Effects                 21
#define IDS_LBL_FPS                     22
#define IDS_LBL_GameMode                23
#define IDS_LBL_Desc1                   24
#define IDS_LBL_GM1                     25
#define IDS_LBL_Desc2                   26
#define IDS_LBL_GM2                     27
#define IDS_LBL_Desc3                   28
#define IDS_LBL_GM3                     29
#define IDS_LBL_Desc4                   30
#define IDS_LBL_GM4                     31
#define IDS_LBL_StartLevel              32
#define IDS_LBL_Score                   33
#define IDS_LBL_Date                    34
#define IDS_STRING35                    35
#define IDS_LBL_Mode                    35
#define IDS_LBL_Level                   36
#define IDS_MENU_Yes                    37
#define IDS_MENU_No                     38
#define IDS_LBL_GameOver                39
#define IDS_LBL_PlayAgain               40
#define IDS_MENU_Options                42
#define IDS_MENU_Quit                   45
#define IDS_MENU_Exit                   46
#define IDS_LBL_ScoreText               47
#define IDS_LBL_ScoreHight              48
#define IDS_LBL_ScoreHigh               48
#define IDS_IMPLICIT_SOFTWARE           61
#define IDS_WEBSITE                     62
#define IDS_VERSION                     63
#define IDS_LBL_PowerSaving             64
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDS_TOOLS                       105
#define IDD_DLG_Basic                   129
#define IDR_MENU_Options                131
#define IDR_MENU_Hextris                132
#define IDR_PNG_Ghost                   132
#define IDS_NAME_Hextris                141
#define IDD_DLG_Child                   146
#define IDC_LST_ND                      147
#define IDI_Hextris                     148
#define IDR_GIF1                        148
#define IDR_PNG_Gems                    148
#define IDR_BEVEL                       150
#define IDR_SPLASH                      151
#define IDR_SPLASH_VGA                  152
#define IDR_PNG_ANI                     153
#define IDR_PTMOD2                      156
#define IDR_LOGO                        157
#define IDR_LOGO_VGA                    158
#define IDR_LOGO_Alpha                  158
#define IDR_PNG_Explosion               159
#define IDWAV_DOWN                      160
#define IDR_PNG_ExpAlpha                160
#define IDWAV_GAMEOVER                  161
#define IDR_P1_BR                       161
#define IDWAV_LEVELUP                   162
#define IDWAV_LINECLEAR                 163
#define IDWAV_LINECLEARMULTI            164
#define IDWAV_MOVE                      165
#define IDWAV_NEWHIGHSCORE              166
#define IDWAV_SWITCH                    167
#define IDR_MNA_B                       168
#define IDR_MNA_BL                      169
#define IDR_MNA_BR                      170
#define IDR_GIF8                        171
#define IDR_MNA_L                       171
#define IDR_MNA_M                       172
#define IDR_MNA_R                       173
#define IDR_PNG_OrbAlpha                177
#define IDR_PNG_Fireball                178
#define IDR_PNG_FireballAlpha           179
#define IDR_PNG_Orb                     180
#define IDR_PNG_Items                   181
#define IDR_PNG_ItemsAlpha              182
#define IDR_MNA_T                       183
#define IDR_MNA_TL                      184
#define IDR_MNA_TR                      185
#define IDR_MN_B                        186
#define IDR_MN_BL                       187
#define IDR_MN_BR                       188
#define IDR_MN_L                        189
#define IDR_MN_M                        190
#define IDR_MN_R                        191
#define IDR_MN_T                        192
#define IDR_MN_TL                       193
#define IDR_MN_TR                       194
#define IDR_GIF5                        195
#define IDR_GS1_B                       195
#define IDR_GIF6                        196
#define IDR_GS1_BL                      196
#define IDR_GIF7                        197
#define IDR_GS1_BR                      197
#define IDR_GIF9                        198
#define IDR_GS1_L                       198
#define IDR_GS1_R                       199
#define IDS_MENU_Menu                   200
#define IDR_GS1_T                       200
#define IDS_MENU_Game                   201
#define IDR_GS1_TL                      201
#define IDR_GS1_TR                      202
#define IDS_MSG_Help                    202
#define IDS_MSG_Exit                    202
#define IDR_GS2_B                       203
#define IDR_GS2_BL                      204
#define IDR_GS2_BR                      205
#define IDR_GS2_L                       206
#define IDR_GS2_R                       207
#define IDR_GS2_T                       208
#define IDR_GS2_TL                      209
#define IDR_GS2_TR                      210
#define IDR_GS_M                        211
#define IDR_GS3_B                       212
#define IDR_GS3_BL                      213
#define IDR_GS3_BR                      214
#define IDR_GS3_L                       215
#define IDR_GS3_M                       216
#define IDR_GS3_R                       217
#define IDR_GS3_T                       218
#define IDR_GS3_TL                      219
#define IDR_GIF18                       220
#define IDR_GS3_TR                      220
#define IDR_TILE_BG                     221
#define IDR_SLOGO                       222
#define IDR_SLOGO_Alpha                 223
#define IDR_GIF10                       224
#define IDR_GFont                       224
#define IDR_GFont_Alpha                 225
#define IDC_SPIN1                       305
#define IDC_SPIN2                       306
#define IDC_SPIN3                       307
#define IDC_SPIN4                       308
#define IDR_PNG_Pulse                   309
#define IDR_PNG_PulseAlpha              310
#define IDWAV_EXPLODE		            311
#define IDMENU_NewGame                  32763
#define IDMENU_Options                  32764
#define IDMENU_Restart                  32765
#define IDMENU_GameClassic              32766
#define IDMENU_GameChallenge            32767
#define IDMENU_GameUltra                32768
#define IDMENU_Game40                   32769
#define IDMENU_Pause                    32770
#define IDMENU_HiScores                 32771
#define IDMENU_Help                     32772
#define IDMENU_About                    32773
#define IDMENU_Exit                     32774
#define IDMENU_Menu                     32792
#define IDMENU_Game                     32793
#define IDMENU_Resume                   32794
#define IDMENU_Quit                     32795
#define IDM_HELP                        40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
